force-app/main/default/objects/Case/fields/Code_Ann_e_Etudiant__c.field-meta.xml
<CustomField>
    <fullName>Code_Ann_e_Etudiant__c</fullName>
    <description>Permet le changement de tables de règles si changement de dates</description>
    <label>Code Année Etudiant</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <label>Programme</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/Convsta_Conditions_Contractuelles__c.object-meta.xml
<CustomObject>
    <description>Informations relatives aux conditions contractuelles de l&apos;étudiant en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Conditions Contractuelles</label>
    <nameField>
        <displayFormat>contrat-{000000}</displayFormat>
        <label>Convsta Conditions Contractuelles</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions Contractuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/Date_Debut__c.field-meta.xml
<CustomField>
    <fullName>Date_Debut__c</fullName>
    <description>La date à laquelle commence l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Date à laquelle commence l&apos;expérience professionnelle de l&apos;étudiant</inlineHelpText>
    <label>Date de Début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/Date_Fin__c.field-meta.xml
<CustomField>
    <fullName>Date_Fin__c</fullName>
    <description>La date à laquelle se termine l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Date à laquelle se termine l&apos;expérience professionnelle de l&apos;étudiant</inlineHelpText>
    <label>Date de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Conditions Contractuelles</relationshipLabel>
    <relationshipName>Conditions_Contractuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Accessible_aux_etudiants__c.field-meta.xml
<CustomField>
    <fullName>Accessible_aux_etudiants__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accessible aux étudiants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Ann_e_suivante__c.field-meta.xml
<CustomField>
    <fullName>Ann_e_suivante__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique que la table doit être rattachée aux demandes de l&apos;année en cours pour l&apos;année suivante</description>
    <label>Année suivante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Annee_Application__c.field-meta.xml
<CustomField>
    <fullName>Annee_Application__c</fullName>
    <inlineHelpText>Les 4 premiers caractères du code étudiant des étudiants concernés</inlineHelpText>
    <label>Préfixe du code étudiant</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Code_etude__c.field-meta.xml
<CustomField>
    <fullName>Code_etude__c</fullName>
    <label>Code étude / Année actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Programme__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU2MS</fullName>
            </value>
            <value>
                <fullName>AUBBA</fullName>
            </value>
            <value>
                <fullName>AUBBAC</fullName>
            </value>
            <value>
                <fullName>AUGP</fullName>
            </value>
            <value>
                <fullName>AUMBA</fullName>
            </value>
            <value>
                <fullName>BBA0</fullName>
            </value>
            <value>
                <fullName>BBA1</fullName>
            </value>
            <value>
                <fullName>BBA2</fullName>
            </value>
            <value>
                <fullName>BBA3</fullName>
            </value>
            <value>
                <fullName>BBA4</fullName>
            </value>
            <value>
                <fullName>BBAB1</fullName>
            </value>
            <value>
                <fullName>BBAB2</fullName>
            </value>
            <value>
                <fullName>BBAB3</fullName>
            </value>
            <value>
                <fullName>BBAB4</fullName>
            </value>
            <value>
                <fullName>BBAC1</fullName>
            </value>
            <value>
                <fullName>BBAC2</fullName>
            </value>
            <value>
                <fullName>BBAC3</fullName>
            </value>
            <value>
                <fullName>BBAC4</fullName>
            </value>
            <value>
                <fullName>BBAH1</fullName>
            </value>
            <value>
                <fullName>BBAH2</fullName>
            </value>
            <value>
                <fullName>BBAH3</fullName>
            </value>
            <value>
                <fullName>BBAH4</fullName>
            </value>
            <value>
                <fullName>BBAP0</fullName>
            </value>
            <value>
                <fullName>BBAP1</fullName>
            </value>
            <value>
                <fullName>BBAP2</fullName>
            </value>
            <value>
                <fullName>BBAP3</fullName>
            </value>
            <value>
                <fullName>BBAP4</fullName>
            </value>
            <value>
                <fullName>BBAPS</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
            <value>
                <fullName>BBAS0</fullName>
            </value>
            <value>
                <fullName>E2MS2</fullName>
                <label>E2MS 2</label>
            </value>
            <value>
                <fullName>E2MS3</fullName>
            </value>
            <value>
                <fullName>E2MS4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Code_etude_Annee_suivante__c.field-meta.xml
<CustomField>
    <fullName>Code_etude_Annee_suivante__c</fullName>
    <label>Code étude / Année suivante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU2MS</fullName>
            </value>
            <value>
                <fullName>AUBBA</fullName>
            </value>
            <value>
                <fullName>AUBBAC</fullName>
            </value>
            <value>
                <fullName>AUGP</fullName>
            </value>
            <value>
                <fullName>AUMBA</fullName>
            </value>
            <value>
                <fullName>BBA0</fullName>
            </value>
            <value>
                <fullName>BBA1</fullName>
                <isActive>false</isActive>
                <label>BBA1</label>
            </value>
            <value>
                <fullName>BBA2</fullName>
            </value>
            <value>
                <fullName>BBA3</fullName>
            </value>
            <value>
                <fullName>BBA4</fullName>
            </value>
            <value>
                <fullName>BBA5</fullName>
            </value>
            <value>
                <fullName>BBAB1</fullName>
            </value>
            <value>
                <fullName>BBAB2</fullName>
            </value>
            <value>
                <fullName>BBAB3</fullName>
            </value>
            <value>
                <fullName>BBAB4</fullName>
            </value>
            <value>
                <fullName>BBAC1</fullName>
            </value>
            <value>
                <fullName>BBAC2</fullName>
            </value>
            <value>
                <fullName>BBAC3</fullName>
            </value>
            <value>
                <fullName>BBAC4</fullName>
            </value>
            <value>
                <fullName>BBAH1</fullName>
            </value>
            <value>
                <fullName>BBAH2</fullName>
            </value>
            <value>
                <fullName>BBAH3</fullName>
            </value>
            <value>
                <fullName>BBAH4</fullName>
            </value>
            <value>
                <fullName>BBAP0</fullName>
            </value>
            <value>
                <fullName>BBAP1</fullName>
            </value>
            <value>
                <fullName>BBAP2</fullName>
            </value>
            <value>
                <fullName>BBAP3</fullName>
            </value>
            <value>
                <fullName>BBAP4</fullName>
            </value>
            <value>
                <fullName>BBAPS</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
            <value>
                <fullName>E2MS3</fullName>
            </value>
            <value>
                <fullName>E2MS4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Date_Demarrage_Au_Plus_Tot__c.field-meta.xml
<CustomField>
    <fullName>Date_Demarrage_Au_Plus_Tot__c</fullName>
    <description>La date au plus tôt à laquelle l&apos;étudiant a le droit de commencer son stage</description>
    <label>Date De Démarrage Au Plus Tôt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Date_Maximum_Fin_Stage__c.field-meta.xml
<CustomField>
    <fullName>Date_Maximum_Fin_Stage__c</fullName>
    <description>La date maximum à laquelle l&apos;étudiant doit avoir terminé son stage</description>
    <label>Date Maximum de Fin de Stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <description>Le programme d&apos;étude de l&apos;étudiant, dans le cadre duquel il effectue son expérience professionnelle</description>
    <label>Programme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BBAB</fullName>
            </value>
            <value>
                <fullName>BBAC</fullName>
            </value>
            <value>
                <fullName>BBAP</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
            <value>
                <fullName>BBASP</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BOOS</fullName>
            </value>
            <value>
                <fullName>BWGE</fullName>
            </value>
            <value>
                <fullName>CDM</fullName>
            </value>
            <value>
                <fullName>CFT</fullName>
            </value>
            <value>
                <fullName>COSM</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>DBAL</fullName>
            </value>
            <value>
                <fullName>DIBO</fullName>
            </value>
            <value>
                <fullName>DMDS</fullName>
            </value>
            <value>
                <fullName>E2BA</fullName>
            </value>
            <value>
                <fullName>E2MS</fullName>
            </value>
            <value>
                <fullName>EMM</fullName>
            </value>
            <value>
                <fullName>ENVI</fullName>
            </value>
            <value>
                <fullName>ESC</fullName>
            </value>
            <value>
                <fullName>ETD</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GEP</fullName>
            </value>
            <value>
                <fullName>GIE</fullName>
            </value>
            <value>
                <fullName>GLUX</fullName>
            </value>
            <value>
                <fullName>GMST</fullName>
            </value>
            <value>
                <fullName>HEBM</fullName>
            </value>
            <value>
                <fullName>HMDI</fullName>
            </value>
            <value>
                <fullName>IDEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTR010ManageConditionsContractuelles.cls
@isTest
public class TestTR010ManageConditionsContractuelles {
    @isTest 
    static void changeTableTest(){
        Date d1 = Date.newInstance(2021, 01, 01);
        Date d2 = Date.newInstance(2021, 03, 01);
        Date d3 = Date.newInstance(2021, 08, 01);
        Date d4 = Date.newInstance(2021, 10, 01);

        CONVSTA_Table_Regles_Experience_Pro__c table1 = new CONVSTA_Table_Regles_Experience_Pro__c();
        table1.Name =                    'TestAnneeEncours';
        table1.Programme__c =            'E2MS';
        table1.Code_etude__c =           'E2MS2';
        table1.Code_etude_Annee_suivante__c =  'E2MS3';
        table1.Ann_e_suivante__c =       false;
        table1.Annee_application__c  =   '2019';
        table1.Accessible_aux_etudiants__c = true;
        table1.Date_Demarrage_Au_Plus_Tot__c = Date.newInstance(2020, 7, 1);
        table1.Date_Maximum_Fin_Stage__c = Date.newInstance(2021, 7, 1);
        insert table1;

        CONVSTA_Table_Regles_Experience_Pro__c table2 = new CONVSTA_Table_Regles_Experience_Pro__c();
        table2.Name =                    'TestAnneeSuivante';
        table2.Programme__c =            'E2MS';
        table2.Code_etude__c =           'E2MS3';
        table2.Code_etude_Annee_suivante__c =  'E2MS4';
        table2.Ann_e_suivante__c =       true;
        table2.Annee_application__c  =   '2019';
        table2.Accessible_aux_etudiants__c = true;
        table2.Date_Demarrage_Au_Plus_Tot__c = Date.newInstance(2021, 07, 01);
        table2.Date_Maximum_Fin_Stage__c = Date.newInstance(2022, 07, 01);
        insert table2;
        
        Contact etu1 = TestDataFactory.getContact();
        insert etu1;
        Contact etu2 = TestDataFactory.getContact();
        insert etu2;

        Case demande1 = TestObjectFactory.createCase(etu1);
        demande1.Code_Ann_e_Etudiant__c = 'E2MS2';
        demande1.Convsta_Type_de_demande__c = 'Stage';
        insert demande1;
        Convsta_Conditions_Contractuelles__c ccc1 = new Convsta_Conditions_Contractuelles__c();
        ccc1.MD_Demande__c = demande1.Id;
        ccc1.Date_Debut__c = d1;
        ccc1.Date_Fin__c = d2;
        insert ccc1;
        
        Case demande2 = TestObjectFactory.createCase(etu2);
        demande2.Code_Ann_e_Etudiant__c = 'E2MS2';
        demande2.Convsta_Type_de_demande__c = 'Stage';
        insert demande2;
		Convsta_Conditions_Contractuelles__c ccc2 = new Convsta_Conditions_Contractuelles__c();
        ccc2.MD_Demande__c = demande2.Id;
        ccc2.Date_Debut__c = d3;
        ccc2.Date_Fin__c = d4;
        insert ccc2;

        Test.startTest();
        TR010ManageConditionsContractuelles.changeTable(ccc1);
        TR010ManageConditionsContractuelles.changeTable(ccc2);
        Test.stopTest();

        Case dmd1 = [SELECT Id, Convsta_Table_des_Regles_Experience_Pro__c FROM Case WHERE Id =: ccc1.MD_Demande__c LIMIT 1];
        System.assertEquals(table1.Id, dmd1.Convsta_Table_des_Regles_Experience_Pro__c);
		Case dmd2 = [SELECT Id, Convsta_Table_des_Regles_Experience_Pro__c FROM Case WHERE Id =: ccc2.MD_Demande__c LIMIT 1];
        System.assertEquals(table2.Id, dmd2.Convsta_Table_des_Regles_Experience_Pro__c);
    }
}