force-app/main/default/objects/Case/fields/Code_Ann_e_Etudiant__c.field-meta.xml
<CustomField>
    <fullName>Code_Ann_e_Etudiant__c</fullName>
    <description>Permet le changement de tables de règles si changement de dates</description>
    <label>Code Année Etudiant</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/Convsta_Conditions_Contractuelles__c.object-meta.xml
<CustomObject>
    <description>Informations relatives aux conditions contractuelles de l&apos;étudiant en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Conditions Contractuelles</label>
    <nameField>
        <displayFormat>contrat-{000000}</displayFormat>
        <label>Convsta Conditions Contractuelles</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions Contractuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/Date_Debut__c.field-meta.xml
<CustomField>
    <fullName>Date_Debut__c</fullName>
    <description>La date à laquelle commence l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Date à laquelle commence l&apos;expérience professionnelle de l&apos;étudiant</inlineHelpText>
    <label>Date de Début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/Date_Fin__c.field-meta.xml
<CustomField>
    <fullName>Date_Fin__c</fullName>
    <description>La date à laquelle se termine l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Date à laquelle se termine l&apos;expérience professionnelle de l&apos;étudiant</inlineHelpText>
    <label>Date de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Conditions Contractuelles</relationshipLabel>
    <relationshipName>Conditions_Contractuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Accessible_aux_etudiants__c.field-meta.xml
<CustomField>
    <fullName>Accessible_aux_etudiants__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accessible aux étudiants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Ann_e_suivante__c.field-meta.xml
<CustomField>
    <fullName>Ann_e_suivante__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique que la table doit être rattachée aux demandes de l&apos;année en cours pour l&apos;année suivante</description>
    <label>Année suivante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Code_etude__c.field-meta.xml
<CustomField>
    <fullName>Code_etude__c</fullName>
    <label>Code étude / Année actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Programme__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU2MS</fullName>
            </value>
            <value>
                <fullName>AUBBA</fullName>
            </value>
            <value>
                <fullName>AUBBAC</fullName>
            </value>
            <value>
                <fullName>AUGP</fullName>
            </value>
            <value>
                <fullName>AUMBA</fullName>
            </value>
            <value>
                <fullName>BBA0</fullName>
            </value>
            <value>
                <fullName>BBA1</fullName>
            </value>
            <value>
                <fullName>BBA2</fullName>
            </value>
            <value>
                <fullName>BBA3</fullName>
            </value>
            <value>
                <fullName>BBA4</fullName>
            </value>
            <value>
                <fullName>BBAB1</fullName>
            </value>
            <value>
                <fullName>BBAB2</fullName>
            </value>
            <value>
                <fullName>BBAB3</fullName>
            </value>
            <value>
                <fullName>BBAB4</fullName>
            </value>
            <value>
                <fullName>BBAC1</fullName>
            </value>
            <value>
                <fullName>BBAC2</fullName>
            </value>
            <value>
                <fullName>BBAC3</fullName>
            </value>
            <value>
                <fullName>BBAC4</fullName>
            </value>
            <value>
                <fullName>BBAH1</fullName>
            </value>
            <value>
                <fullName>BBAH2</fullName>
            </value>
            <value>
                <fullName>BBAH3</fullName>
            </value>
            <value>
                <fullName>BBAH4</fullName>
            </value>
            <value>
                <fullName>BBAP0</fullName>
            </value>
            <value>
                <fullName>BBAP1</fullName>
            </value>
            <value>
                <fullName>BBAP2</fullName>
            </value>
            <value>
                <fullName>BBAP3</fullName>
            </value>
            <value>
                <fullName>BBAP4</fullName>
            </value>
            <value>
                <fullName>BBAPS</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
            <value>
                <fullName>BBAS0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Code_etude_Annee_suivante__c.field-meta.xml
<CustomField>
    <fullName>Code_etude_Annee_suivante__c</fullName>
    <label>Code étude / Année suivante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU2MS</fullName>
            </value>
            <value>
                <fullName>AUBBA</fullName>
            </value>
            <value>
                <fullName>AUBBAC</fullName>
            </value>
            <value>
                <fullName>AUGP</fullName>
            </value>
            <value>
                <fullName>AUMBA</fullName>
            </value>
            <value>
                <fullName>BBA0</fullName>
            </value>
            <value>
                <fullName>BBA1</fullName>
                <isActive>false</isActive>
                <label>BBA1</label>
            </value>
            <value>
                <fullName>BBA2</fullName>
            </value>
            <value>
                <fullName>BBA3</fullName>
            </value>
            <value>
                <fullName>BBA4</fullName>
            </value>
            <value>
                <fullName>BBA5</fullName>
            </value>
            <value>
                <fullName>BBAB1</fullName>
            </value>
            <value>
                <fullName>BBAB2</fullName>
            </value>
            <value>
                <fullName>BBAB3</fullName>
            </value>
            <value>
                <fullName>BBAB4</fullName>
            </value>
            <value>
                <fullName>BBAC1</fullName>
            </value>
            <value>
                <fullName>BBAC2</fullName>
            </value>
            <value>
                <fullName>BBAC3</fullName>
            </value>
            <value>
                <fullName>BBAC4</fullName>
            </value>
            <value>
                <fullName>BBAH1</fullName>
            </value>
            <value>
                <fullName>BBAH2</fullName>
            </value>
            <value>
                <fullName>BBAH3</fullName>
            </value>
            <value>
                <fullName>BBAH4</fullName>
            </value>
            <value>
                <fullName>BBAP0</fullName>
            </value>
            <value>
                <fullName>BBAP1</fullName>
            </value>
            <value>
                <fullName>BBAP2</fullName>
            </value>
            <value>
                <fullName>BBAP3</fullName>
            </value>
            <value>
                <fullName>BBAP4</fullName>
            </value>
            <value>
                <fullName>BBAPS</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Date_De_Demarrage_Au_Plus_Tard__c.field-meta.xml
<CustomField>
    <fullName>Date_De_Demarrage_Au_Plus_Tard__c</fullName>
    <description>La date butoire à laquelle l&apos;étudiant doit commencer son expérience professionnelle.</description>
    <label>Date De Démarrage Au Plus Tard</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Date_Demarrage_Au_Plus_Tot__c.field-meta.xml
<CustomField>
    <fullName>Date_Demarrage_Au_Plus_Tot__c</fullName>
    <description>La date au plus tôt à laquelle l&apos;étudiant a le droit de commencer son stage</description>
    <label>Date De Démarrage Au Plus Tôt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Date_Maximum_Fin_Stage__c.field-meta.xml
<CustomField>
    <fullName>Date_Maximum_Fin_Stage__c</fullName>
    <description>La date maximum à laquelle l&apos;étudiant doit avoir terminé son stage</description>
    <label>Date Maximum de Fin de Stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TR010ManageConditionsContractuelles.cls
public without sharing class TR010ManageConditionsContractuelles {

        public static void changeTable (Convsta_Conditions_Contractuelles__c ccc){
            Date datedebut = ccc.Date_Debut__c;
            Date datefin = ccc.Date_Fin__c;
            Case demande = [SELECT Id, Convsta_Table_des_Regles_Experience_Pro__c, Code_Ann_e_Etudiant__c, Convsta_Type_de_demande__c FROM Case WHERE Id =: ccc.MD_Demande__c LIMIT 1];
            String codeAnnee = demande.Code_Ann_e_Etudiant__c;

    // Récupération des tdr pour l'année en cours et l'année suivante à partir du code année du contact Etudiant
          try{
            if(demande.Convsta_Type_de_demande__c != 'Validation_experience_anterieure'){
               CONVSTA_Table_Regles_Experience_Pro__c t1 = [
           SELECT
            Id,
            Date_Demarrage_Au_Plus_Tot__c,
            Date_De_Demarrage_Au_Plus_Tard__c,
            Date_Maximum_Fin_Stage__c,
            Code_etude__c,
            Code_etude_Annee_suivante__c
          FROM CONVSTA_Table_Regles_Experience_Pro__c
          WHERE Code_etude__c = :codeAnnee AND Ann_e_suivante__c = false AND Accessible_aux_etudiants__c = true
        ];
    
        // Attribution en fonction de la date de début de Conditions Contractuelles
        List<CONVSTA_Table_Regles_Experience_Pro__c> tableListe = new List<CONVSTA_Table_Regles_Experience_Pro__c>();
         if (t1!=null){
             if(
                ((datedebut >= t1.Date_Demarrage_Au_Plus_Tot__c && t1.Date_De_Demarrage_Au_Plus_Tard__c == null)
            	|| ( t1.Date_De_Demarrage_Au_Plus_Tard__c >= datedebut && datedebut >= t1.Date_Demarrage_Au_Plus_Tot__c))
              	&&((t1.Date_Maximum_Fin_Stage__c == null)||(datefin <= t1.Date_Maximum_Fin_Stage__c))
              	){
             	 tableListe.add(t1);
        	 	 }
              else {
                String codesuivant = t1.Code_etude_Annee_suivante__c;
                if (codesuivant != null) {
        		CONVSTA_Table_Regles_Experience_Pro__c t2 = [
            	SELECT
            	Id,
            	Date_Demarrage_Au_Plus_Tot__c,
            	Date_De_Demarrage_Au_Plus_Tard__c,
                Date_Maximum_Fin_Stage__c,
            	Code_etude__c,
            	Code_etude_Annee_suivante__c
          		FROM CONVSTA_Table_Regles_Experience_Pro__c
          		WHERE Code_etude__c =: codesuivant AND Ann_e_suivante__c = true AND Accessible_aux_etudiants__c = true
        		];
                  if (t2 != null) {
                    if(
                    ((datedebut >= t2.Date_Demarrage_Au_Plus_Tot__c && t2.Date_De_Demarrage_Au_Plus_Tard__c == null)
                		|| ( t2.Date_De_Demarrage_Au_Plus_Tard__c >= datedebut && datedebut >= t2.Date_Demarrage_Au_Plus_Tot__c))
                    &&((t2.Date_Maximum_Fin_Stage__c == null)||(datefin <= t2.Date_Maximum_Fin_Stage__c))
                    ){
                 	 tableListe.add(t2);
                  	 }
                  }
                }
              }
         	}
        
        // Si aucune table de règles ne correspond aux nouvelles dates
        if (tableListe.Size() == 0){
              ccc.addError('Pas de correspondance accessible pour les dates demandées dans les tables de règles, merci de contacter internship@em-lyon.com');
        }else{
          demande.Convsta_Table_des_Regles_Experience_Pro__c = tableListe[0].Id;
          Database.update (demande);
            }
          }
          } catch (QueryException e){
            System.debug( e.getMessage() );
            ccc.addError('Pas de correspondance accessible pour les dates demandées dans les tables de règles, merci de contacter internship@em-lyon.com');
          }
    }
}