force-app/main/default/objects/Case/fields/Convsta_DateEnd__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation liée</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Convsta_Entreprise__c/Convsta_Entreprise__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Entreprise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Convsta Entreprise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entreprises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Entreprise__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entreprises</relationshipLabel>
    <relationshipName>Entreprise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/Convsta_Mission__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à la mission que l&apos;étudiant effectuera en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Convsta Mission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Mission__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Titre_Mission__c.field-meta.xml
<CustomField>
    <fullName>Titre_Mission__c</fullName>
    <description>Le titre de la mission de l&apos;étudiant dans l&apos;entreprise</description>
    <inlineHelpText>Titre de la mission de l&apos;étudiant dans l&apos;entreprise (maximum 70 caractères)</inlineHelpText>
    <label>Titre de la Mission</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Convsta_InternshipTest.cls
@isTest
public class Convsta_InternshipTest {
    @testSetup
    public static void setup(){
        Account entreprise = TestDataFactory.getAccount();
        entreprise.Name = 'Test Name';
        insert entreprise;

        Contact etudiant = TestDataFactory.getContact();
        insert etudiant;

        CONVSTA_Table_Regles_Experience_Pro__c table = TestObjectFactory.createTable();
        insert table;

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.Convsta_DateStart__c = Date.today().addDays(-30);
        demande.Convsta_DateEnd__c = Date.today().addYears(-1);
        demande.Convsta_Entreprise__c = entreprise.Id;
        demande.Convsta_Table_des_Regles_Experience_Pro__c = table.Id;
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c = 'Convention de stage de l ecole';
        insert demande;

        Convsta_Mission__c mission = [SELECT Id FROM Convsta_Mission__c WHERE MD_Demande__c =:demande.Id];
        mission.Titre_Mission__c = 'Researchable';
        update mission;

        Convsta_Mission__c missionNOK = new Convsta_Mission__c();
        missionNOK.Titre_Mission__c = 'Not found';
        missionNOK.MD_Demande__c = demande.Id;
        insert missionNOK;
    }

    @isTest
    public static void shareEvalWithRespPedaTest(){
        User respPedagogique = TestObjectFactory.createUser('RespPedago','Responsable Pédagogique');
        insert respPedagogique;
        Convsta_Evaluation__c evaluation = TestObjectFactory.createEvaluation();
        evaluation.Responsable_Pedagogique__c = respPedagogique.Id;
        insert evaluation;    
                    
        Test.startTest();
        Convsta_Evaluation__Share evalShare = Convsta_Internship.shareEvalWithRespPeda(evaluation);
        insert evalShare;
        Test.stopTest();
    
        List<Convsta_Evaluation__Share> jShrs = [
            SELECT Id, UserOrGroupId, AccessLevel, RowCause 
            FROM Convsta_Evaluation__Share 
            WHERE ParentId =:evaluation.Id 
            AND UserOrGroupId =:respPedagogique.Id];

        System.assertEquals(jShrs.size(), 1);
        System.assertEquals(jShrs[0].AccessLevel, 'Read');
        System.assertEquals(jShrs[0].RowCause, 'Manual');
    }

    @isTest
    public static void testSearchOK(){
        Convsta_Internship.SearchInput input = new Convsta_Internship.SearchInput();
        input.country = 'France';
        input.city = 'TestVille';
        input.programme = 'E2MS';
        input.companyName = 'Test Name';
        input.title = 'Researchable';

        Test.startTest();
        Convsta_Internship.SearchReturn resReturn = Convsta_Internship.search(input);
        Test.stopTest();
        system.debug(resReturn);
        System.assertEquals(1, resReturn.lOutputs.size(), resReturn);
    }

    @isTest
    public static void testSearchNoCondition(){
        Convsta_Internship.SearchInput input = new Convsta_Internship.SearchInput();

        Test.startTest();
        Convsta_Internship.SearchReturn resReturn = Convsta_Internship.search(input);
        Test.stopTest();

        System.assertEquals( 'NOK : No condition entered', resReturn.state );
    }

    @isTest
    public static void testSearchNoResult(){
        Convsta_Internship.SearchInput input = new Convsta_Internship.SearchInput();
        input.country = 'NOK';
        input.city = 'NOK';
        input.programme = 'NOK';
        input.naf = 'NOK';
        input.companyName = 'NOK';
        input.title = 'NOK';

        Test.startTest();
        Convsta_Internship.SearchReturn resReturn = Convsta_Internship.search(input);
        Test.stopTest();

        System.assertEquals(null, resReturn.lOutputs);
    }
}