force-app/main/default/objects/Case/fields/Convsta_ConventionDocumentId__c.field-meta.xml
<CustomField>
    <fullName>Convsta_ConventionDocumentId__c</fullName>
    <label>Convention Document Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Convsta_Validation_d_experience.recordType-meta.xml
<RecordType>
    <fullName>Convsta_Validation_d_experience</fullName>
    <active>true</active>
    <businessProcess>Convsta_Validation_Expérience</businessProcess>
    <label>Validation d&apos;expérience</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/classes/Convsta_AttachConventionFromEmailTest.cls
@isTest 
public class Convsta_AttachConventionFromEmailTest {
    @testSetup
    static void setup(){        
        Contact etudiant =      TestDataFactory.getContact();
        etudiant.FirstName =    'Etudiant';
        etudiant.LastName =     'EM';
        etudiant.Email =        'testEtudiant@test.com';
        insert etudiant;
    }

    @isTest 
    static void success() {
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId    = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;

        demande =  [SELECT Id, CaseNumber
                    FROM Case
                    LIMIT 1];

        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();

        email.subject = 'Test Subject';
        email.fromName = 'Test Name';
        email.plainTextBody = 'Hello, this a test email body.';
        Messaging.InboundEmail.BinaryAttachment[] binaryAttachments = new Messaging.InboundEmail.BinaryAttachment[1];  
        Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
        String fileName = 'convention-' + demande.CaseNumber + '.pdf';
        binaryAttachment.Filename = fileName;
        String algorithmName = 'HMacSHA1';
        Blob b = Crypto.generateMac(algorithmName, Blob.valueOf('Test'), Blob.valueOf('test_key'));
        binaryAttachment.Body = b;
        binaryAttachments[0] =  binaryAttachment ;
        email.binaryAttachments = binaryAttachments ;
        envelope.fromAddress = 'test@email.com';    


        Test.startTest();
        Convsta_AttachConventionFromEmail catcher = new Convsta_AttachConventionFromEmail();
        Messaging.InboundEmailResult result = catcher.handleInboundEmail(email, envelope);
        Test.stopTest();

        List<ContentDocumentLink> lFile = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :demande.Id];
        demande = [SELECT Convsta_ConventionDocumentId__c  FROM Case WHERE Id =:demande.Id];

        System.assertNotEquals(0, lFile.size());
        System.assertEquals(lFile[0].ContentDocumentId, demande.Convsta_ConventionDocumentId__c);
    }

    @isTest 
    static void caseNotFound() {
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();

        email.subject = 'Test Subject';
        email.fromName = 'Test Name';
        email.plainTextBody = 'Hello, this a test email body.';
        Messaging.InboundEmail.BinaryAttachment[] binaryAttachments = new Messaging.InboundEmail.BinaryAttachment[1];  
        Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
        String fileName = 'convention' + 'XXXXXXX' + '.pdf';
        binaryAttachment.Filename = fileName;
        String algorithmName = 'HMacSHA1';
        Blob b = Crypto.generateMac(algorithmName, Blob.valueOf('Test'), Blob.valueOf('test_key'));
        binaryAttachment.Body = b;
        binaryAttachments[0] =  binaryAttachment ;
        email.binaryAttachments = binaryAttachments ;
        envelope.fromAddress = 'test@email.com';    


        Test.startTest();
        Convsta_AttachConventionFromEmail catcher = new Convsta_AttachConventionFromEmail();
        Messaging.InboundEmailResult result = catcher.handleInboundEmail(email, envelope);
        Test.stopTest();

        //Nothing to test
    }
}