force-app/main/default/objects/Case/fields/Convsta_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation liée</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Langue__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Langue__c</fullName>
    <label>Langue de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Français</fullName>
            </value>
            <value>
                <fullName>Anglais</fullName>
            </value>
            <value>
                <fullName>Espagnol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Competences__mdt/Convsta_Competences__mdt.object-meta.xml
<CustomObject>
    <description>Regroupe les compétences 
EarlyMaker
Comportementales
Métiers</description>
    <label>Convsta_Competences</label>
    <pluralLabel>Convsta_Competences</pluralLabel>
</CustomObject>

force-app/main/default/objects/Convsta_Competences__mdt/fields/Famille_metier__c.field-meta.xml
<CustomField>
    <fullName>Famille_metier__c</fullName>
    <label>Famille métier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Competences__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name_Fr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Competences__mdt/fields/Name_En__c.field-meta.xml
<CustomField>
    <fullName>Name_En__c</fullName>
    <label>Name_En</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Famille_competences_metier__c.field-meta.xml
<CustomField>
    <fullName>Famille_competences_metier__c</fullName>
    <label>Famille compétences métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance d&apos;entreprise, comptabilité, contrôle de gestion</fullName>
            </value>
            <value>
                <fullName>Ressources Humaines</fullName>
            </value>
            <value>
                <fullName>Direction Générale</fullName>
            </value>
            <value>
                <fullName>Financement, Investissements et Assurances</fullName>
            </value>
            <value>
                <fullName>Marketing et Communication</fullName>
            </value>
            <value>
                <fullName>Production et QHSE</fullName>
            </value>
            <value>
                <fullName>Audit et Conseil</fullName>
            </value>
            <value>
                <fullName>Développement commercial et relations clients</fullName>
            </value>
            <value>
                <fullName>Digital et data</fullName>
            </value>
            <value>
                <fullName>Achats</fullName>
            </value>
            <value>
                <fullName>Informatique</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management</fullName>
            </value>
            <value>
                <fullName>Juridique</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/Convsta_Mission__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à la mission que l&apos;étudiant effectuera en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Convsta Mission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Mission__c/fields/Competences_categorie_2__c.field-meta.xml
<CustomField>
    <fullName>Competences_categorie_2__c</fullName>
    <label>Compétences comportementales</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Démontrer un comportement assertif</fullName>
            </value>
            <value>
                <fullName>Gérer son stress</fullName>
            </value>
            <value>
                <fullName>Élaborer un diagnostic</fullName>
            </value>
            <value>
                <fullName>Conceptualiser, et modéliser les situations complexes</fullName>
            </value>
            <value>
                <fullName>Mobiliser différentes sources pour accéder à l&apos;information</fullName>
            </value>
            <value>
                <fullName>Qualifier l&apos;information et identifier l&apos;information pertinente</fullName>
            </value>
            <value>
                <fullName>Organiser son travail avec précision et rigueur</fullName>
            </value>
            <value>
                <fullName>Gérer son temps et les priorités</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Conceptualiser_et_modeliser__c.field-meta.xml
<CustomField>
    <fullName>Conceptualiser_et_modeliser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Conceptualiser, et modéliser les situations complexes</inlineHelpText>
    <label>Conceptualiser et modéliser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Demontrer_un_comportement_assertif__c.field-meta.xml
<CustomField>
    <fullName>Demontrer_un_comportement_assertif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Démontrer un comportement assertif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Elaborer_un_diagnostic__c.field-meta.xml
<CustomField>
    <fullName>Elaborer_un_diagnostic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Élaborer un diagnostic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Gerer_son_stress__c.field-meta.xml
<CustomField>
    <fullName>Gerer_son_stress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gérer son stress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Gerer_son_temps_et_les_priorites__c.field-meta.xml
<CustomField>
    <fullName>Gerer_son_temps_et_les_priorites__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gérer son temps et les priorités</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Mobiliser_differentes_sources__c.field-meta.xml
<CustomField>
    <fullName>Mobiliser_differentes_sources__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mobiliser différentes sources pour accéder à l&apos;information.</inlineHelpText>
    <label>Mobiliser différentes sources</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Precision_et_rigueur_au_travail__c.field-meta.xml
<CustomField>
    <fullName>Precision_et_rigueur_au_travail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Organiser son travail avec précision et rigueur.</inlineHelpText>
    <label>Précision et rigueur au travail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Qualifier_et_identifier_l_information__c.field-meta.xml
<CustomField>
    <fullName>Qualifier_et_identifier_l_information__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Qualifier l&apos;information et identifier l&apos;information pertinente</inlineHelpText>
    <label>Qualifier et identifier l&apos;information</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Convsta_GenererDemandeDEvaluation_CX.cls
public with sharing class Convsta_GenererDemandeDEvaluation_CX {
    private final Convsta_Evaluation__c eval;
    public Boolean isPreviewMode {get;set;}
    
    // Constructor used to get the Evaluation record
    public Convsta_GenererDemandeDEvaluation_CX(ApexPages.StandardController stdController) {
        this.eval = (Convsta_Evaluation__c) stdController.getRecord();
    }

    public Case demande {
        get {
            return [SELECT Id,
                    Convsta_Langue__c
                     FROM Case
                     WHERE Case.Convsta_Evaluation__c = :eval.Id
                     LIMIT 1];
        }
        set;
    }
    public Convsta_Mission__c mission {
        get {
            return [SELECT Id,
                    Precision_et_rigueur_au_travail__c,
                    Conceptualiser_et_modeliser__c,
                    Qualifier_et_identifier_l_information__c,
                    Demontrer_un_comportement_assertif__c,
                    Elaborer_un_diagnostic__c,
                    Gerer_son_temps_et_les_priorites__c,
                    Mobiliser_differentes_sources__c,
                    Gerer_son_stress__c,
                    Competences_categorie_2__c
                     FROM Convsta_Mission__c
                     WHERE Convsta_Mission__c.MD_Demande__c = :demande.Id];
        }
        set;
    }
    
    //public string getOutputClass (){
       // return isPreviewMode ?'font-weight:bold;background-color: #ffff00;':'font-weight:bold;background-color: transparent;';
  //  }
    
     public List<Convsta_Competences__mdt> lCompEarlyMaker {
        get {
            return [SELECT  Name__c,
                    Name_En__c,
                    Type__c,
                    Famille_metier__c,
                    Order__c
                    FROM    Convsta_Competences__mdt
                    WHERE   Type__c = '1EarlyMaker'
                    ORDER BY Order__c
                    ];
        }
        set;
    }
    
   public List<Convsta_Competences__mdt> lCompComportem {
        get { 
                List<Convsta_Competences__mdt> listComp = [SELECT  Id,
                        Name__c,
                        Name_En__c,
                        Type__c,
                        Famille_metier__c,
                        Order__c
                        FROM    Convsta_Competences__mdt
                        WHERE   Type__c = '2Comportement'
                        ORDER BY Order__c
                    ];

                Map<Convsta_Competences__mdt, Boolean> compCochees = new Map<Convsta_Competences__mdt, Boolean>();
                    compCochees.put(listComp.get(0), mission.Conceptualiser_et_modeliser__c);
                    compCochees.put(listComp.get(1), mission.Demontrer_un_comportement_assertif__c);
                    compCochees.put(listComp.get(2), mission.Elaborer_un_diagnostic__c);
                    compCochees.put(listComp.get(3), mission.Precision_et_rigueur_au_travail__c);
                    compCochees.put(listComp.get(4), mission.Gerer_son_stress__c);
                    compCochees.put(listComp.get(5), mission.Gerer_son_temps_et_les_priorites__c);
                    compCochees.put(listComp.get(6), mission.Mobiliser_differentes_sources__c);
                    compCochees.put(listComp.get(7), mission.Qualifier_et_identifier_l_information__c);
            		System.debug(compCochees.size());

                List<Convsta_Competences__mdt> listChecked = new List<Convsta_Competences__mdt>();

                for (Convsta_Competences__mdt competence : compCochees.keySet()) {
                    System.debug(competence);
                    Boolean coche = compCochees.get(competence);
                    if (coche == TRUE) {
                        listChecked.add(competence);
                    }
                }
                return listChecked;
        }
        set;
    }
    
      public List<Convsta_Competences__mdt> lCompMetier {
        get {
            return [SELECT  Name__c,
                    Name_En__c,
                    Type__c,
                    Famille_metier__c,
                    Order__c
                    FROM  Convsta_Competences__mdt
                    WHERE Type__c = '3Métier'
                    AND  Famille_metier__c =:eval.Famille_competences_metier__c
                    ORDER BY Order__c
                    ];
        }
        set;
    }  
}