force-app/main/default/objects/Case/fields/Convsta_Date_assignation_au_gestionnaire__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_assignation_au_gestionnaire__c</fullName>
    <label>Assignation au gestionnaire</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Soumission_Demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Soumission_Demande__c</fullName>
    <inlineHelpText>La date à laquelle l&apos;étudiant a soumis sa demande d&apos;expérience de stage.</inlineHelpText>
    <label>Dernière Soumission de la Demande</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Validation_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Validation_Pedagogique__c</fullName>
    <label>Validation Pédagogique</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Gestionnaire_en_charge__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Gestionnaire_en_charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestionnaire en charge</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gestionnaire_de</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convsta_Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Role_EMLYON__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Role_EMLYON__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suiveur GBBA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>R_le__c.isStageOrSuiveur__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>R_le__c.convsta_suiveur__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>R_le__c</referenceTo>
    <relationshipLabel>suiveur stage</relationshipLabel>
    <relationshipName>SuiveurRequetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Statut_Signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Statut_Signature__c</fullName>
    <label>Statut de la signature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Envoyé</fullName>
            </value>
            <value>
                <fullName>Signée</fullName>
            </value>
            <value>
                <fullName>Convention validée à émettre</fullName>
            </value>
            <value>
                <fullName>Avenant validé à émettre</fullName>
            </value>
            <value>
                <fullName>Erreur génération</fullName>
            </value>
            <value>
                <fullName>Expirée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Traité manuellement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_suiveur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_suiveur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Suiveur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes (Suiveur)</relationshipLabel>
    <relationshipName>suiveur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Validation_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Validation_Pedagogique__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Le Responsable Pédagogique doit cocher cette case lorsque la validation pédagogique est ok</inlineHelpText>
    <label>Validation Pédagogique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Verdict_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Verdict_Pedagogique__c</fullName>
    <label>Verdict Pédagogique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Acceptée</fullName>
            </value>
            <value>
                <fullName>Demande Rejetée</fullName>
            </value>
            <value>
                <fullName>Précisions Nécessaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Convsta_Validation_d_experience.recordType-meta.xml
<RecordType>
    <fullName>Convsta_Validation_d_experience</fullName>
    <active>true</active>
    <businessProcess>Convsta_Validation_Expérience</businessProcess>
    <label>Validation d&apos;expérience</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Liste_r_le__c.field-meta.xml
<CustomField>
    <fullName>Liste_r_le__c</fullName>
    <label>Liste rôle</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Cat_gorie_r_le__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Membre de l&apos;AG AESCRA</fullName>
            </value>
            <value>
                <fullName>Membre  du CA de l&apos;AESCRA</fullName>
            </value>
            <value>
                <fullName>membre conseil d&apos;administration Alliance</fullName>
            </value>
            <value>
                <fullName>Membre Comex Fondation</fullName>
            </value>
            <value>
                <fullName>Réseaux d&apos;accompagement créateurs d&apos;Eses</fullName>
            </value>
            <value>
                <fullName>Membre Conseil Surveillance CDME</fullName>
            </value>
            <value>
                <fullName>Membre Associés CCI</fullName>
            </value>
            <value>
                <fullName>Membre Bureau Elus CCI</fullName>
            </value>
            <value>
                <fullName>Membre Elus CCI</fullName>
            </value>
            <value>
                <fullName>Membre Commision Enseignement CCI</fullName>
            </value>
            <value>
                <fullName>Membre PRES</fullName>
            </value>
            <value>
                <fullName>Membres CA ADEM LYON</fullName>
            </value>
            <value>
                <fullName>Dirigeant du CAC 40</fullName>
            </value>
            <value>
                <fullName>Dirigeant créateur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/R_le__c.field-meta.xml
<CustomField>
    <fullName>R_le__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Association étudiant</fullName>
            </value>
            <value>
                <fullName>Délégué de promo</fullName>
            </value>
            <value>
                <fullName>Correspondant</fullName>
            </value>
            <value>
                <fullName>Président club</fullName>
            </value>
            <value>
                <fullName>Administrateur ADEM</fullName>
            </value>
            <value>
                <fullName>Intervenant témoin</fullName>
            </value>
            <value>
                <fullName>Prestataire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Nom_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Nom_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>L&apos;identité du responsable pédagogique s&apos;occupant de l&apos;étudiant</description>
    <label>Nom du Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/R_le__c/R_le__c.object-meta.xml
<CustomObject>
    <label>Rôle EMLYON</label>
    <nameField>
        <label>Nom du contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rôles EMLYON</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_le__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R_les</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_le__c/fields/convsta_suiveur__c.field-meta.xml
<CustomField>
    <fullName>convsta_suiveur__c</fullName>
    <defaultValue>false</defaultValue>
    <label>convsta_suiveur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_le__c/fields/Liste_r_le__c.field-meta.xml
<CustomField>
    <fullName>Liste_r_le__c</fullName>
    <label>Liste rôle</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Categorie_role__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1kubator Lyon</fullName>
            </value>
            <value>
                <fullName>50 partners</fullName>
            </value>
            <value>
                <fullName>AD’OCC</fullName>
            </value>
            <value>
                <fullName>Agoranov</fullName>
            </value>
            <value>
                <fullName>Alter’Incub</fullName>
            </value>
            <value>
                <fullName>Ancien BOURSIER EMLYON</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Astuce Lycéens</fullName>
            </value>
            <value>
                <fullName>Ancien Membre BDA</fullName>
            </value>
            <value>
                <fullName>Ancien Membre BDE</fullName>
            </value>
            <value>
                <fullName>Ancien Membre BDS</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Beaux Cuis&apos;</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Club Voile</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Corpo</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Déclic</fullName>
            </value>
            <value>
                <fullName>Ancien Membre EM&apos;icrocrédit</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Forum</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Goût&apos;R&apos;Mets</fullName>
            </value>
            <value>
                <fullName>Ancien Membre I LINK</fullName>
            </value>
            <value>
                <fullName>Ancien Membre JET</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Junior Conseil</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Ligne 2 Mire</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Numérik</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Opening</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Petit Paumé</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Planet &amp; Co</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Radio Activ</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Raid Hannibal</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Ski Club</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Solidari&apos;Terre</fullName>
            </value>
            <value>
                <fullName>Ancien Membre Sup de Côteaux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTR008ManageCase.cls
@isTest
public class TestTR008ManageCase {
    @testSetup
    static void setup(){
        CONVSTA_Table_Regles_Experience_Pro__c test = TestDataFactory.getTableReglesExperiencePro();
        insert test;
    }

    @isTest 
    static void isValidationPedagoAdmin(){
        Case demande = TestDataFactory.getCaseWithSigners();
        Contact ctc = [select id from contact limit 1];
        R_le__c role = new R_le__c(contact__c=ctc.id, Liste_r_le__c = 'SUIVEUR OU MAITRE DE STAGE');
        insert role;
        R_le__c role2 = new R_le__c(contact__c=ctc.id);
        insert role2;
        System.assertNotEquals(0, [select id from R_le__c where convsta_suiveur__c =true].size());
        demande.Convsta_Role_EMLYON__c = role.id;
        demande.Convsta_Verdict_Pedagogique__c = 'Demande Acceptée';
        demande.RecordTypeId =  APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');

        Test.startTest();
        insert demande;
        Test.stopTest();

        demande = [SELECT Convsta_Date_Validation_Pedagogique__c, Convsta_Date_assignation_au_gestionnaire__c,
                          Convsta_Validation_Pedagogique__c, OwnerId, Status
                   FROM Case];

        Group queue =  [SELECT Id
                       FROM Group WHERE 
                       DeveloperName = 'Convsta_En_attente_de_validation_admin'];

        System.assertNotEquals(null, demande.Convsta_Date_Validation_Pedagogique__c);
        System.assertNotEquals(null, demande.Convsta_Date_assignation_au_gestionnaire__c);

        System.assertEquals(true, demande.Convsta_Validation_Pedagogique__c);

        System.assertEquals(queue.Id, demande.OwnerId);
        System.assertEquals('Demande en cours de validation administrative', demande.Status);
    }

    @isTest 
    static void isDemandeSoumiseSansRP(){
        Case demande = TestDataFactory.getCaseWithSigners();
        demande.Status = 'Demande soumise';
        demande.Convsta_Table_des_Regles_Experience_Pro__c = [SELECT Id, Nom_Responsable_Pedagogique__c FROM CONVSTA_Table_Regles_Experience_Pro__c].Id;
        demande.RecordTypeId =  APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        
        Test.startTest();
        insert demande;
        Test.stopTest();

        demande = [SELECT Convsta_Date_Soumission_Demande__c,
                          OwnerId, Status
                   FROM Case];

        Group queue = [SELECT Id
                       FROM Group WHERE 
                       DeveloperName = 'Convsta_En_attente_de_validation_admin'];

        System.assertNotEquals(null, demande.Convsta_Date_Soumission_Demande__c);

        System.assertEquals(queue.Id, demande.OwnerId);
        System.assertEquals('Demande en cours de validation pédagogique', demande.Status);
    }
    
    @isTest 
    static void isDemandeSansRespAdminAvecRespPeda(){      
        CONVSTA_Table_Regles_Experience_Pro__c table = [SELECT Id, Nom_Responsable_Pedagogique__c FROM CONVSTA_Table_Regles_Experience_Pro__c];
        table.Nom_Responsable_Pedagogique__c = [select id from user where isActive=true and userType='Standard' limit 1].id;
        update table;
        
        Case demande = TestDataFactory.getCaseWithSigners();  
        demande.Convsta_Table_des_Regles_Experience_Pro__c = table.id;
        demande.Status = 'Demande soumise';
        demande.Convsta_Gestionnaire_en_charge__c = null;
        demande.Convsta_Validation_Pedagogique__c = true;
        demande.RecordTypeId =  APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        
        Test.startTest();
        insert demande;
        Test.stopTest();

        demande = [SELECT Convsta_Date_Soumission_Demande__c, Convsta_Date_assignation_au_gestionnaire__c,
                          OwnerId, Status
                   FROM Case];

        Group queue = [SELECT Id
                       FROM Group WHERE 
                       DeveloperName = 'Convsta_En_attente_de_validation_admin'];

        System.assertEquals('Demande en cours de validation pédagogique', demande.Status);
        System.assertNotEquals(null, demande.Convsta_Date_Soumission_Demande__c);

        System.assertEquals(queue.Id, demande.OwnerId);
    }
    
    @isTest 
    static void isDemandeSansRespAdminSansRespPeda(){
        CONVSTA_Table_Regles_Experience_Pro__c table = [SELECT Id, Nom_Responsable_Pedagogique__c FROM CONVSTA_Table_Regles_Experience_Pro__c];
        table.Nom_Responsable_Pedagogique__c = null;
        update table;
        
        Case demande = TestDataFactory.getCaseWithSigners();
        demande.Convsta_Table_des_Regles_Experience_Pro__c = table.id;
        demande.Status = 'Demande soumise';
        demande.Convsta_Gestionnaire_en_charge__c = null;
        demande.Convsta_Validation_Pedagogique__c = true;
        demande.RecordTypeId =  APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        
        Test.startTest();
        insert demande;
        Test.stopTest();

        demande = [SELECT Convsta_Date_Soumission_Demande__c, Convsta_Date_assignation_au_gestionnaire__c,
                          OwnerId, Status
                   FROM Case];

        Group queue = [SELECT Id
                       FROM Group WHERE 
                       DeveloperName = 'Convsta_En_attente_de_validation_admin'];

        System.assertEquals('Demande en cours de validation pédagogique', demande.Status);
        System.assertNotEquals(null, demande.Convsta_Date_Soumission_Demande__c);

        System.assertEquals(queue.Id, demande.OwnerId);
    }

    @isTest 
    static void isDemandeAvecRespAdminSansRespPeda(){
        CONVSTA_Table_Regles_Experience_Pro__c table = [SELECT Id, Nom_Responsable_Pedagogique__c FROM CONVSTA_Table_Regles_Experience_Pro__c];
        table.Nom_Responsable_Pedagogique__c = null;
        update table;
        
        Case demande = TestDataFactory.getCaseWithSigners();
        demande.Convsta_Table_des_Regles_Experience_Pro__c = table.id;
        demande.Status = 'Demande soumise';
        demande.Convsta_Gestionnaire_en_charge__c = UserInfo.getUserId();
        demande.Convsta_Validation_Pedagogique__c = true;
        demande.RecordTypeId =  APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        
        Test.startTest();
        insert demande;
        Test.stopTest();

        demande = [SELECT Convsta_Date_Soumission_Demande__c, Convsta_Date_assignation_au_gestionnaire__c,
                          OwnerId, Status
                   FROM Case];

        System.assertEquals('Demande en cours de validation administrative', demande.Status);
        System.assertNotEquals(null, demande.Convsta_Date_Soumission_Demande__c);

        System.assertEquals(UserInfo.getUserId(), demande.OwnerId);
    }
    
    @isTest
    static void testConvention() {
        Case demande = TestDataFactory.getCaseWithSigners();
        insert demande;

        Test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('convsta_postEsignCreatenewSign');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');

        Test.setMock(HttpCalloutMock.class, mock);
        demande.Convsta_Statut_Signature__c = 'Convention validée à émettre';
        update demande;
        Test.stopTest();

        demande = [SELECT Convsta_Statut_Signature__c FROM Case WHERE Id = :demande.Id];

        System.assertEquals('Convention en attente de signature', demande.Convsta_Statut_Signature__c);
    }

    @isTest static void testAvenant() {
        Case demande = TestDataFactory.getCaseWithSigners();
        insert demande;
        Case avenant = TestDataFactory.getCaseWithSigners();
        avenant.ParentId = demande.Id;
        insert avenant;

        Test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('convsta_postEsignCreateNewSign');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');

        Test.setMock(HttpCalloutMock.class, mock);
        avenant.Status = 'Avenant validé à émettre';
        avenant.Convsta_Statut_Signature__c = 'Avenant validé à émettre';
        update avenant;
        Test.stopTest();

        avenant = [SELECT Convsta_Statut_Signature__c FROM Case WHERE Id = :avenant.Id];

        System.assertEquals('Avenant en cours de signature', avenant.Convsta_Statut_Signature__c);
    }

    @isTest static void testCaseSharingUpdateRP() {
        Case demande = TestDataFactory.getCaseWithSigners();
        demande.Convsta_Validation_Pedagogique__c = true;
        insert demande;

        Profile p = [SELECT Id FROM Profile WHERE name LIKE '%Responsable%Pédagogique%'] ;

        User oldRP = [SELECT Id FROM User WHERE id !=: demande.OwnerId AND isActive = true AND ProfileId =: p.Id LIMIT 1] ;
        User newRP = [SELECT Id FROM User WHERE id !=: oldRP.Id AND id !=: demande.OwnerId AND isActive = true AND ProfileId =: p.Id LIMIT 1] ;

        Test.startTest();
        demande.Convsta_Responsable_Pedagogique__c = oldRP.Id ;
        update demande;
        demande.Convsta_Responsable_Pedagogique__c = newRP.Id ;
        update demande;
        Test.stopTest();

        String resAccess = '' ;
        String resUserId = '' ;

        for(CaseShare cs : [SELECT Id, CaseId, UserOrGroupId, CaseAccessLevel FROM CaseShare WHERE CaseID =: demande.Id]){
			if(cs.UserOrGroupId == newRP.Id){
				resAccess = cs.CaseAccessLevel ;
			}
            if(cs.CaseAccessLevel == 'Read'){
				resUserId = cs.UserOrGroupId ;
			}
		}

        System.assertEquals('Read', resAccess);
        System.assertEquals(newRP.Id, resUserId);
    }
}