force-app/main/default/objects/Case/fields/Convsta_DateEnd__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation liée</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/convsta_ignore_eval__c.field-meta.xml
<CustomField>
    <fullName>convsta_ignore_eval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>convsta_ignore_eval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Referent_pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Referent_pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tuteur emlyon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Le contact doit être désigné comme Tuteur EM.</errorMessage>
        <filterItems>
            <field>Contact.Convsta_Tuteur_EM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status</field>
            <operation>equals</operation>
            <value>En cours de signature, Signée, En cours d&apos;évaluation, Validée, Evaluée</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Référent pédagogique)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convsta_Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Tuteur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Tuteur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tuteur entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/A_evaluer__c.field-meta.xml
<CustomField>
    <fullName>A_evaluer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique si le stage doit être évalué</description>
    <inlineHelpText>Indique si le stage doit être évalué</inlineHelpText>
    <label>A évaluer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/convsta_BatchSchedule_CreateEval.cls
/*--------------------------------------------------------------------
-- - Purpose            : Ce batch sert à créer les évaluations des demandes concernées.
--                        Il se lance tous les jours de la semaine à 18h : 0 0 18 ? * MON-FRI * 
--
-- - Maintenance History:
--
-- Date        Name  Company  Version  Remarks
-- ----------  ----  -------  -------  -------------------------------
-- 00/00/20XX  T.CH  MODIS    1.0      Initial version
--------------------------------------------------------------------*/
global class convsta_BatchSchedule_CreateEval implements Schedulable, Database.Batchable<sObject>{ 
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date limitDate = date.valueOf(Label.convsta_eval_generationLimit);
        return Database.getQueryLocator([
            SELECT Id, 
            Contact.Id, 
            Contact.Name, 
            Casenumber,
            Convsta_Referent_pedagogique__c, 
            Convsta_DateEnd__c,
            Convsta_Responsable_Pedagogique__c,
            Convsta_Tuteur__c
            FROM Case
            WHERE (Convsta_TypeContrat__c IN (
                'Convention de stage de l ecole',
                'Convention de stage de l\'entreprise') 
                OR (
                Convsta_TypeContrat__c IN ('Contrat de travail de l\'entreprise',
                    'VIE',
                    'Service_civique')
                AND Convsta_DateStart__c > :limitDate)) 
            AND Convsta_DateEnd__c <= NEXT_N_DAYS:28
            AND Convsta_Evaluation__c = null
            AND Convsta_Table_des_Regles_Experience_Pro__R.A_evaluer__c = true
        	AND convsta_ignore_eval__c =false
        	AND status='Convention signée']);
    }
    
    global void execute(Database.BatchableContext info, List<Case> scope){
        system.debug(scope);
        Convsta_Internship.createEval(scope);
    }  
    
    global void finish(Database.BatchableContext info){
    }
    
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new convsta_BatchSchedule_CreateEval(),1);
    } 
}