force-app/main/default/objects/Case/fields/Convsta_Date_assignation_au_gestionnaire__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_assignation_au_gestionnaire__c</fullName>
    <label>Assignation au gestionnaire</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Soumission_Demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Soumission_Demande__c</fullName>
    <inlineHelpText>La date à laquelle l&apos;étudiant a soumis sa demande d&apos;expérience de stage.</inlineHelpText>
    <label>Dernière Soumission de la Demande</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Validation_Administrative__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Validation_Administrative__c</fullName>
    <label>Validation Administrative</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Validation_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Validation_Pedagogique__c</fullName>
    <label>Validation Pédagogique</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Gestionnaire_en_charge__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Gestionnaire_en_charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestionnaire en charge</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gestionnaire_de</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convsta_Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Role_EMLYON__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Role_EMLYON__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suiveur GBBA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>R_le__c.isStageOrSuiveur__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>R_le__c.convsta_suiveur__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>R_le__c</referenceTo>
    <relationshipLabel>suiveur stage</relationshipLabel>
    <relationshipName>SuiveurRequetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_suiveur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_suiveur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Suiveur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes (Suiveur)</relationshipLabel>
    <relationshipName>suiveur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Validation_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Validation_Pedagogique__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Le Responsable Pédagogique doit cocher cette case lorsque la validation pédagogique est ok</inlineHelpText>
    <label>Validation Pédagogique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Verdict_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Verdict_Pedagogique__c</fullName>
    <label>Verdict Pédagogique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Acceptée</fullName>
            </value>
            <value>
                <fullName>Demande Rejetée</fullName>
            </value>
            <value>
                <fullName>Précisions Nécessaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Nom_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Nom_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>L&apos;identité du responsable pédagogique s&apos;occupant de l&apos;étudiant</description>
    <label>Nom du Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/R_le__c/R_le__c.object-meta.xml
<CustomObject>
    <label>Rôle EMLYON</label>
    <nameField>
        <label>Nom du contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rôles EMLYON</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_le__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R_les</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_le__c/fields/convsta_suiveur__c.field-meta.xml
<CustomField>
    <fullName>convsta_suiveur__c</fullName>
    <defaultValue>false</defaultValue>
    <label>convsta_suiveur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TR008ManageCase.cls
/*---------------------------------------------------------------------
-- - Purpose             : Implementation of methods called by triggers on cases
--
-- - Maintenance History :
--
-- Date        Name  Company  Version  Remarks
-- ----------  ----  -------  -------  --------------------------------
-- 01/02/2019  T.CH  MODIS    1.0      Initial version
---------------------------------------------------------------------*/
public without sharing class TR008ManageCase {
	private static set<Id> roleEmIdSet = new set<Id>();
	private static Datetime now = Datetime.now();
	private static Group queue = null;
	private static Group getQueue(){
		if(queue == null){
			queue = [SELECT Id
				FROM Group WHERE 
				DeveloperName = 'Convsta_En_attente_de_validation_admin'];
		}
		return queue;
	}
	private static Map<Id, String> mpRespNameById = new Map<Id, String>();

	public static void affectOwner(List<Case> lCases){

        // Map<Id, String> mpRespNameById = new Map<Id, String>([SELECT Id, Convsta_Table_des_Regles_Experience_Pro__r.Nom_Responsable_Pedagogique__c FROM Case WHERE Id IN :lCases]);
        List<Case> lRespName = [SELECT Id, Convsta_Table_des_Regles_Experience_Pro__r.Nom_Responsable_Pedagogique__c FROM Case WHERE Id IN :lCases];
        for(Case demande :lRespName){
            mpRespNameById.put(demande.Id, demande.Convsta_Table_des_Regles_Experience_Pro__r.Nom_Responsable_Pedagogique__c);
        }
		for(Case demande :lCases){
			//on vérifie que la validation administrative n'a pas eu lieu
			if( demande.Convsta_Date_Validation_Administrative__c==null){
				handleBeforeValidationAdministrative(demande);
			}else if(demande.Status == 'Demande soumise' && demande.Convsta_Gestionnaire_en_charge__c == null){
					demande.Convsta_Date_assignation_au_gestionnaire__c = now;
					demande.Status='Demande en cours de validation administrative';
					demande.ownerId= getQueue().id;                
				}
		}
        if(roleEmIdSet.size()>0){
            map<Id,R_le__c> roleMap = new Map<Id,R_le__c>( [SELECT id,Contact__c FROM R_le__c WHERE id in :roleEmIdSet ]);
            for(Case demande:lCases){
                if(demande.Convsta_Role_EMLYON__c!=null){
                    demande.Convsta_suiveur__c =roleMap.get(demande.Convsta_Role_EMLYON__c).Contact__c;
                }
            }
        }
	}

	private static void handleBeforeValidationAdministrative(Case demande){
		if(demande.Convsta_Verdict_Pedagogique__c == 'Demande Acceptée' && demande.Convsta_Validation_Pedagogique__c==false)
		{
			if(demande.Convsta_Role_EMLYON__c!=null){
				roleEmIdSet.add(demande.Convsta_Role_EMLYON__c);
			}
			demande.Convsta_Date_Validation_Pedagogique__c      = now;
			demande.Convsta_Date_assignation_au_gestionnaire__c = now;
			demande.Convsta_Validation_Pedagogique__c   = true;
			demande.Status='Demande en cours de validation administrative';
			demande.ownerId= getQueue().id;                
			//Convsta_Object_Helper.setCasePendingValidation(demande, queue);
		}
		else if(demande.Status == 'Demande soumise' && (demande.Convsta_Gestionnaire_en_charge__c != null))
		{
			demande.Convsta_Date_Soumission_Demande__c = now;
			demande.Status='Demande en cours de validation administrative';
			demande.Convsta_Date_assignation_au_gestionnaire__c = now;
			demande.ownerId=demande.Convsta_Gestionnaire_en_charge__c; 
			//Convsta_Object_Helper.setCasePendingValidation(demande, queue);
		}
		else if(demande.Status == 'Demande soumise' && (demande.Convsta_Table_des_Regles_Experience_Pro__c != null &&
														mpRespNameById.get(demande.Id) == null))
		{
			demande.Convsta_Date_Soumission_Demande__c = now;
			demande.Status='Demande en cours de validation pédagogique';
			demande.ownerId= getQueue().id; 
		}
	}

	public static void doPostCreateSignatureConventionQueueable(Id demandeId){
		ID jobID = System.enqueueJob(new PostCreateSignatureQueueable(demandeId, true));
        System.debug([SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id=:jobID]);
	}

	public static void doPostCreateSignatureAvenantQueueable(Id demandeId){
		ID jobID = System.enqueueJob(new PostCreateSignatureQueueable(demandeId, false));
        System.debug([SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id=:jobID]);
	}

	public static void addCaseSharing(list<Case> listDemande){
		//System.debug('TR008 Add Case Sharing of : '+listDemande);
		list<CaseShare> newReadAccess = new list<CaseShare>() ;
		for(Case dem : listDemande){
			CaseShare cs = new CaseShare() ;
			cs.CaseId = dem.Id ;
			cs.CaseAccessLevel = 'Read' ;
			cs.UserOrGroupId = dem.Convsta_Responsable_Pedagogique__c ;
			newReadAccess.add(cs) ;
		}
		if(newReadAccess.size()>0){
			database.insert( newReadAccess,false) ;
		}
	}

	public static void deleteCaseSharing(Map<Id, Id> mapSharingToDelete){
		//System.debug('TR008 Delete Case Sharing of : '+mapSharingToDelete);
		list<CaseShare> deleteAccess = new list<CaseShare>() ;
		for(CaseShare cs : [SELECT Id, CaseId, UserOrGroupId FROM CaseShare WHERE CaseID IN: mapSharingToDelete.keyset()]){
			if(cs.UserOrGroupId == mapSharingToDelete.get(cs.CaseId)){
				deleteAccess.add(cs) ;
			}
		}
		if(deleteAccess.size()>0){
			database.delete( deleteAccess, false) ;
		}
	}
}