force-app/main/default/objects/Case/fields/Convsta_eSign_ExtId__c.field-meta.xml
<CustomField>
    <fullName>Convsta_eSign_ExtId__c</fullName>
    <externalId>true</externalId>
    <label>eSign ExtId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Langue__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Langue__c</fullName>
    <label>Langue de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Français</fullName>
            </value>
            <value>
                <fullName>Anglais</fullName>
            </value>
            <value>
                <fullName>Espagnol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Referent_pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Referent_pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tuteur emlyon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Le contact doit être désigné comme Tuteur EM.</errorMessage>
        <filterItems>
            <field>Contact.Convsta_Tuteur_EM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status</field>
            <operation>equals</operation>
            <value>En cours de signature, Signée, En cours d&apos;évaluation, Validée, Evaluée</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Référent pédagogique)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Signataire_delegue__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Signataire_delegue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si ce champ est renseigné, c&apos;est ce contact qui signera la convention à la place du tuteur emlyon</inlineHelpText>
    <label>Délégation pour le tuteur école</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Signataire délégué)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Tuteur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Tuteur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tuteur entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsable_administratif_entreprise__c.field-meta.xml
<CustomField>
    <fullName>Responsable_administratif_entreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable administratif entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Responsable administratif entreprise)</relationshipLabel>
    <relationshipName>convsta_stages_responsable_entreprise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Ne_pas_faire_signer_le_resp_pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Ne_pas_faire_signer_le_resp_pedagogique__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ne pas faire signer le resp pédagogique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PostCreateSignatureQueueable.cls
/*--------------------------------------------------------------------
-- - Purpose             : Queueable class that call eSign API to PostCreateSignature 
--            
-- - Maintenance History :
--
-- Date        Name  Company  Version  Remarks 
-- ----------  ----  -------  -------  -------------------------------
-- 14/01/2018  T.CH  MODIS    1.0      Creation
--------------------------------------------------------------------*/
public class PostCreateSignatureQueueable implements Queueable,Database.AllowsCallouts {
    Id demandeId;
    Boolean isForConvention;

    public PostCreateSignatureQueueable(Id demandeIdParam, Boolean isForConventionParam){
        this.demandeId          = demandeIdParam;
        this.isForConvention    = isForConventionParam;
    }

    public void execute(QueueableContext context) {
        Case demande = [SELECT Id,Convsta_Langue__c,Convsta_eSign_ExtId__c,CaseNumber, 
                        		CreatedDate,
                        		ParentId,
		                        parent.Responsable_administratif_entreprise__c,
                                Convsta_Tuteur__r.Email,
                                Convsta_Tuteur__r.LastName,
                                Convsta_Tuteur__r.FirstName,
                                Convsta_Tuteur__c,
                                Responsable_administratif_entreprise__r.Email,
                                Responsable_administratif_entreprise__r.LastName,
                                Responsable_administratif_entreprise__r.FirstName,
                                Responsable_administratif_entreprise__c,
                                Contact.Email,
                                Contact.LastName,
                                Contact.FirstName,
                                Contact.Id,
                                Convsta_Signataire_delegue__r.Email,
                                Convsta_Signataire_delegue__r.FirstName,
                                Convsta_Signataire_delegue__r.LastName,
                                Convsta_Signataire_delegue__c,
                                Convsta_Referent_pedagogique__r.Email,
                                Convsta_Referent_pedagogique__r.FirstName,
                                Convsta_Referent_pedagogique__r.LastName,
                                Convsta_Referent_pedagogique__c,
                        		Convsta_Table_des_Regles_Experience_Pro__c,
                                Convsta_Table_des_Regles_Experience_Pro__r.Ne_pas_faire_signer_le_resp_pedagogique__c            
                        FROM Case 
                        WHERE Id= :this.demandeId LIMIT 1];
        
        Convsta_WS_Helper.doPostSignatureCreateFromQueueable(demande, this.isForConvention);        
    }

    //Relancer en finish
}