force-app/main/default/objects/Case/fields/Convsta_Detail_statut_signataire__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Detail_statut_signataire__c</fullName>
    <inlineHelpText>Ce champ permet de connaitre où en est chaque signataire au niveau du processus de signature</inlineHelpText>
    <label>Détails du statut de chaque signataires</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_eSign_Errors__c.field-meta.xml
<CustomField>
    <fullName>Convsta_eSign_Errors__c</fullName>
    <label>Erreur de processus</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_eSign_ExtId__c.field-meta.xml
<CustomField>
    <fullName>Convsta_eSign_ExtId__c</fullName>
    <externalId>true</externalId>
    <label>eSign ExtId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Statut_Signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Statut_Signature__c</fullName>
    <label>Statut de la signature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Envoyé</fullName>
            </value>
            <value>
                <fullName>Signée</fullName>
            </value>
            <value>
                <fullName>Convention validée à émettre</fullName>
            </value>
            <value>
                <fullName>Avenant validé à émettre</fullName>
            </value>
            <value>
                <fullName>Erreur génération</fullName>
            </value>
            <value>
                <fullName>Expirée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Traité manuellement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Convsta_SetDetailsSignatairesSchedulable.cls
/*-------------------------------------------------------------------
-- - Purpose : This class is used to schedule the setDetails StatusSignatures with a batch
--
-- - Maintenance History:
--
-- Date        Name  Company     Version  Remarks
-- ----------  ----  ----------- -------  ----------------------------
-- 05/02/2019  T.CH  MODIS       1.0      Initial version
--------------------------------------------------------------------*/
global class Convsta_SetDetailsSignatairesSchedulable implements Schedulable, Database.Batchable<sObject>, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Convsta_eSign_ExtId__c, Convsta_eSign_Errors__c,Convsta_Detail_statut_signataire__c FROM Case WHERE (Status = \'Convention en attente de signature\' OR Status = \'Avenant en cours de signature\') and Convsta_Statut_Signature__c !=\'Traité manuellement\' and Convsta_Statut_Signature__c !=\'Expirée\' and Convsta_Statut_Signature__c !=\'Annulé\' and Convsta_Statut_Signature__c !=\'Annulée\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Case> scope){
        List<Case> caseList = new List<Case>();
        for(Case demande :scope){
            caseList.add(Convsta_WS_Helper.setDetailStatusSignataires(demande,false));           
        }
        update caseList;
    }   
    
    global void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new Convsta_SetDetailsSignatairesSchedulable(),1);
    }
}