force-app/main/default/objects/Case/fields/Convsta_date_derniere_relance_signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_date_derniere_relance_signature__c</fullName>
    <label>dernière relance signature</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Date_Validation_Administrative__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Validation_Administrative__c</fullName>
    <label>Validation Administrative</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Detail_statut_signataire__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Detail_statut_signataire__c</fullName>
    <inlineHelpText>Ce champ permet de connaitre où en est chaque signataire au niveau du processus de signature</inlineHelpText>
    <label>Détails du statut de chaque signataires</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Statut_Signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Statut_Signature__c</fullName>
    <label>Statut de la signature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Envoyé</fullName>
            </value>
            <value>
                <fullName>Signée</fullName>
            </value>
            <value>
                <fullName>Convention validée à émettre</fullName>
            </value>
            <value>
                <fullName>Avenant validé à émettre</fullName>
            </value>
            <value>
                <fullName>Erreur génération</fullName>
            </value>
            <value>
                <fullName>Expirée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Traité manuellement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/convsta_document_signe__e/convsta_document_signe__e.object-meta.xml
<CustomObject>
    <label>convsta_document_signe</label>
    <pluralLabel>convsta_document_signes</pluralLabel>
</CustomObject>

force-app/main/default/objects/convsta_document_signe__e/fields/caseId__c.field-meta.xml
<CustomField>
    <fullName>caseId__c</fullName>
    <label>caseId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/convsta_document_signe__e/fields/hash__c.field-meta.xml
<CustomField>
    <fullName>hash__c</fullName>
    <label>hash</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eSign_Configuration__mdt/eSign_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>eSign Configuration</label>
    <pluralLabel>eSign Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/eSign_Configuration__mdt/fields/nbJoursAvantRelance__c.field-meta.xml
<CustomField>
    <fullName>nbJoursAvantRelance__c</fullName>
    <label>nbJoursAvantRelance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eSign_Configuration__mdt/fields/nbMaxRelance__c.field-meta.xml
<CustomField>
    <fullName>nbMaxRelance__c</fullName>
    <label>nbMaxRelance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Convsta_eSignCallback.cls
/*--------------------------------------------------------------------
-- - Purpose       : Cette classe sert à récupérer et mettre à jour le statut de signature d'une demande
--
-- - Maintenance History:
--
-- Date        Name  Company  Version  Remarks
-- ----------  ----  -------  -------  -------------------------------
-- 12/12/2018  T.CH  MODIS    1.0      Initial version
---------------------------------------------------------------------*/
@RestResource(urlMapping='/signRequest')
//@RestResource(urlMapping='/Convsta_eSignCallback')
global without sharing class Convsta_eSignCallback{
    @HttpGet
    global static void doGet() {
        RestContext.response.addHeader('Content-Type', 'text/plain');
        String idCase  = RestContext.request.params.get('caseId');
        String codeHash	   = (RestContext.request.params.get('hashCode')!=null ? RestContext.request.params.get('hashCode') :'0');
        String relance	   = RestContext.request.params.get('relance');
        system.debug(idCase+' '+codeHash+' '+relance);
        Case c = [SELECT id, 
                  CreatedDate,
                  Convsta_Detail_statut_signataire__c,
                  Convsta_Date_Validation_Administrative__c 
                  FROM Case 
                  WHERE Id =: idCase LIMIT 1] ;
        
        if(Integer.valueOf(codeHash) == Convsta_eSignCallback.hashCode(c)){
            if(relance != null){
                c.Convsta_date_derniere_relance_signature__c = datetime.now();
                DateTime lastupdate= null;
                List<String> statusList =c.Convsta_Detail_statut_signataire__c.split('\n');
                StatusList.remove(StatusList.size()-1);
                for( String strStatus:StatusList){
                    system.debug('str statuts line : '+strStatus+'*'+strStatus.right(19));
                    try{
                        string dateSubString = strStatus.right(19);
                        if(DateTime.newinstance(
                            Integer.valueOf(dateSubString.substring(0,4)),
                            Integer.valueOf(dateSubString.substring(5,7)),
                            Integer.valueOf(dateSubString.substring(8,10)),
                            Integer.valueOf(dateSubString.substring(11,13)),
                            Integer.valueOf(dateSubString.substring(14,16)),
                            Integer.valueOf(dateSubString.substring(17,19)))!=null){
                                lastupdate=DateTime.newinstance(
                                    Integer.valueOf(dateSubString.substring(0,4)),
                                    Integer.valueOf(dateSubString.substring(5,7)),
                                    Integer.valueOf(dateSubString.substring(8,10)),
                                    Integer.valueOf(dateSubString.substring(11,13)),
                                    Integer.valueOf(dateSubString.substring(14,16)),
                                    Integer.valueOf(dateSubString.substring(17,19)));
                                system.debug('lastUpdate update '+lastupdate);
                            }
                    }
                    catch(Exception e){
                        break;
                    }
                }
                eSign_Configuration__mdt conf = Convsta_WS_Helper.getESignConf();
                Decimal nbJourAvantSansEffet = conf.nbJoursAvantRelance__c*conf.nbMaxRelance__c;
                if(lastUpdate == null){
                    system.debug('lastUpdate was null');
                    lastUpdate= c.Convsta_Date_Validation_Administrative__c;
                }
                system.debug('LastUpdate : '+lastUpdate);
                if((lastUpdate.date().daysBetween(DateTime.now().date())) >=nbJourAvantSansEffet){
                    c.Convsta_Statut_Signature__c='Relance sans effet';
                }
                update c;
            }
            else{
                EventBus.publish(new List<convsta_document_signe__e>{ new convsta_document_signe__e (CaseId__c=idCase, hash__c=Convsta_eSignCallback.hashCode(c))});                            
            }
        }
        else{
            system.debug('£££ Modis YGA - Convsta_eSignCallback bad HashCode £££ expected : '+ Convsta_eSignCallback.hashCode(c)+' got :'+Integer.valueOf(codeHash));            
        }
        RestContext.response.responseBody = Blob.valueOf('Modis YGA eSign CallBack params : Case\'s id SF : '+idCase);//+' - Date : '+demande.Createddate/*+' - Type of Document : '+docType+' - hash code for this record : '+codeHash*/);
    }
    
    public static Integer hashCode(Case demande) {
        Integer hashCode = 43;
        hashCode = (17 * hashCode) + (demande.Id == null ? 0 : System.hashCode(String.valueOf(demande.Id)));
        hashCode = (17 * hashCode) + (demande.CreatedDate == null ? 0 : System.hashCode(demande.CreatedDate));
        return hashCode;
    }
}