force-app/main/default/objects/Case/fields/Convsta_Date_Validation_Administrative__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Date_Validation_Administrative__c</fullName>
    <label>Validation Administrative</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Derniere_Maj_Signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Derniere_Maj_Signature__c</fullName>
    <label>Dernière mise à jour de la Signature</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Detail_statut_signataire__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Detail_statut_signataire__c</fullName>
    <inlineHelpText>Ce champ permet de connaitre où en est chaque signataire au niveau du processus de signature</inlineHelpText>
    <label>Détails du statut de chaque signataires</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_eSign_ExtId__c.field-meta.xml
<CustomField>
    <fullName>Convsta_eSign_ExtId__c</fullName>
    <externalId>true</externalId>
    <label>eSign ExtId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Statut_Signature__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Statut_Signature__c</fullName>
    <label>Statut de la signature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Envoyé</fullName>
            </value>
            <value>
                <fullName>Signée</fullName>
            </value>
            <value>
                <fullName>Convention validée à émettre</fullName>
            </value>
            <value>
                <fullName>Avenant validé à émettre</fullName>
            </value>
            <value>
                <fullName>Erreur génération</fullName>
            </value>
            <value>
                <fullName>Expirée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Traité manuellement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Convsta_Validation_d_experience.recordType-meta.xml
<RecordType>
    <fullName>Convsta_Validation_d_experience</fullName>
    <active>true</active>
    <businessProcess>Convsta_Validation_Expérience</businessProcess>
    <label>Validation d&apos;expérience</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/eSign_Configuration__mdt/eSign_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>eSign Configuration</label>
    <pluralLabel>eSign Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/eSign_Configuration__mdt/fields/nbJoursAvantRelance__c.field-meta.xml
<CustomField>
    <fullName>nbJoursAvantRelance__c</fullName>
    <label>nbJoursAvantRelance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eSign_Configuration__mdt/fields/nbMaxRelance__c.field-meta.xml
<CustomField>
    <fullName>nbMaxRelance__c</fullName>
    <label>nbMaxRelance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Convsta_eSignCallbackTest.cls
@isTest
public class Convsta_eSignCallbackTest {
    @testSetup 
    static void setup(){
        Contact etudiant                        = TestDataFactory.getContact(); 
        etudiant.FirstName                      = 'TestFirstName';
        etudiant.LastName                       = 'TestLastName';
        etudiant.Email   = 'test@email.com';
        insert etudiant;
        
        Case demande = TestObjectFactory.createCase(etudiant);
        demande.recordTypeId            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_eSign_ExtId__c  = 'TestExtId';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        demande.Convsta_Date_Validation_Administrative__c = DateTime.now().addYears(-4);
        demande.Convsta_Detail_statut_signataire__c = 'CUI Hongjia signed '+demande.Convsta_Date_Validation_Administrative__c+'\n YIK hoi ready \n'+
            'YIK Hoi waiting \nMAJ 14/01/2020 17:01:06';
        insert demande;
    }
    @isTest 
    static void test(){
        Test.startTest();
        Case casetest =[select id, createdDate FROM case where Convsta_eSign_ExtId__c  = 'TestExtId' limit 1 ];
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.addParameter('caseId', casetest.id);
        req.addParameter('hashCode', String.valueOf(Convsta_eSignCallback.hashCode(casetest)));
        req.requestURI = '/signRequest?caseId='+casetest.id+'&hashCode='+Convsta_eSignCallback.hashCode(casetest);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        
        Convsta_eSignCallback.doGet();
        
        Test.stopTest();
        Case demande = [SELECT  Id, Convsta_Statut_Signature__c, Convsta_Derniere_Maj_Signature__c
                        FROM    Case
                        WHERE   Convsta_eSign_ExtId__c = 'TestExtId'];
        system.debug(RestContext.response.responseBody.toString());
        System.assert(RestContext.response.responseBody.toString().contains('eSign CallBack'));
    }
    @isTest 
    static void testRelanceKO(){
        eSign_Configuration__mdt conf = Convsta_WS_Helper.getESignConf();
        Decimal nbJourAvantSansEffet = conf.nbJoursAvantRelance__c*conf.nbMaxRelance__c;
        Case casetest =[select id, createdDate FROM case where Convsta_eSign_ExtId__c  = 'TestExtId' limit 1 ];
        caseTest.Convsta_Detail_statut_signataire__c = 'CUI Hongjia signed '+dateTime.now().addDays(-Integer.valueOf(nbJourAvantSansEffet))+'\n YIK hoi ready \n'+
            'YIK Hoi waiting \nMAJ 14/01/2020 17:01:06';
        update caseTest;
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.addParameter('caseId', casetest.id);
        req.addParameter('relance', '1');
        req.addParameter('hashCode', String.valueOf(Convsta_eSignCallback.hashCode(casetest)));
        req.requestURI = '/signRequest?caseId='+casetest.id+'&hashCode='+Convsta_eSignCallback.hashCode(casetest)+'&relance=1';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        
        Convsta_eSignCallback.doGet();
        
        Test.stopTest();
        Case demande = [SELECT  Id, Convsta_Statut_Signature__c, Convsta_Derniere_Maj_Signature__c
                        FROM    Case
                        WHERE   Convsta_eSign_ExtId__c = 'TestExtId'];
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals('Relance sans effet', demande.Convsta_Statut_Signature__c, 'statut incorrect');
        System.assert(RestContext.response.responseBody.toString().contains('eSign CallBack'));
    }
    @isTest 
    static void testRelanceOk(){
        system.debug('testRelanceOk');
        Test.startTest();
        Case casetest =[select id, createdDate FROM case where Convsta_eSign_ExtId__c  = 'TestExtId' limit 1 ];
        caseTest.Convsta_Detail_statut_signataire__c = 'CUI Hongjia signed '+dateTime.now()+'\n YIK hoi ready \n'+
            'YIK Hoi waiting \nMAJ 14/01/2020 17:01:06';
        update caseTest;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.addParameter('caseId', casetest.id);
        req.addParameter('relance', '1');
        req.addParameter('hashCode', String.valueOf(Convsta_eSignCallback.hashCode(casetest)));
        req.requestURI = '/signRequest?caseId='+casetest.id+'&hashCode='+Convsta_eSignCallback.hashCode(casetest)+'&relance=1';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        
        Convsta_eSignCallback.doGet();
        
        Test.stopTest();
        Case demande = [SELECT  Id, Convsta_Statut_Signature__c, Convsta_Derniere_Maj_Signature__c
                        FROM    Case
                        WHERE   Convsta_eSign_ExtId__c = 'TestExtId'];
        system.debug(RestContext.response.responseBody.toString());
        system.assertNotEquals('Relance sans effet', demande.Convsta_Statut_Signature__c, 'statut incorrect');
        System.assert(RestContext.response.responseBody.toString().contains('eSign CallBack'));
    }
    
    @isTest static void testFail(){
        Test.startTest();
        Case casetest =[select id, createdDate FROM case where Convsta_eSign_ExtId__c  = 'TestExtId' limit 1 ];
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        
        req.addParameter('caseId', casetest.id);
        req.requestURI = '/signRequest?caseId='+casetest.id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        
        Convsta_eSignCallback.doGet();
        
        Test.stopTest();
        
        system.debug(RestContext.response.responseBody.toString());
        System.assert(RestContext.response.responseBody.toString().contains('eSign CallBack'));
    }
}