force-app/main/default/objects/Case/fields/Convsta_Avenant__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Avenant__c</fullName>
    <label>Avenant</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Langue__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Langue__c</fullName>
    <label>Langue de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Français</fullName>
            </value>
            <value>
                <fullName>Anglais</fullName>
            </value>
            <value>
                <fullName>Espagnol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Responsable_administratif_entreprise__c.field-meta.xml
<CustomField>
    <fullName>Responsable_administratif_entreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable administratif entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Responsable administratif entreprise)</relationshipLabel>
    <relationshipName>convsta_stages_responsable_entreprise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/Convsta_Entreprise__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Entreprise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Convsta Entreprise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entreprises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Entreprise__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entreprises</relationshipLabel>
    <relationshipName>Entreprise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Nom_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Nom_Entreprise__c</fullName>
    <description>Le nom de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</description>
    <inlineHelpText>Raison sociale de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</inlineHelpText>
    <label>Nom de l&apos;Entreprise</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/Convsta_Informations_Personnelles__c.object-meta.xml
<CustomObject>
    <description>Informations personnelles de l&apos;étudiant - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Informations Personnelles</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Convsta Informations Personnelles</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informations Personnelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Informations Personnelles</relationshipLabel>
    <relationshipName>Informations_Personnelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <description>Le nom de l&apos;étudiant</description>
    <label>Nom</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <description>Le prénom de l&apos;étudiant</description>
    <label>Prénom</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Convsta_GenerationAvenantController.cls
public class Convsta_GenerationAvenantController {
    public Case                                     avenant         {get;set;}
    public Case                                     demande         {get;set;}
    public Convsta_Informations_Personnelles__c     infoPerso       {get;set;}
    public Convsta_Entreprise__c                    monEntreprise   {get;set;}
    public Date                                     dateDuJour      {get;set;}
    public Boolean                                  isPreviewMode     {get;set;}
    public string getOutputClass (){
        return isPreviewMode ?'background-color: #ffff00;':'background-color: transparent;';
    }

    public Convsta_GenerationAvenantController(){
        String caseId = ApexPages.currentPage().getParameters().get('caseId');
        isPreviewMode = ApexPages.currentPage().getParameters().get('previewMode')==null?false:true;
        
        dateDuJour =    System.Date.today();
        
        avenant=        [   SELECT  ParentId, Convsta_Avenant__c
                            FROM    Case 
                            WHERE   id=:caseId LIMIT 1];
        demande=        [   SELECT  CaseNumber,Responsable_administratif_entreprise__r.Name, Convsta_Langue__c
                            FROM    Case 
                            WHERE   id=:avenant.ParentId LIMIT 1];

        infoPerso=      [   SELECT  Nom__c, Prenom__c 
                            FROM    Convsta_Informations_Personnelles__c
                            WHERE   MD_Demande__c=:avenant.ParentId LIMIT 1];

        monEntreprise=  [   SELECT  Nom_Entreprise__c
                            FROM    Convsta_Entreprise__c 
                            WHERE   MD_Demande__c=:avenant.ParentId LIMIT 1];
    }
}