force-app/main/default/objects/Case/fields/Convsta_DateEnd__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise_Name__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise_Name__c</fullName>
    <label>Entreprise</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation liée</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type donation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Campagne</fullName>
            </value>
            <value>
                <fullName>ISF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Competence__c/Convsta_Competence__c.object-meta.xml
<CustomObject>
    <description>Une compétence qui a un master-details sur une Convsta_Evaluation__c</description>
    <label>Competence</label>
    <nameField>
        <label>Nom de Competence</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Competence__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <label>Evaluation</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Competences</relationshipLabel>
    <relationshipName>Competences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Competence__c/fields/Famille_metiers__c.field-meta.xml
<CustomField>
    <fullName>Famille_metiers__c</fullName>
    <label>Famille métiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Competence__c/fields/Label_fr__c.field-meta.xml
<CustomField>
    <fullName>Label_fr__c</fullName>
    <label>Label_fr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Competence__c/fields/Rating_displayed__c.field-meta.xml
<CustomField>
    <fullName>Rating_displayed__c</fullName>
    <formula>IF(ISNUMBER(TEXT(rating__c)),
			TEXT(rating__c) &amp; &quot;/5&quot;,
			&quot;NA&quot;
		)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating displayed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Competence__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2Comportement</fullName>
                <label>Comportement</label>
            </value>
            <value>
                <fullName>1EarlyMaker</fullName>
                <label>EarlyMaker</label>
            </value>
            <value>
                <fullName>3Métier</fullName>
                <label>Métier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Circonstances_du_stage__c.field-meta.xml
<CustomField>
    <fullName>Circonstances_du_stage__c</fullName>
    <label>Circonstances du stage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Commentaire_global__c.field-meta.xml
<CustomField>
    <fullName>Commentaire_global__c</fullName>
    <label>Commentaire global</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Demande__c.field-meta.xml
<CustomField>
    <fullName>Demande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Convsta_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Etudiant__c.field-meta.xml
<CustomField>
    <fullName>Etudiant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Etudiant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Convsta_Evaluation_Etudiant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Famille_competences_metier__c.field-meta.xml
<CustomField>
    <fullName>Famille_competences_metier__c</fullName>
    <label>Famille compétences métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance d&apos;entreprise, comptabilité, contrôle de gestion</fullName>
            </value>
            <value>
                <fullName>Ressources Humaines</fullName>
            </value>
            <value>
                <fullName>Direction Générale</fullName>
            </value>
            <value>
                <fullName>Financement, Investissements et Assurances</fullName>
            </value>
            <value>
                <fullName>Marketing et Communication</fullName>
            </value>
            <value>
                <fullName>Production et QHSE</fullName>
            </value>
            <value>
                <fullName>Audit et Conseil</fullName>
            </value>
            <value>
                <fullName>Développement commercial et relations clients</fullName>
            </value>
            <value>
                <fullName>Digital et data</fullName>
            </value>
            <value>
                <fullName>Achats</fullName>
            </value>
            <value>
                <fullName>Informatique</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management</fullName>
            </value>
            <value>
                <fullName>Juridique</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Note_globale__c.field-meta.xml
<CustomField>
    <fullName>Note_globale__c</fullName>
    <description>La note globale obtenue par l&apos;étudiant</description>
    <inlineHelpText>La note globale obtenue par l&apos;étudiant</inlineHelpText>
    <label>Note globale</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Afficher_logo_Paul_Bocuse__c.field-meta.xml
<CustomField>
    <fullName>Afficher_logo_Paul_Bocuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Afficher le logo Paul Bocuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Convsta_GenerationEvaluationController.cls
public class Convsta_GenerationEvaluationController {
    public Case                                     demande             {get;set;}
    public Boolean                                  isPreviewMode       {get;set;}
    public Convsta_Evaluation__c     				eval       		    {get;set;}
    public List<Convsta_Competence__c>              lCompEarlyMaker     {get;set;}
    public List<Convsta_Competence__c>              lCompComportem      {get;set;}
    public List<Convsta_Competence__c>              lCompMetier         {get;set;}

    public string getOutputClass (){
        return isPreviewMode ?'font-weight:bold;background-color: #ffff00;':'font-weight:bold;background-color: transparent;';
    }
    
    public Convsta_GenerationEvaluationController(){
        String evalId = ApexPages.currentPage().getParameters().get('evalId')!= null ? ApexPages.currentPage().getParameters().get('evalId') : ApexPages.currentPage().getParameters().get('id');
        isPreviewMode = ApexPages.currentPage().getParameters().get('previewMode')==null?false:true; 
	system.debug(ApexPages.currentPage().getParameters()+' '+ApexPages.currentPage().getUrl());        
        eval =			[	SELECT  Id,
                                    Demande__c,
                         			Demande__r.Convsta_Entreprise_Name__c,
                         			Etudiant__r.Name, 
                                    Etudiant__r.FirstName,
                                    Famille_competences_metier__c,
                                    Circonstances_du_stage__c,
                                    Note_globale__c,
                                    Commentaire_global__c
                        	FROM	Convsta_Evaluation__c
                        	WHERE 	ID =:evalId LIMIT 1];
        
        demande=        [   SELECT  Id, 
                                    Convsta_Table_des_Regles_Experience_Pro__r.Afficher_logo_Paul_Bocuse__c, 
                                    Convsta_DateStart__c, 
                                    Convsta_DateEnd__c
                            FROM    Case 
                            WHERE   Id=:eval.Demande__c LIMIT 1];

        lCompEarlyMaker=[   SELECT  Id,
                                    Label_fr__c,
                                    Rating_displayed__c
                            FROM    Convsta_Competence__c
                            WHERE   Evaluation__c =:evalId
                            AND     type__c = '1EarlyMaker'];

        lCompComportem= [   SELECT  Id,
                                    Label_fr__c,
                                    Rating_displayed__c
                            FROM    Convsta_Competence__c
                            WHERE   Evaluation__c =:evalId
                            AND     type__c = '2Comportement'];

        lCompMetier=    [   SELECT  Id,
                                    Label_fr__c,
                                    Rating_displayed__c
                            FROM    Convsta_Competence__c
                            WHERE   Evaluation__c =:evalId
                            AND     type__c = '3Métier'
                            AND     Famille_metiers__c =:eval.Famille_competences_metier__c];
    }
}