force-app/main/default/objects/Convsta_Informations_Personnelles__c/Convsta_Informations_Personnelles__c.object-meta.xml
<CustomObject>
    <description>Informations personnelles de l&apos;étudiant - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Informations Personnelles</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Convsta Informations Personnelles</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informations Personnelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Informations Personnelles</relationshipLabel>
    <relationshipName>Informations_Personnelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Informations_Personnelles__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <description>Le nom de l&apos;étudiant</description>
    <label>Nom</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Convsta_informations_persoTriggerTest.cls
@isTest
public class Convsta_informations_persoTriggerTest {
    @isTest
    public static void test(){
        Case demande = TestDataFactory.getCaseWithSigners();
        insert demande;
        
        Convsta_informations_personnelles__c information = new Convsta_informations_personnelles__c(MD_Demande__c = demande.Id);
        insert information;
                
		information.Nom__c = 'Test';        
        update information;
        
        //Only code coverage
    }
}