force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TR009ManageConvstaEvaluationTest.cls
@isTest
public class TR009ManageConvstaEvaluationTest {
    @isTest
    public static void shareEvalWithRespPedaTest(){
        User respPedagogique = TestObjectFactory.createUser('RespPedago','Responsable Pédagogique');
        insert respPedagogique;
        Convsta_Evaluation__c evaluation = TestObjectFactory.createEvaluation();
        evaluation.Responsable_Pedagogique__c = respPedagogique.Id;
        insert evaluation;    
                    
        Test.startTest();
        Convsta_Evaluation__Share evalShare = Convsta_Internship.shareEvalWithRespPeda(evaluation);
        insert evalShare;
        Test.stopTest();
    
        List<Convsta_Evaluation__Share> jShrs = [
            SELECT Id, UserOrGroupId, AccessLevel, RowCause 
            FROM Convsta_Evaluation__Share 
            WHERE ParentId =:evaluation.Id 
            AND UserOrGroupId =:respPedagogique.Id];

        System.assertEquals(jShrs.size(), 1);
        System.assertEquals(jShrs[0].AccessLevel, 'Read');
        System.assertEquals(jShrs[0].RowCause, 'Manual');
    }
}