force-app/main/default/objects/Account/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse courante: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeAPE__c.field-meta.xml
<CustomField>
    <fullName>CodeAPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAF</label>
    <referenceTo>NAF__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse courante: Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lieu_ls__c.field-meta.xml
<CustomField>
    <fullName>Lieu_ls__c</fullName>
    <label>Lieu</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lyon</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse:Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect Etudiant</fullName>
            </value>
            <value>
                <fullName>Etudiant</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Detail_pack__c/Detail_pack__c.object-meta.xml
<CustomObject>
    <label>Détail pack</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Id de Détail pack</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail_pack__c/fields/Composant__c.field-meta.xml
<CustomField>
    <fullName>Composant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composant</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pack parent</relationshipLabel>
    <relationshipName>Composant_pack</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detail_pack__c/fields/Pack__c.field-meta.xml
<CustomField>
    <fullName>Pack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pack</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Détails pack</relationshipLabel>
    <relationshipName>Details_pack</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NAF__c/NAF__c.object-meta.xml
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAF__c/fields/CODE_APE__c.field-meta.xml
<CustomField>
    <fullName>CODE_APE__c</fullName>
    <externalId>true</externalId>
    <label>CODE APE</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_central__c.field-meta.xml
<CustomField>
    <fullName>Contact_central__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact central</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exercice__c.field-meta.xml
<CustomField>
    <fullName>Exercice__c</fullName>
    <label>Exercice EMLYON</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
                <default>true</default>
                <label>2015</label>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exercice_de_report__c.field-meta.xml
<CustomField>
    <fullName>Exercice_de_report__c</fullName>
    <label>Exercice de report</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Code_OLI__c.field-meta.xml
<CustomField>
    <fullName>Code_OLI__c</fullName>
    <externalId>true</externalId>
    <label>Code_OLI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CodeAgresso_Poste_Opportunite__c.field-meta.xml
<CustomField>
    <fullName>CodeAgresso_Poste_Opportunite__c</fullName>
    <description>Ce champ est remplit automatiquement en se basant sur &quot; RecordType + Exercice + Compteur Opp&quot;</description>
    <label>Code Agresso Poste Opportunité</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>TEXT(Opportunity.StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session de formation</label>
    <nameField>
        <label>Nom de Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions de formation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Code_agresso_for__c.field-meta.xml
<CustomField>
    <fullName>Code_agresso_for__c</fullName>
    <description>Ce champ va être renseigné manuellement ou par chargement et sert pour export vers AGRESSO en tant que code formation. Ex: 15SELPGM--1</description>
    <label>Code agresso Formation</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Code_Agresso_Session_formation__c.field-meta.xml
<CustomField>
    <fullName>Code_Agresso_Session_formation__c</fullName>
    <label>Code Agresso Session formation</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date_de_debut_de_session__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut_de_session__c</fullName>
    <label>Date de début de session</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date_de_fin_de_session__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_session__c</fullName>
    <label>Date de fin de session</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Exercice_fiscale__c.field-meta.xml
<CustomField>
    <fullName>Exercice_fiscale__c</fullName>
    <label>Exercice fiscal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF-EF10</fullName>
            </value>
            <value>
                <fullName>SF-EF20</fullName>
            </value>
            <value>
                <fullName>SF-EF30</fullName>
            </value>
            <value>
                <fullName>SF-EF40</fullName>
            </value>
            <value>
                <fullName>SF-EF50</fullName>
            </value>
            <value>
                <fullName>SF-EF60</fullName>
            </value>
            <value>
                <fullName>SF-EF70</fullName>
            </value>
            <value>
                <fullName>SF-EF80</fullName>
            </value>
            <value>
                <fullName>SF-EF90</fullName>
            </value>
            <value>
                <fullName>SF-EF100</fullName>
            </value>
            <value>
                <fullName>SF-EF110</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Lieu_ls__c.field-meta.xml
<CustomField>
    <fullName>Lieu_ls__c</fullName>
    <label>Lieu</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF-LS10</fullName>
            </value>
            <value>
                <fullName>SF-LS20</fullName>
            </value>
            <value>
                <fullName>SF-LS30</fullName>
            </value>
            <value>
                <fullName>SF-LS40</fullName>
            </value>
            <value>
                <fullName>SF-LS50</fullName>
            </value>
            <value>
                <fullName>SF-LS60</fullName>
            </value>
            <value>
                <fullName>SF-LS70</fullName>
            </value>
            <value>
                <fullName>SF-LS80</fullName>
            </value>
            <value>
                <fullName>SF-LS90</fullName>
            </value>
            <value>
                <fullName>SF-LS100</fullName>
            </value>
            <value>
                <fullName>SF-LS110</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Mode_apprentissage__c.field-meta.xml
<CustomField>
    <fullName>Mode_apprentissage__c</fullName>
    <label>Mode d&apos;apprentissage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF-MA10</fullName>
            </value>
            <value>
                <fullName>SF-MA20</fullName>
            </value>
            <value>
                <fullName>SF-MA30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Produits__c.field-meta.xml
<CustomField>
    <fullName>Produits__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF-SS10</fullName>
            </value>
            <value>
                <fullName>SF-SS20</fullName>
            </value>
            <value>
                <fullName>SF-SS30</fullName>
            </value>
            <value>
                <fullName>SF-SS40</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTR002ManageOpportunityLineItem.cls
/**
LastModifiedBy Sabri Dali 16/03/2016
test class correction and assert implementation
cooments added
*/
@isTest
private class TestTR002ManageOpportunityLineItem {

    @isTest static void myUnitTest() {

       //Data creation
       NAF__c naf = new NAF__c(Name='naf',CODE_APE__c='1234');
       insert naf;

       Pays__c pays = new Pays__c();
       pays.Name = 'France';
       insert pays;

       Account acc = new Account(Name='test');
       acc.SIRET__c='00000000000000';
       acc.CodeAPE__c=naf.Id;
       acc.Industry='Agriculture';
       acc.CodePays__c = pays.id;
       acc.Adresse_Ville__c = 'Nantes';
       insert acc;

       Contact contact= new Contact(AccountId=acc.Id,statut__c='Etudiant',FirstName='Asmae',LastName='Ettahiri',Salutation='Mme');
       insert contact;

       Product2 prod = new Product2(Name='prodTest');
       insert prod;

       // Get standard price book ID.
       // This is available irrespective of the state of SeeAllData.
       Id standardPbId = Test.getStandardPricebookId();

       Pricebookentry pricebook1= new PriceBookEntry(Product2Id=prod.Id, UnitPrice=10, Pricebook2Id=standardPbId, IsActive = true, UseStandardPrice = false);
       insert pricebook1;

       Date d = System.Today();
       Opportunity opp= new Opportunity(StageName='test',Name='test',Contact_central__c=contact.Id,AccountId=acc.Id,Exercice__c='2015',CloseDate=Date.valueOf('2015-08-15'));
       opp.CloseDate=Date.valueOf('2015-08-15');
       System.debug('#####CloseDate'+opp.CloseDate);
       insert opp;


       OpportunityLineItem oli = new OpportunityLineItem(PricebookentryId=pricebook1.Id, Totalprice=23, Quantity=2);
       oli.OpportunityId=opp.Id;

       //Test
       Test.startTest();
       insert oli;
       List<OpportunityLineItem> oppLine = [SELECT id,Name FROM OpportunityLineItem where OpportunityId=:opp.Id];
       System.assertEquals(oppLine.size(),1);
       Test.stopTest();
    }
    
    @isTest static void IncrementCompteurOppLine(){
        // Simuler Top Agresso ou Interface
        PAD.addTriggerBypass('TR006OppLineItem2FieldsNull');
      	PAD.addTriggerBypass('TR007Opp2FieldsNull');

        Account acc = TestDataFactory.getAccount();
        insert acc;
        
        List<Opportunity> oppList = new List<Opportunity>();
        // Met criteria
        Opportunity opp1 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Pré inscrit');
        oppList.add(opp1);

        Opportunity opp2 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Inscrit');
        oppList.add(opp2);

        Opportunity opp3 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Admis');
        oppList.add(opp3);

        Opportunity opp4 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Intégré');
        oppList.add(opp4);

        Opportunity opp5 = TestObjectFactory.createOpportunity(acc,  'Programme Long Diplômant', 'Candidat');
        oppList.add(opp5);

        // Don't met criteria
        Opportunity opp6 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Prospect report');
        // validation rule
        opp6.Exercice_de_report__c = '2023'; 
        oppList.add(opp6);

        Opportunity opp7 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Prospect report');
        opp7.Exercice_de_report__c = '2023'; 
        oppList.add(opp7);

        // Met criteria
        Opportunity opp8 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Candidat');
        oppList.add(opp8);

        // Met criteria (opp line will contains Agresso)
        Opportunity opp9 = TestObjectFactory.createOpportunity(acc, 'Formation intra-entreprise');
        oppList.add(opp9);

        insert oppList;

        Product2 prod2 = TestObjectFactory.createProduct2();
        insert prod2;
        Pricebookentry pricebookentry= TestObjectFactory.createPricebookEntryStandard(prod2.Id);
        insert pricebookentry;

        List<OpportunityLineItem> oppLineList = new List<OpportunityLineItem>();
        for (Opportunity opp: oppList) { 
            oppLineList.add(TestObjectFactory.createOpportunityLineItem(opp.Id, prod2.Id, pricebookentry.Id));
        }

        // Set Agresso to see no change
        oppLineList[8].CodeAgresso_Poste_Opportunite__c = 'IEXX-XXXXXX';

        Test.startTest();
        insert oppLineList;
        update oppLineList[8]; // Simulate update on existing Agresso : no change
        Test.stopTest();

        oppLineList[0] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp1.Id];
        oppLineList[1] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp2.Id];
        oppLineList[2] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp3.Id];
        oppLineList[3] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp4.Id];
        oppLineList[4] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp5.Id];
        oppLineList[5] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp6.Id];
        oppLineList[6] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp7.Id];
        oppLineList[7] = [SELECT Id, Code_OLI__c FROM OpportunityLineItem WHERE OpportunityId = :opp8.Id];
        oppLineList[8] = [SELECT Id, CodeAgresso_Poste_Opportunite__c FROM OpportunityLineItem WHERE OpportunityId = :opp9.Id];

        // Incrementation
        System.assertEquals(oppLineList[0].Code_OLI__c + 1, oppLineList[1].Code_OLI__c);
        System.assertEquals(oppLineList[1].Code_OLI__c + 1, oppLineList[2].Code_OLI__c);
        System.assertEquals(oppLineList[2].Code_OLI__c + 1, oppLineList[3].Code_OLI__c);
        System.assertEquals(oppLineList[3].Code_OLI__c + 1, oppLineList[4].Code_OLI__c);

        // No incrementation
        System.assertEquals(null, oppLineList[5].Code_OLI__c);
        System.assertEquals(null, oppLineList[6].Code_OLI__c);
        
        // Incrementation
        System.assertEquals(oppLineList[4].Code_OLI__c + 1, oppLineList[7].Code_OLI__c);

        // No change on Agresso
        System.assertEquals('IEXX-XXXXXX', oppLineList[8].CodeAgresso_Poste_Opportunite__c);
        
        // Simuler Top Agresso ou Interface
        PAD.removeTriggerBypass('TR006OppLineItem2FieldsNull');
      	PAD.removeTriggerBypass('TR007Opp2FieldsNull');
    }

    @isTest static void attachSession() {
        // get Product RecordTypes 
        Id recordTypePackId = APU_ApexUtils.getProduct2RecordTypeIdByName('Pack');
        Id recordTypeModuleId = APU_ApexUtils.getProduct2RecordTypeIdByName('Module');
        
        //date creation
        NAF__c naf = new NAF__c(Name='naf',CODE_APE__c='1234');
        insert naf;
        
        Pays__c pays = new Pays__c();
        pays.Name = 'France';
        insert pays;
        
        Account acc = new Account(Name='test');
        acc.SIRET__c='00000000000000';
        acc.CodeAPE__c=naf.Id;
        acc.Industry='Agriculture';
        acc.CodePays__c = pays.id;
        acc.Adresse_Ville__c = 'Nantes';
        insert acc;
        
        Contact contact= new Contact(AccountId=acc.Id,statut__c='Etudiant',FirstName='Asmae',LastName='Ettahiri',Salutation='Mme');
        insert contact;
        
        Product2 prod = new Product2(Name='prodTest', RecordTypeId = recordTypeModuleId);
        insert prod;
        Product2 prod_module = new Product2(Name='prodTest', RecordTypeId = recordTypeModuleId);
        insert prod_module;
        
        Detail_pack__c dp= new Detail_pack__c(Pack__c=prod.Id,Composant__c=prod_module.Id);
        insert dp;
        
        Session__c ses_pack = new Session__c (Name = 'pack', Produits__c = prod.Id, 
                                              Code_agresso_for__c = '54983',
                                              Code_Agresso_Session_formation__c = 'codeAgr1',
                                              Date_de_debut_de_session__c = System.today() + 5,
            Date_de_fin_de_session__c = System.today() + 15,
            Exercice_fiscale__c = 'SF-EF10',
            Lieu_ls__c = 'SF-LS10',
            Mode_apprentissage__c = 'SF-MA10');
        insert ses_pack;
        
        Session__c ses_module = new Session__c (Name = 'module', Produits__c = prod_module.Id,  
                                                Code_agresso_for__c = '98456', 
                                                Code_Agresso_Session_formation__c = 'codeAgr2',
                                                Date_de_debut_de_session__c = System.today() + 5,
            Date_de_fin_de_session__c = System.today() + 15,
            Exercice_fiscale__c = 'SF-EF10',
            Lieu_ls__c = 'SF-LS10',
            Mode_apprentissage__c = 'SF-MA10');
        insert ses_module;
        
        Detail_pack_session__c dps = new Detail_pack_session__c(Composant_session__c=ses_module.Id,Pack_Session__c=ses_pack.id);
        insert dps;
        
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id standardPB = Test.getStandardPricebookId();
        
        Pricebookentry pricebook1= new PriceBookEntry(Product2Id=prod.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
        insert pricebook1;
        
        Pricebookentry pricebook2= new PriceBookEntry(Product2Id=prod_module.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
        insert pricebook2;
        
        Date d = System.Today();
        Opportunity opp= new Opportunity(Pricebook2Id=standardPB,StageName='test',Name='test',Contact_central__c=contact.Id,AccountId=acc.Id,Exercice__c='2015',CloseDate=Date.valueOf('2015-08-15'));
        opp.CloseDate=Date.valueOf('2015-08-15');
        insert opp;        
        
        OpportunityLineItem oliModule = new OpportunityLineItem(PricebookentryId=pricebook2.Id, Totalprice=23, Quantity=2, Session_de_formation__c = ses_pack.Id, OpportunityId=opp.Id, Type_produit__c = 'Module');
        insert oliModule;
        PAD.removeTriggerHasRun('TR002ManageOpportunityLineItem');

        OpportunityLineItem oliPack = new OpportunityLineItem(PricebookentryId=pricebook1.Id, Totalprice=23, Quantity=2, Session_de_formation__c = ses_pack.Id, OpportunityId=opp.Id, Type_produit__c = 'Pack');
        
        // Test
        Test.startTest();
        insert oliPack;
        //Tester l'update
        
        List<OpportunityLineItem> lcontrolOppLI = [select id,Session_de_formation__c from OpportunityLineItem where OpportunityId =: opp.Id and Session_de_formation__c =:ses_module.id];
        System.assert(lcontrolOppLI!=null);
        
        Test.stopTest();
    }

    @isTest static void createOppLineItem(){
        //Get Product RecordType
        Id recordTypePackId = APU_ApexUtils.getProduct2RecordTypeIdByName('Pack');
        Id recordTypeModuleId = APU_ApexUtils.getProduct2RecordTypeIdByName('Module');

        Account acc = TestDataFactory.getAccount();
        insert acc;

        Contact contact= TestDataFactory.getContact();
        insert contact;

        Product2 prodPack = new Product2(Name='Produit Pack',Suiveur__c = UserInfo.getUserId(),RecordTypeId =recordTypePackId);
        insert prodPack;

        Product2 prodModule = new Product2(Name='Produit Module',RecordTypeId = recordTypeModuleId);
        insert prodModule;

        Detail_pack__c dp= new Detail_pack__c(Pack__c=prodPack.Id,Composant__c=prodModule.Id);
        insert dp;      

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id standardPB = Test.getStandardPricebookId();

        Pricebookentry pricebookPack= new PriceBookEntry(Product2Id=prodPack.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
        insert pricebookPack;

        Pricebookentry pricebookModule= new PriceBookEntry(Product2Id=prodModule.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
        insert pricebookModule;

        Date d = System.Today();
        Opportunity opp= new Opportunity(Pricebook2Id=standardPB ,StageName='test',Name='test',Contact_central__c=contact.Id,AccountId=acc.Id);
        opp.CloseDate=Date.today().addDays(1);
        insert opp;
        
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id, PricebookentryId=pricebookPack.Id, Totalprice=23, Quantity=2,Product2Id =prodPack.Id);     
        
        //Test
        Test.startTest();   
        insert oli; 
        List<OpportunityLineItem> controlOppLI = [select id from OpportunityLineItem where OpportunityId =: opp.Id];
        System.assertEquals(2, controlOppLI.size());
        Test.stopTest();   
    }
}