force-app/main/default/objects/Account/fields/Adresse_Rue__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Rue__c</fullName>
    <label>Adresse courante: Rue</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse courante: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <formula>CodeAPE__r.CODE_APE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code NAF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Adresse courante: Code Postal</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeAPE__c.field-meta.xml
<CustomField>
    <fullName>CodeAPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAF</label>
    <referenceTo>NAF__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse courante: Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Convsta_Modifie_par_Convsta__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Modifie_par_Convsta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique si le compte a été modifié par Convsta</description>
    <label>Modifié par Convsta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tranche_d_effectif__c.field-meta.xml
<CustomField>
    <fullName>Tranche_d_effectif__c</fullName>
    <label>Tranche d&apos;effectif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>De 0 à 9</fullName>
            </value>
            <value>
                <fullName>De 10 à 49</fullName>
            </value>
            <value>
                <fullName>De 50 à 249</fullName>
            </value>
            <value>
                <fullName>De 250 à 499</fullName>
            </value>
            <value>
                <fullName>De 500 à 999</fullName>
            </value>
            <value>
                <fullName>De 1000 à 1999</fullName>
            </value>
            <value>
                <fullName>De 2000 à 4999</fullName>
            </value>
            <value>
                <fullName>De 5000 à 9999</fullName>
            </value>
            <value>
                <fullName>10 000 et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Localisation_de_l_entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Localisation_de_l_entreprise__c</fullName>
    <label>Localisation de l&apos;entreprise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En France</fullName>
                <default>true</default>
                <label>En France</label>
            </value>
            <value>
                <fullName>A l&apos;étranger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Convsta_Modifie_par_Convsta__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Modifie_par_Convsta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique si le contact a été créé ou modifié par Convsta</description>
    <label>Modifié par Convsta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse:Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/Convsta_Entreprise__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Entreprise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Convsta Entreprise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entreprises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Adresse_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Entreprise__c</fullName>
    <description>L&apos;adresse de l&apos;entreprise</description>
    <inlineHelpText>Adresse de l&apos;entreprise</inlineHelpText>
    <label>Adresse de l&apos;Entreprise</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/code_NAF__c.field-meta.xml
<CustomField>
    <fullName>code_NAF__c</fullName>
    <label>code NAF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <description>Le code postal de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Code postal de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</inlineHelpText>
    <label>Code Postal</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Email_Signataire_Convention__c.field-meta.xml
<CustomField>
    <fullName>Email_Signataire_Convention__c</fullName>
    <description>L&apos;adresse email de l&apos;employé en charge des ressources humaines qui peut engager l’entreprise dans le cadre de l&apos;expérience professionnelle de l&apos;étudiant.</description>
    <inlineHelpText>Conseil : Demandez qui va recevoir et signer la convention. ex: le responsable légal peut être le Directeur Général mais c&apos;est dans les faits son assistante qui signera la convention.C&apos;est donc effectivement le mail de l&apos;assistante qu&apos;il faudra renseigner</inlineHelpText>
    <label>Email du Signataire de la Convention</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entreprises</relationshipLabel>
    <relationshipName>Entreprise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Nom_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Nom_Entreprise__c</fullName>
    <description>Le nom de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</description>
    <inlineHelpText>Raison sociale de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</inlineHelpText>
    <label>Nom de l&apos;Entreprise</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Nom_Signataire_Convention__c.field-meta.xml
<CustomField>
    <fullName>Nom_Signataire_Convention__c</fullName>
    <description>Le nom de l&apos;employé en charge des ressources humaines qui peut engager l’entreprise dans le cadre de l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Conseil : Attention à l&apos;orthographe !!</inlineHelpText>
    <label>Nom du Signataire de la Convention</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Pays2__c.field-meta.xml
<CustomField>
    <fullName>Pays2__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>pays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Prenom_Signataire_Convention__c.field-meta.xml
<CustomField>
    <fullName>Prenom_Signataire_Convention__c</fullName>
    <description>Le prénom de l&apos;employé en charge des ressources humaines qui peut engager l’entreprise dans le cadre de l&apos;expérience professionnelle de l&apos;étudiant.</description>
    <inlineHelpText>Conseil : Attention à l&apos;orthographe !!</inlineHelpText>
    <label>Prénom du Signataire de la Convention</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <description>Le numéro SIRET de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Numéro SIRET de l&apos;entreprise signataire de la convention de stage.</inlineHelpText>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Telephone_Signataire_Convention__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Signataire_Convention__c</fullName>
    <description>Le numéro de téléphone de l&apos;employé en charge des ressources humaines qui peut engager l’entreprise dans le cadre de l&apos;expérience professionnelle de l&apos;étudiant</description>
    <inlineHelpText>Numéro de téléphone du représentant légal qui peut engager l’entreprise dans le cadre de l&apos;expérience professionnelle de l&apos;étudiant</inlineHelpText>
    <label>Téléphone du Signataire de la Convention</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Tranche_effectif_etablissement__c.field-meta.xml
<CustomField>
    <fullName>Tranche_effectif_etablissement__c</fullName>
    <label>Tranche effectif etablissement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <description>La ville où est située l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Localisation de l&apos;entreprise signataire de la convention.</inlineHelpText>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Demande__c.field-meta.xml
<CustomField>
    <fullName>Demande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Convsta_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/Convsta_Mission__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à la mission que l&apos;étudiant effectuera en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Convsta Mission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Mission__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Prenom_Tuteur_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Prenom_Tuteur_Entreprise__c</fullName>
    <description>Le prénom de l&apos;employé de l’entreprise en charge de l’étudiant pendant son expérience professionnelle.</description>
    <inlineHelpText>Conseil: Attention à l&apos;orthographe</inlineHelpText>
    <label>Prénom du Tuteur Entreprise</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAF__c/NAF__c.object-meta.xml
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAF__c/fields/CODE_APE__c.field-meta.xml
<CustomField>
    <fullName>CODE_APE__c</fullName>
    <externalId>true</externalId>
    <label>CODE APE</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pays__c/Pays__c.object-meta.xml
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pays__c/fields/Code_Pays_2_caracteres__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays_2_caracteres__c</fullName>
    <label>Code Pays 2 caractères</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/pays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <masterLabel>pays</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/Convsta_Object_Helper.cls
/*-------------------------------------------------------------------
-- - Purpose : Helper for Convsta's objects
--
-- - Maintenance History:
--
-- Date        Name  Company     Version  Remarks
-- ----------  ----  ----------- -------  ----------------------------
-- XX/XX/20XX  E.BE  MODIS       1.0      Initial version
-- 14/12/2018  T.CH  MODIS       1.1      Adding method for Resp. Admin. and Tuteur creations, company check & upsert
-- 16/05/2019  T.CH  MODIS       1.2      Adding method to share a file from back office to community
-- 04/06/2019  E.CA  MODIS       1.3      Adding method to map fonction contact
-- 17/12/2019  Y.GA  MODIS		 1.4	  MAJ checkMatchingAccountAndContact : update Account if SIRET already exists, create an Account 
--------------------------------------------------------------------*/
public without sharing class Convsta_Object_Helper {
    
    public static Case checkMatchingAccountAndContact(Id demandeId){
        Case demande = new Case(Id=demandeId);

        try{
            Boolean updateDemandeBool = false;
            // Get entreprise and resp.admin. informations from the company of the request
            Convsta_Entreprise__c entreprise = [SELECT  Id, MD_Demande__r.Convsta_Localisation_de_l_entreprise__c , Nom_Entreprise__c, Pays2__c, Ville__c, //Check existing account & Upsert french account
                                                        Prenom_Signataire_Convention__c, Nom_Signataire_Convention__c, Email_Signataire_Convention__c, Telephone_Signataire_Convention__c, //Check existing & update contact
                                                        SIRET__c, Adresse_Entreprise__c, Code_Postal__c, Tranche_effectif_etablissement__c, Code_NAF__c //Upsert french account                                               
                                                FROM    Convsta_Entreprise__c
                                                WHERE   MD_Demande__c = :demandeId];

            // Check french company : upsert
            if(entreprise.MD_Demande__r.Convsta_Localisation_de_l_entreprise__c == 'En France'){
                List<Pays__c> lPays =  [SELECT  Id
                                        FROM    Pays__c
                                        WHERE   Code_Pays_2_caracteres__c = :entreprise.Pays2__c];
                String codeApe = entreprise.Code_NAF__c.replaceAll('\\W','');
                NAF__c nafRef =    [
                    SELECT  Id
                    FROM    NAF__c
                    WHERE   CODE_APE__c = :codeApe
                    LIMIT 1];
                if(lPays.size() > 0){
                    ID interfaceId = [SELECT Id FROM User WHERE Name = 'Interface'].Id;
                    Boolean accountFound = false ;
                    // 17/12/2019 - Y.GA - MODIS - 1.4
                    List<Account> listAcc = [SELECT Id, 
                                   		  SIRET__c, 
                                   		  Adresse_Rue__c, 
                                   		  CodePays__c,
										  CodeAPE__c,
										  Code_Postal__c,
										  Adresse_Ville__c,
										  Tranche_d_effectif__c,
										  Convsta_Modifie_par_Convsta__c
                                   FROM Account 
                                   WHERE SIRET__c =: entreprise.SIRET__c
                                  ] ;
                    Account acc ;
                    if(listAcc.size()==0){   
                        /*Account*/ acc = new Account(    SIRET__c =              entreprise.SIRET__c,
                                                  Name =                  entreprise.Nom_Entreprise__c,
                                                  Adresse_Rue__c =        entreprise.Adresse_Entreprise__c,
                                                  CodePays__c =           lPays[0].Id,
                                                  CodeAPE__c =            nafRef.Id,
                                                  Code_Postal__c =        entreprise.Code_Postal__c,
                                                  Adresse_Ville__c =      entreprise.Ville__c,
                                                  Tranche_d_effectif__c = entreprise.Tranche_effectif_etablissement__c,
                                                  Convsta_Modifie_par_Convsta__c = true,
                                                  OwnerId= interfaceId);
                        Database.insert(acc, false) ;
                    }
                    else{
                        /*Account*/ acc = listAcc.get(0) ;
                                                  acc.Adresse_Rue__c =        entreprise.Adresse_Entreprise__c;
                                                  acc.CodePays__c =           lPays[0].Id;
                                                  acc.Code_Postal__c =        entreprise.Code_Postal__c;
                                                  acc.Adresse_Ville__c =      entreprise.Ville__c;
                                                  acc.Tranche_d_effectif__c = entreprise.Tranche_effectif_etablissement__c;
                                                  acc.Convsta_Modifie_par_Convsta__c = true;
                        						  if (acc.CodeAPE__c == null) {
                                                    acc.CodeAPE__c =          nafRef.Id;
                                                  }

                        Database.update(acc, false) ;                        
                    }                                                
                    //Database.upsert(acc, Account.Fields.SIRET__c);
                    demande.Convsta_Entreprise__c = acc.Id;
                    updateDemandeBool=true;
                }
            }else{
                List<Account> lMatchingAccount = [  SELECT  Id
                                                    FROM    Account
                                                    WHERE   Name =                                  :entreprise.Nom_Entreprise__c
                                                    AND     CodePays__r.Code_Pays_2_caracteres__c = :entreprise.Pays2__c
                                                    AND     Adresse_Ville__c =                      :entreprise.Ville__c];
                // Affect existing foreign account to request
                if(lMatchingAccount.size() > 0){
                    demande.Convsta_Entreprise__c = lMatchingAccount[0].Id;
                    updateDemandeBool=true;
                }
            }
            // Update contacts if we have a company
            if(demande.Convsta_Entreprise__c != null){
                // Get tuteur informations from the mission of the request
                Convsta_Mission__c mission = [  SELECT  Id,
                                                        Prenom_Tuteur_Entreprise__c, Nom_Tuteur_Entreprise__c, Email_Tuteur_Entreprise__c, Telephone_Tuteur_Entreprise__c
                                                FROM    Convsta_Mission__c
                                                WHERE   MD_Demande__c = :demande.Id];
                
                // Check for existing tuteur or resp.admin from mission and company
                List<Contact> lMatchingContacts = [ SELECT      Id, LastName, FirstName, AccountId, Email, Phone
                                                    FROM        Contact
                                                    WHERE(      LastName  = :entreprise.Nom_Signataire_Convention__c
                                                            AND FirstName = :entreprise.Prenom_Signataire_Convention__c
                                                            AND AccountId = :demande.Convsta_Entreprise__c)
                                                    OR(         LastName  = :mission.Nom_Tuteur_Entreprise__c
                                                            AND FirstName = :mission.Prenom_Tuteur_Entreprise__c
                                                            AND AccountId = :demande.Convsta_Entreprise__c)];
                if(lMatchingContacts.size() > 0){
                    List<Contact> ctcList = new List<Contact>();
                    for(Contact ctc :lMatchingContacts){
                        //Responsable Administratif presence
                        if(     ctc.LastName    == entreprise.Nom_Signataire_Convention__c
                            &&  ctc.FirstName   == entreprise.Prenom_Signataire_Convention__c
                            &&  ctc.AccountId   == demande.Convsta_Entreprise__c)
                        {
                            ctc.Phone = entreprise.Telephone_Signataire_Convention__c;
                            ctc.Email = entreprise.Email_Signataire_Convention__c;
                            ctcList.add(ctc);

                            demande.Responsable_administratif_entreprise__c = ctc.Id;
                            updateDemandeBool= true;
                        }
                        
                        // Tuteur presence
                        if(     ctc.LastName    == mission.Nom_Tuteur_Entreprise__c
                            &&  ctc.FirstName   == mission.Prenom_Tuteur_Entreprise__c
                            &&  ctc.AccountId   == demande.Convsta_Entreprise__c)
                        {
                            ctc.Phone = mission.Telephone_Tuteur_Entreprise__c;
                            ctc.Email = mission.Email_Tuteur_Entreprise__c;
                            ctcList.add(ctc);

                            demande.Convsta_Tuteur__c = ctc.Id;
                            updateDemandeBool= true;
                        }
                    }
                    if(ctcList.size()>0){
                        update ctcList;
                    }
                }
            }

            if(updateDemandeBool){
                update demande;
            }
            
            return demande;
        }catch(Exception e){
            
            demande.Convsta_eSign_Errors__c += 'Erreur lors de la méthode checkMatchingAccountAndContact :\r\n';
            demande.Convsta_eSign_Errors__c += 'Numéro de la ligne en erreur : ' + e.getLineNumber() + '\r\n';
            demande.Convsta_eSign_Errors__c += 'Message de l\'erreur : ' + e.getMessage() + '\r\n';
            demande.Convsta_eSign_Errors__c += 'Trace de l\'erreur : ' + e.getStackTraceString() + '\r\n';
            demande.Convsta_eSign_Errors__c += 'Type de l\'erreur : ' + e.getTypeName() + '\r\n';
            demande.Convsta_eSign_Errors__c += 'Cause de l\'erreur : ' + e.getCause();
            system.debug(demande.Convsta_eSign_Errors__c);
            update demande;

            return demande;
        }        
    }

    public static void setIsSoumisEtudiant(List<SObject> triggerNew) {
        if(UserInfo.getUserType()!='Standard'){
            for(SObject obj:triggerNew){
                obj.put('is_soumis_etudiant__c',true);
            }
        }
    }

    @AuraEnabled
    public static void caseSetDocumentAVerifier(Id caseId, String typeDocument) { 
        System.debug('typeDocument : '+typeDocument);
        update new Case(Id=caseId, Convsta_Document_a_verifier__c=true, Convsta_Type_de_document__c=typeDocument);
    }

    public static void handleTrigger(List<SObject> triggerNew, Boolean isUpdate, Boolean isBefore){
        if(isUpdate && isBefore){
            setIsSoumisEtudiant(triggerNew);
        }
    }

    @AuraEnabled
    public static void evalSetEvaluee(Id evalId) { 
        update new Convsta_Evaluation__c(Id=evalId, Statut__c='Évaluée', Date_Reception_Evalutation__c= dateTime.now());
    }
    private static Group internalCareerCenterQueue = null;
    public static Group getCareerCenterQueue(){
        if(internalCareerCenterQueue == null){
        	internalCareerCenterQueue =   [SELECT Id
                       FROM Group WHERE 
                       DeveloperName = 'Convsta_En_attente_de_validation_admin'];
        }
        return internalCareerCenterQueue;
    }
       @AuraEnabled
    public static void shareFileToCommunity(Id caseId, Id documentId){
        Case demande = [SELECT Id FROM Case WHERE Id =:caseId LIMIT 1];
        demande.Status ='Convention signée';
        demande.Convsta_Statut_Signature__c ='Signée';
        demande.Date_Reception_Convention__c =Datetime.now();
        update demande;

        ContentDocumentLink cdl = [SELECT Id,LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId =:documentId AND LinkedEntityId =:caseId LIMIT 1];
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        update cdl;
    }
    public static String mapFonctionContact(String inFonctionString){
        string outFonctionCodeeString ='';
        switch on inFonctionString {
            when 'Commercial/Ventes' {
                outFonctionCodeeString = 'Conseil Commercial/Ventes';
            }
            when 'Direction Générale' {
                outFonctionCodeeString = 'Directeur ou Conseil en Stratégie';
            }
            when 'Enseignement/Education' {
                outFonctionCodeeString = 'Professeur';
            }
            when 'Etud/Recherche/Dévelop/Qualité' {
                outFonctionCodeeString = 'Conseil Etudes/Recherche';
            }
            when 'Finance/Gest./Adminis./Juridi.' {
                outFonctionCodeeString = 'Consultant Finance/Gestion/Audit';
            }
            when 'Marketing/Communication' {
                outFonctionCodeeString = 'Conseil en Marketing';
            }
            when 'Organisation/Systèmes d’Informations' {
                outFonctionCodeeString = 'Conseil Organis./SI';
            }
            when 'Production/Achats' {
                outFonctionCodeeString = 'Responsable des Achats';
            }
            when 'Ressources Humaines/Formation' {
                outFonctionCodeeString = 'Conseil en Ress. Humaines/ Outplacement';
            }
        }
        return outFonctionCodeeString;
    }

    @AuraEnabled
    public static void updateEvaluationDocumentId(Id evalId, Id evalDocumentId) { 
        Convsta_Evaluation__c eval = [SELECT Id, Demande__c 
                                        FROM Convsta_Evaluation__c
                                        WHERE Id= :evalId];
        Case demande = [SELECT Id, Convsta_EvaluationDocumentId__c
                        FROM Case
                        WHERE Id = :eval.Demande__c];
        demande.Convsta_EvaluationDocumentId__c = evalDocumentId;
        update demande;
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId =evalDocumentId , 
            LinkedEntityId =demande.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
            );
        insert cdl;
    }
    @AuraEnabled
    public static void uploadAvenant(Id avenantId, Id avenantcontentDocumentId){
        try {
        Case demande = [SELECT Id,ParentId
                        FROM   Case 
                        WHERE  Id = :avenantId LIMIT 1];
        
        List<ContentDocumentLink> listCl = new List<ContentDocumentLink>();
        insert new ContentDocumentLink(LinkedEntityId = demande.ParentId, ContentDocumentId = avenantcontentDocumentId, ShareType = 'I', Visibility='AllUsers');
        demande.Status ='Avenant signé';
        demande.Convsta_Statut_Signature__c = 'Signée';
        demande.Convsta_Convention__c = true;
        demande.Date_Reception_Convention__c = Datetime.now();
        update demande; 
        
        ContentDocumentLink avenantCdl =[Select id from ContentDocumentLink Where LinkedEntityId = :avenantId AND ContentDocumentId = :avenantcontentDocumentId LIMIT 1];
        avenantCdl.ShareType = 'I';
        avenantCdl.Visibility='AllUsers';
        update avenantCdl;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}