force-app/main/default/objects/Account/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse courante: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <formula>CodeAPE__r.CODE_APE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code NAF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeAPE__c.field-meta.xml
<CustomField>
    <fullName>CodeAPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAF</label>
    <referenceTo>NAF__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse courante: Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateEnd__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation liée</label>
    <referenceTo>Convsta_Evaluation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Mon_evaluation__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Mon_evaluation__c</fullName>
    <formula>IF( Convsta_Boolean_Evaluation__c,
			IF(NOT(ISBLANK(Convsta_EvaluationDocumentId__c)),
			HYPERLINK(&apos;/internships/sfc/servlet.shepherd/document/download/&apos;+Convsta_EvaluationDocumentId__c  +&apos;?operationContext=S1&apos;, $Label.convsta_dowload_evaluation, &apos;_blank&apos;),
			HYPERLINK(&apos;/internships/s/convsta-evaluation/&apos;+Convsta_Evaluation__c, $Label.convsta_dowload_evaluation, &apos;_blank&apos;)),$Label.convsta_pas_disponible )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mon évaluation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convsta_Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Table_des_Regles_Experience_Pro__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Table_des_Regles_Experience_Pro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Table des Règles Expérience Pro</label>
    <referenceTo>CONVSTA_Table_Regles_Experience_Pro__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Tuteur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Tuteur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tuteur entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <label>Programme</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect Etudiant</fullName>
            </value>
            <value>
                <fullName>Etudiant</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Cle_cryptee__c.field-meta.xml
<CustomField>
    <fullName>Cle_cryptee__c</fullName>
    <label>Clé cryptée</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/DateEndStage__c.field-meta.xml
<CustomField>
    <fullName>DateEndStage__c</fullName>
    <description>Date de la fin du stage</description>
    <label>Date de fin de stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Demande__c.field-meta.xml
<CustomField>
    <fullName>Demande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Convsta_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Etudiant__c.field-meta.xml
<CustomField>
    <fullName>Etudiant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Etudiant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Convsta_Evaluation_Etudiant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Evaluateur__c.field-meta.xml
<CustomField>
    <fullName>Evaluateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluateur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Convsta_Evaluation_Evaluateur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Lien_pour_evaluation__c.field-meta.xml
<CustomField>
    <fullName>Lien_pour_evaluation__c</fullName>
    <formula>HYPERLINK(
 evalLink__c , &quot;Consulter la page d&apos;évaluation&quot;	)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lien pour évaluation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Envoyée</fullName>
            </value>
            <value>
                <fullName>En attente d&apos;évaluation</fullName>
            </value>
            <value>
                <fullName>Relancée</fullName>
            </value>
            <value>
                <fullName>Évaluée</fullName>
            </value>
            <value>
                <fullName>Non-évaluable</fullName>
            </value>
            <value>
                <fullName>Expirée</fullName>
            </value>
            <value>
                <fullName>Evaluation manuelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/Convsta_Mission__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à la mission que l&apos;étudiant effectuera en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Convsta Mission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Mission__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/fields/Titre_Mission__c.field-meta.xml
<CustomField>
    <fullName>Titre_Mission__c</fullName>
    <description>Le titre de la mission de l&apos;étudiant dans l&apos;entreprise</description>
    <inlineHelpText>Titre de la mission de l&apos;étudiant dans l&apos;entreprise (maximum 70 caractères)</inlineHelpText>
    <label>Titre de la Mission</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <description>Le programme d&apos;étude de l&apos;étudiant, dans le cadre duquel il effectue son expérience professionnelle</description>
    <label>Programme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BBAB</fullName>
            </value>
            <value>
                <fullName>BBAC</fullName>
            </value>
            <value>
                <fullName>BBAP</fullName>
            </value>
            <value>
                <fullName>BBAS</fullName>
            </value>
            <value>
                <fullName>BBASP</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BOOS</fullName>
            </value>
            <value>
                <fullName>BWGE</fullName>
            </value>
            <value>
                <fullName>CDM</fullName>
            </value>
            <value>
                <fullName>CFT</fullName>
            </value>
            <value>
                <fullName>COSM</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>DBAL</fullName>
            </value>
            <value>
                <fullName>DIBO</fullName>
            </value>
            <value>
                <fullName>DMDS</fullName>
            </value>
            <value>
                <fullName>E2BA</fullName>
            </value>
            <value>
                <fullName>E2MS</fullName>
            </value>
            <value>
                <fullName>EMM</fullName>
            </value>
            <value>
                <fullName>ENVI</fullName>
            </value>
            <value>
                <fullName>ESC</fullName>
            </value>
            <value>
                <fullName>ETD</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>GEP</fullName>
            </value>
            <value>
                <fullName>GIE</fullName>
            </value>
            <value>
                <fullName>GLUX</fullName>
            </value>
            <value>
                <fullName>GMST</fullName>
            </value>
            <value>
                <fullName>HEBM</fullName>
            </value>
            <value>
                <fullName>HMDI</fullName>
            </value>
            <value>
                <fullName>IDEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAF__c/NAF__c.object-meta.xml
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pays__c/Pays__c.object-meta.xml
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Convsta_Internship.cls
/*-------------------------------------------------------------------
-- - Purpose            : Used to search internship
--
-- - Maintenance History:
--
-- Date        Name  Company     Version  Remarks
-- ----------  ----  ----------- -------  ----------------------------
-- 17/06/2019  T.CH  MODIS      1.0      Creation
--------------------------------------------------------------------*/
public without sharing class Convsta_Internship {
    @InvocableMethod
    public static void sendNewLink(List<Id> lEvalIds){
        Convsta_Evaluation__c evaluation = [SELECT Id, 
                                            Evaluateur__r.Email,
                                            Etudiant__r.Name,
                                            Lien_pour_evaluation__c 
                                            FROM Convsta_Evaluation__c WHERE ID =:lEvalIds[0] LIMIT 1];
        system.debug(evaluation); 
        
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {evaluation.Evaluateur__r.Email};
            mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('emlyon business school');
        mail.setSubject('Votre nouveau lien d\'évaluation de ' + evaluation.Etudiant__r.Name);
        mail.setHtmlBody('Bonjour,<br>Voici votre nouveau lien afin d\'évaluer l\'étudiant <b>' + evaluation.Etudiant__r.Name + '</b> :' + evaluation.Lien_pour_evaluation__c );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public static void createEval(List<Case> lCasesToEval){ //tested by BatchSchedule_CreateEval
        List<Convsta_Evaluation__c> lEvalsToCreate = new List<Convsta_Evaluation__c>();
        set<Id> studentIdSet = new set<Id>();
        for(Case demande :lCasesToEval){
            Convsta_Evaluation__c eval = new Convsta_Evaluation__c();
            Group queueCareerCenter = Convsta_Object_Helper.getCareerCenterQueue();
            eval.OwnerId 			= queueCareerCenter.Id;
            eval.Cle_cryptee__c 	= EncodingUtil.base64Encode(Crypto.generateDigest('SHA-512', Blob.valueOf(demande.caseNumber+String.valueOf(DateTime.now()))))
                						.replace('+','')
                						.replace('=','')
                						.replace('/','');
            eval.DateEndStage__c	= demande.Convsta_DateEnd__c;
            eval.Demande__c			= demande.Id;
            eval.Name		 		= 'Eval '+ demande.caseNumber+ ' '+ demande.Contact.Name;
            eval.Etudiant__c = 		demande.Contact.Id;
            studentIdSet.add(demande.Contact.Id);
            eval.Evaluateur__c = 	demande.Convsta_Tuteur__c;
            eval.Responsable_Pedagogique__c = demande.Convsta_Responsable_Pedagogique__c;
            eval.Statut__c = 		'En attente d\'évaluation';
            eval.ValidFrom__c = 	demande.Convsta_DateEnd__c.addDays(-22);
            eval.ValidTo__c = 		demande.Convsta_DateEnd__c.addDays(14);
            lEvalsToCreate.add(eval);
        }
        if(lEvalsToCreate.size()>0){
            database.insert( lEvalsToCreate,false);
            
            List<Case> lCasesToUpdate = new List<Case>();
            List<Convsta_Evaluation__Share> lEvalSharesToInsert = new List<Convsta_Evaluation__Share>();
            
            for(Convsta_Evaluation__c eval :lEvalsToCreate){
                Case demande = new Case(Id= eval.Demande__c, Convsta_Evaluation__c=eval.Id);                            
                lCasesToUpdate.add(demande);
                if(eval.Responsable_Pedagogique__c!=null){
                    lEvalSharesToInsert.add(shareEvalWithRespPeda(eval));
                }
            }
            update lCasesToUpdate;
            database.insert( lEvalSharesToInsert,false);
        }
    }
    
    public static Convsta_Evaluation__Share shareEvalWithRespPeda(Convsta_Evaluation__c eval){
        Convsta_Evaluation__Share evalShr  = new Convsta_Evaluation__Share();
        
        evalShr.ParentId = eval.Id;
        evalShr.UserOrGroupId = eval.Responsable_Pedagogique__c;
        evalShr.AccessLevel = 'Read';
        evalShr.RowCause = Schema.Convsta_Evaluation__Share.RowCause.Manual;
        
        return evalShr;
    }    
    
    @AuraEnabled
    public static String isEvaluee(Id demandeId){
        Convsta_Evaluation__c eval = [SELECT Id, Statut__c, Lien_pour_evaluation__c 
                                      FROM Convsta_Evaluation__c 
                                      WHERE Demande__c = :demandeId 
                                      LIMIT 1];
        if(eval != null){
            if(eval.Statut__c == 'Évaluée'){
                system.debug('évaluée');
                return eval.Lien_pour_evaluation__c;
            }else{
                system.debug('pas évaluée');
                return '';
            }    
        }else{
            return '';
        }                
    }
    
    @AuraEnabled
    public static String getEvalDownloadLink(Id demandeId){
        Case demande = [SELECT Id, Convsta_Mon_evaluation__c 
                                      FROM Case 
                                      WHERE Id = :demandeId 
                                      LIMIT 1];
        if(demande != null){
            return demande.Convsta_Mon_evaluation__c; 
        }else{
            return '';
        }
    }
    
    public class SearchInput{
        @AuraEnabled
        public String country{get;set;}
        @AuraEnabled
        public String city{get;set;}
        @AuraEnabled
        public String programme{get;set;}
        @AuraEnabled
        public String naf{get;set;}
        @AuraEnabled
        public String companyName{get;set;}
        @AuraEnabled
        public String title{get;set;}
    }
    
    public class SearchOutput{
        @AuraEnabled
        public String companyName{get;set;}
        @AuraEnabled
        public String country{get;set;}
        @AuraEnabled
        public String city{get;set;}
        @AuraEnabled
        public String naf{get;set;}
        @AuraEnabled
        public String title{get;set;}
        @AuraEnabled
        public String startYear{get;set;}
        @AuraEnabled
        public String studentName{get;set;}
    }
    public class SearchReturn{
        @AuraEnabled
        public String state;
        @AuraEnabled
        public Integer size = 0;
        @AuraEnabled
        public List<SearchOutput> lOutputs = new List<SearchOutput>();
    }
    
    @AuraEnabled
    public static SearchReturn search(SearchInput input){
        SearchReturn resReturn = new SearchReturn();
        
        List<String> lCondition = new List<String>();
        if(!String.isBlank(input.country)){
            lCondition.add('MD_Demande__r.Convsta_Entreprise__r.CodePays__r.Name LIKE \'%' + input.country + '%\'');
        }
        if(!String.isBlank(input.city)){
            lCondition.add('MD_Demande__r.Convsta_Entreprise__r.Adresse_Ville__c LIKE \'%' + input.city + '%\'');
        }
        if(!String.isBlank(input.programme)){
            lCondition.add('MD_Demande__r.Convsta_Table_des_Regles_Experience_Pro__r.Programme__c = \''+ input.programme + '\'');
        }
        if(!String.isBlank(input.naf)){
            lCondition.add('MD_Demande__r.Convsta_Entreprise__r.Code_NAF__c = \'' + input.naf + '\'');
        }
        if(!String.isBlank(input.companyName)){
            lCondition.add('MD_Demande__r.Convsta_Entreprise__r.Name LIKE \'%' + input.companyName + '%\'');
        }
        if(!String.isBlank(input.title)){
            lCondition.add('Titre_Mission__c LIKE \'%' + input.title + '%\'');
        }
        
        if(lCondition.size()>0){
            String whereClause = String.join(lCondition, ' AND ') + ' ';
            String query =  'SELECT Id, '+
                'MD_Demande__r.Convsta_Entreprise__r.Name, '+
                'MD_Demande__r.Convsta_Entreprise__r.CodePays__r.Name, '+
                'MD_Demande__r.Convsta_Entreprise__r.Adresse_Ville__c, '+
                'MD_Demande__r.Convsta_Entreprise__r.CodeAPE__r.Name, '+
                'Titre_Mission__c, '+
                'MD_Demande__r.Convsta_DateStart__c, '+
                'MD_Demande__r.Contact.Name '+
                'FROM Convsta_Mission__c '+
                'WHERE '  + whereClause +
                'AND MD_Demande__r.Convsta_Type_de_demande__c = \'Stage\' '+
                'AND MD_Demande__r.Convsta_DateEnd__c < TODAY '+
                'LIMIT 100';
                    
            List<Convsta_Mission__c> lMissions = Database.query(query);
            
            System.debug('lMissions: '+lMissions);
            
            if(lMissions.size()>0){
                for(Convsta_Mission__c mission :lMissions){
                    SearchOutput output = new SearchOutput();            
                    output.companyName =    mission.MD_Demande__r.Convsta_Entreprise__r.Name;
                    output.country =        mission.MD_Demande__r.Convsta_Entreprise__r.CodePays__r.Name;
                    output.city =           mission.MD_Demande__r.Convsta_Entreprise__r.Adresse_Ville__c;
                    output.naf =            mission.MD_Demande__r.Convsta_Entreprise__r.CodeAPE__r.Name;
                    output.title =          mission.Titre_Mission__c;
                    output.startYear =      String.valueOf(mission.MD_Demande__r.Convsta_DateStart__c.year());
                    output.studentName =    mission.MD_Demande__r.Contact.Name;
                    
                    resReturn.state = 'OK';    
                    resReturn.lOutputs.add(output);
                    resReturn.size++;
                }
            }else{
                resReturn.state = 'NOK : No mission found';
                resReturn.size  = 0;
                resReturn.lOutputs = null;    
            }            
        }else{ 
            resReturn.state = 'NOK : No condition entered';
            resReturn.size  = 0;
            resReturn.lOutputs = null;
        }
        
        System.debug('resReturn ' + resReturn);
        return resReturn;
    }
    
    
}