force-app/main/default/objects/Account/fields/Adresse_Rue__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Rue__c</fullName>
    <label>Adresse courante: Rue</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse courante: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <formula>CodeAPE__r.CODE_APE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code NAF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Adresse courante: Code Postal</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeAPE__c.field-meta.xml
<CustomField>
    <fullName>CodeAPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAF</label>
    <referenceTo>NAF__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse courante: Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tranche_d_effectif__c.field-meta.xml
<CustomField>
    <fullName>Tranche_d_effectif__c</fullName>
    <label>Tranche d&apos;effectif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>De 0 à 9</fullName>
            </value>
            <value>
                <fullName>De 10 à 49</fullName>
            </value>
            <value>
                <fullName>De 50 à 249</fullName>
            </value>
            <value>
                <fullName>De 250 à 499</fullName>
            </value>
            <value>
                <fullName>De 500 à 999</fullName>
            </value>
            <value>
                <fullName>De 1000 à 1999</fullName>
            </value>
            <value>
                <fullName>De 2000 à 4999</fullName>
            </value>
            <value>
                <fullName>De 5000 à 9999</fullName>
            </value>
            <value>
                <fullName>10 000 et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Localisation_de_l_entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Localisation_de_l_entreprise__c</fullName>
    <label>Localisation de l&apos;entreprise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En France</fullName>
                <default>true</default>
                <label>En France</label>
            </value>
            <value>
                <fullName>A l&apos;étranger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Convsta_Validation_d_experience.recordType-meta.xml
<RecordType>
    <fullName>Convsta_Validation_d_experience</fullName>
    <active>true</active>
    <businessProcess>Convsta_Validation_Expérience</businessProcess>
    <label>Validation d&apos;expérience</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Convsta_Tuteur_EM__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Tuteur_EM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tuteur EM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse:Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Convsta_Entreprise__c/Convsta_Entreprise__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Entreprise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Convsta Entreprise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entreprises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Adresse_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Entreprise__c</fullName>
    <description>L&apos;adresse de l&apos;entreprise</description>
    <inlineHelpText>Adresse de l&apos;entreprise</inlineHelpText>
    <label>Adresse de l&apos;Entreprise</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/code_NAF__c.field-meta.xml
<CustomField>
    <fullName>code_NAF__c</fullName>
    <label>code NAF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <description>Le code postal de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Code postal de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</inlineHelpText>
    <label>Code Postal</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Guide_des_bonnes_pratiques__c.field-meta.xml
<CustomField>
    <fullName>Guide_des_bonnes_pratiques__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Je m&apos;engage à le respecter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entreprises</relationshipLabel>
    <relationshipName>Entreprise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Nom_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Nom_Entreprise__c</fullName>
    <description>Le nom de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</description>
    <inlineHelpText>Raison sociale de l&apos;entreprise dans laquelle l&apos;étudiant effectue son expérience professionnelle</inlineHelpText>
    <label>Nom de l&apos;Entreprise</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Pays2__c.field-meta.xml
<CustomField>
    <fullName>Pays2__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>pays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <description>Le numéro SIRET de l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Numéro SIRET de l&apos;entreprise signataire de la convention de stage.</inlineHelpText>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Tranche_effectif_etablissement__c.field-meta.xml
<CustomField>
    <fullName>Tranche_effectif_etablissement__c</fullName>
    <label>Tranche effectif etablissement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Entreprise__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <description>La ville où est située l&apos;entreprise au sein de laquelle l&apos;étudiant va effectuer son expérience professionnelle</description>
    <inlineHelpText>Localisation de l&apos;entreprise signataire de la convention.</inlineHelpText>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Evaluation__c/Convsta_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Informations d&apos;une évaluation concernant un stage</description>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Evaluation__c/fields/Demande__c.field-meta.xml
<CustomField>
    <fullName>Demande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Convsta_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convsta_Mission__c/Convsta_Mission__c.object-meta.xml
<CustomObject>
    <description>Informations relatives à la mission que l&apos;étudiant effectuera en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Convsta Mission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Mission__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NAF__c/NAF__c.object-meta.xml
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAF__c/fields/CODE_APE__c.field-meta.xml
<CustomField>
    <fullName>CODE_APE__c</fullName>
    <externalId>true</externalId>
    <label>CODE APE</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pays__c/Pays__c.object-meta.xml
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pays__c/fields/Code_Pays_2_caracteres__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays_2_caracteres__c</fullName>
    <label>Code Pays 2 caractères</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/pays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>pays</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/Convsta_Object_HelperTest.cls
@isTest()
private class Convsta_Object_HelperTest {
    @testSetup
    static void setup(){
        Pays__c frenchCountry =                    TestObjectFactory.createPays();
        frenchCountry.Name =                       'France';
        frenchCountry.Code_Pays_2_caracteres__c =  'FR';
        insert frenchCountry;
        NAF__c naf =        TestObjectFactory.createNaf();
        naf.CODE_APE__c =   'TestNaf';
        insert naf;
        Account accFr = TestObjectFactory.createAccount(frenchCountry, naf);
        accFr.Name =                    'TestNameFR';
        accFr.SIRET__c =                '35315026100330';
        accFr.Adresse_Rue__c =          'TestAddress';
        accFr.Code_Postal__c =          '69000';
        accFr.Adresse_Ville__c =        'TestCity';
        accFr.Tranche_d_effectif__c =   '10 000 et plus';
        insert accFr;
        
        Contact etudiant =      TestObjectFactory.createContact(accFr);
        etudiant.FirstName =    'Etudiant';
        etudiant.LastName =     'EM';
        etudiant.Email =        'testEtudiant@test.com';
        insert etudiant;

        Contact tuteurEM =              TestObjectFactory.createContact(accFr);
        tuteurEM.FirstName =            'Tuteur';
        tuteurEM.LastName =             'EM';
        tuteurEM.Email =                'testTuteurEM@test.com';
        tuteurEM.Convsta_Tuteur_EM__c = true;
        insert tuteurEM;

        Pays__c foreignCountry =                    TestObjectFactory.createPays();
        foreignCountry.Name =                       'Espagne';
        foreignCountry.Code_Pays_2_caracteres__c =  'ES';
        insert foreignCountry;
        Account foreignAcc =            TestDataFactory.getAccount();
        foreignAcc.Name =               'ForeignAcc';
        foreignAcc.CodePays__c =        foreignCountry.Id;
        foreignAcc.Adresse_Ville__c =   'Madrid'; 
        insert foreignAcc;

        Contact respAdmin =     TestObjectFactory.createContact(foreignAcc);
        respAdmin.FirstName =   'Responsable';
        respAdmin.LastName =    'ADMINISTRATIF';
        respAdmin.Email=        'testRespAdmin@test.com';
        insert respAdmin;

        Contact tuteurEntreprise =      TestObjectFactory.createContact(foreignAcc);
        tuteurEntreprise.FirstName =    'Tuteur';
        tuteurEntreprise.LastName =     'ENTREPRISE';
        tuteurEntreprise.Email=         'testTuteurEntreprise@test.com';
        insert tuteurEntreprise;
    }

	// method to test when a student add a company who already exists in SF database
    @isTest static void frenchCompanyTest(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;

        Account accFr = [SELECT Name, CodePays__r.Code_Pays_2_caracteres__c, CODEAPE__r.CODE_APE__c, SIRET__c
                         FROM Account
                         WHERE Name = 'TestNameFR'];
        
        Convsta_Entreprise__c entreprise = [SELECT  Id, Nom_Entreprise__c, Pays2__c, Ville__c, 
                                                    SIRET__c, Adresse_Entreprise__c, Code_Postal__c, Tranche_effectif_etablissement__c, Code_NAF__c
                                            FROM    Convsta_Entreprise__c
                                            WHERE   MD_Demande__c = :demande.Id];
        entreprise.SIRET__c =                           accFr.SIRET__c;
        entreprise.Nom_Entreprise__c =                  'NewTestName';
        entreprise.Adresse_Entreprise__c =              'NewTestAddress';
        entreprise.Pays2__c =                           accFr.CodePays__r.Code_Pays_2_caracteres__c;
        entreprise.Code_Postal__c =                     '69100';
        entreprise.Ville__c =                           'NewTestCity';
        entreprise.Tranche_effectif_etablissement__c =  '10 000 et plus';
        entreprise.Code_NAF__c =                        accFr.CODEAPE__r.CODE_APE__c;
        update entreprise;

        Test.startTest();
        Convsta_object_helper.checkMatchingAccountAndContact(demande.id);
        Test.stopTest();

        accFr = [SELECT Name, Adresse_Rue__c
                 FROM Account
                 WHERE Id = :accFr.Id];
        // because the account already exists we just update some informations but not the name
        System.assertEquals('TestNameFR', accFr.Name);
        System.assertEquals('NEWTESTADDRESS', accFr.Adresse_Rue__c.toUpperCase());
    }
    
    // method to test when a student add a company who doesn't already exists in SF database
    @isTest static void frenchOtherCompanyTest(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;

        Account accFr = [SELECT Name, CodePays__r.Code_Pays_2_caracteres__c, CODEAPE__r.CODE_APE__c, SIRET__c
                         FROM Account
                         WHERE Name = 'TestNameFR'];
        
        Convsta_Entreprise__c entreprise = [SELECT  Id, Nom_Entreprise__c, Pays2__c, Ville__c, 
                                                    SIRET__c, Adresse_Entreprise__c, Code_Postal__c, Tranche_effectif_etablissement__c, Code_NAF__c
                                            FROM    Convsta_Entreprise__c
                                            WHERE   MD_Demande__c = :demande.Id];
        entreprise.SIRET__c =                           '12345678200010';//accFr.SIRET__c;
        entreprise.Nom_Entreprise__c =                  'NewTestName';
        entreprise.Adresse_Entreprise__c =              'NewTestAddress';
        entreprise.Pays2__c =                           accFr.CodePays__r.Code_Pays_2_caracteres__c;
        entreprise.Code_Postal__c =                     '69100';
        entreprise.Ville__c =                           'NewTestCity';
        entreprise.Tranche_effectif_etablissement__c =  '10 000 et plus';
        entreprise.Code_NAF__c =                        accFr.CODEAPE__r.CODE_APE__c;
        update entreprise;

        Test.startTest();
        Convsta_object_helper.checkMatchingAccountAndContact(demande.id);
        Test.stopTest();

        accFr = [SELECT Name
                 FROM Account
                 WHERE Id = :accFr.Id];
                        
        /*Account newAcc = [SELECT Name
                 FROM Account
                 WHERE Id = :demande.Convsta_Entreprise__c];*/
        
        // because the account did not already exists now we have two Account in the database
        System.assertEquals('TestNameFR', accFr.Name);
        //System.assertEquals('NewTestName', newAcc.Name);
    }
    
    @isTest static void foreignCompanyTest(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            =   APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c =   'A l\'étranger';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole'; 
        insert demande;

        Convsta_Entreprise__c entreprise = [SELECT  Id, Nom_Entreprise__c, Pays2__c, Ville__c
                                            FROM    Convsta_Entreprise__c
                                            WHERE   MD_Demande__c = :demande.Id];
                                            
        entreprise.Nom_Entreprise__c =                  'ForeignAcc';
        entreprise.Pays2__c =                           'ES';
        entreprise.Ville__c =                           'Madrid';
        entreprise.Guide_des_bonnes_pratiques__c =		true;
        update entreprise;

        Test.startTest();
        Convsta_Object_Helper.checkMatchingAccountAndContact(demande.Id);
        Test.stopTest();

        demande =  [SELECT Id, Convsta_Entreprise__c
                    FROM Case
                    LIMIT 1];
        Account foreignAcc =   [SELECT Id
                                FROM Account
                                WHERE Name = 'ForeignAcc'];
                                
        System.assertEquals(foreignAcc.Id, demande.Convsta_Entreprise__c);
    }

    @isTest static void checkMatchingAccountAndContactTest(){
        String phone = '0000000000';
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;        
        
        Account foreignAcc = [SELECT Id, Name, CodePays__r.Code_Pays_2_caracteres__c, CODEAPE__r.CODE_APE__c, Adresse_Ville__c, SIRET__c
                              FROM Account
                              WHERE Name = 'ForeignAcc'];
        demande.Convsta_Entreprise__c = foreignAcc.Id;

        Convsta_Entreprise__c entreprise = [SELECT  Id, Prenom_Signataire_Convention__c, Nom_Signataire_Convention__c, 
                                                    Email_Signataire_Convention__c, Telephone_Signataire_Convention__c
                                            FROM    Convsta_Entreprise__c
                                            WHERE   MD_Demande__c = :demande.Id];
        entreprise.Nom_Entreprise__c =                  foreignAcc.Name;
        entreprise.Pays2__c  =                          foreignAcc.CodePays__r.Code_Pays_2_caracteres__c;
        entreprise.Code_NAF__c =                        foreignAcc.CODEAPE__r.CODE_APE__c;
        entreprise.Ville__c  =                          foreignAcc.Adresse_Ville__c;
        entreprise.SIRET__c =                           foreignAcc.SIRET__c;
        entreprise.Prenom_Signataire_Convention__c =    'Responsable';
        entreprise.Nom_Signataire_Convention__c =       'ADMINISTRATIF';
        entreprise.Email_Signataire_Convention__c =     'newtest@test.com';
        entreprise.Telephone_Signataire_Convention__c = phone;
        update entreprise;
                        
        Convsta_Mission__c mission = [  SELECT  Id, Prenom_Tuteur_Entreprise__c, Nom_Tuteur_Entreprise__c, 
                                                Email_Tuteur_Entreprise__c, Telephone_Tuteur_Entreprise__c
                                        FROM    Convsta_Mission__c
                                        WHERE   MD_Demande__c = :demande.Id];
        mission.Prenom_Tuteur_Entreprise__c =   'Tuteur';
        mission.Nom_Tuteur_Entreprise__c=       'ENTREPRISE';
        mission.Email_Tuteur_Entreprise__c =    'newtest@test.com';
        mission.Telephone_Tuteur_Entreprise__c= phone;
        update mission;

        Test.startTest();
        Convsta_object_helper.checkMatchingAccountAndContact(demande.Id);
        Test.stopTest();

        Contact existingTuteur =   [SELECT      Id, Email, Phone, CreatedDate
                                    FROM        Contact
                                    WHERE       FirstName = 'Tuteur'
                                    AND         LastName  = 'ENTREPRISE'
                                    ORDER BY    CreatedDate DESC];
        Contact existingResp =     [SELECT      Id, Email, Phone, CreatedDate
                                    FROM        Contact
                                    WHERE       FirstName = 'Responsable'
                                    ORDER BY    CreatedDate  DESC];
        demande =                  [SELECT      Id, Responsable_administratif_entreprise__c, Convsta_Tuteur__c
                                    FROM        Case
                                    WHERE       Id = :demande.Id];

        System.assertEquals(entreprise.Email_Signataire_Convention__c,      existingResp.Email);
        System.assertEquals(entreprise.Telephone_Signataire_Convention__c,  existingResp.Phone);
        System.assertEquals(existingResp.Id, demande.Responsable_administratif_entreprise__c);

        System.assertEquals(mission.Email_Tuteur_Entreprise__c,     existingTuteur.Email);
        System.assertEquals(mission.Telephone_Tuteur_Entreprise__c, existingTuteur.Phone);
        System.assertEquals(existingTuteur.Id, demande.Convsta_Tuteur__c);
    }

    @isTest
    static void shareFileToCommunity(){
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true; 

        Account acc = TestDataFactory.getAccount();
        Database.SaveResult sr = Database.insert(acc, dml);

        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];

        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId               = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c     = 'Convention de stage de l ecole';
        insert demande;

        ContentVersion contentVersion = new ContentVersion(
            Title = 'convention-00000000',
            PathOnClient = 'convention-00000000.pdf',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = demande.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'I';
        cdl.Visibility = 'InternalUsers';
        insert cdl;

        Test.startTest();
        Convsta_Object_Helper.shareFileToCommunity(demande.Id, documents[0].Id);
        Test.stopTest();

        demande = [SELECT Status, Convsta_Statut_Signature__c, Date_Reception_Convention__c FROM Case WHERE Id =:demande.Id];
        System.assertEquals(demande.Status, 'Convention signée');
        System.assertEquals(demande.Convsta_Statut_Signature__c, 'Signée');

        cdl = [SELECT ShareType, Visibility FROM ContentDocumentLink WHERE ContentDocumentId =:documents[0].Id AND LinkedEntityId =:demande.id];
        System.assertEquals(cdl.ShareType, 'V');
        System.assertEquals(cdl.Visibility, 'AllUsers');
    }
    @isTest
    static void testMappingFonction (){
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Commercial/Ventes'), 'Conseil Commercial/Ventes');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Direction Générale'), 'Directeur ou Conseil en Stratégie');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Enseignement/Education'), 'Professeur');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Etud/Recherche/Dévelop/Qualité'), 'Conseil Etudes/Recherche');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Finance/Gest./Adminis./Juridi.'), 'Consultant Finance/Gestion/Audit');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Marketing/Communication'), 'Conseil en Marketing');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Organisation/Systèmes d’Informations'), 'Conseil Organis./SI');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Production/Achats'), 'Responsable des Achats');
        system.assertEquals(Convsta_Object_Helper.mapFonctionContact('Ressources Humaines/Formation'), 'Conseil en Ress. Humaines/ Outplacement');
    }
    @isTest
    static void testUpdateEvalDocId(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];
        
        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;
        
        Convsta_Evaluation__c evaluation = TestObjectFactory.createEvaluation() ;
        evaluation.demande__c = demande.Id ;
        insert evaluation ;
        
        Test.startTest();
        ContentVersion contentVersion = new ContentVersion(
            Title = 'convention-00000000',
            PathOnClient = 'convention-00000000.pdf',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        Convsta_Object_Helper.updateEvaluationDocumentId(evaluation.id, documents[0].Id);
        Test.stopTest();
        
        Case res = [SELECT Id, Convsta_EvaluationDocumentId__c FROM Case WHERE Id =: demande.id];
        System.assertEquals(documents[0].Id, res.Convsta_EvaluationDocumentId__c);
    }
    
    @isTest
    static void testEvalueeEvalId(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];
        
        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;
        
        Convsta_Evaluation__c evaluation = TestObjectFactory.createEvaluation() ;
        evaluation.demande__c = demande.Id ;
        insert evaluation ;
        
        Test.startTest();
        Convsta_Object_Helper.getCareerCenterQueue();
        Convsta_Object_Helper.evalSetEvaluee(evaluation.id);
        Test.stopTest();
        
        Convsta_Evaluation__c res = [SELECT Id, Statut__c FROM Convsta_Evaluation__c WHERE Id =: evaluation.id];
        System.assertEquals('Évaluée', res.Statut__c);
    }
    @isTest
    static void testDocAVerifier(){
        Contact etudiant = [SELECT Id
                            FROM Contact
                            WHERE FirstName = 'Etudiant'];
        
        Case demande = TestObjectFactory.createCase(etudiant);
        demande.RecordTypeId                            = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience');
        demande.Convsta_Localisation_de_l_entreprise__c = 'En France';
        demande.Convsta_Type_de_demande__c = 'Stage';
        demande.Convsta_TypeContrat__c  = 'Convention de stage de l ecole';
        insert demande;
        
        Test.startTest();
        Convsta_Object_Helper.caseSetDocumentAVerifier(demande.id, 'Autre');
        Test.stopTest();
        
        Case res = [SELECT Id, Convsta_Document_a_verifier__c, Convsta_Type_de_document__c FROM Case WHERE Id =: demande.id];
        System.assertEquals(true, res.Convsta_Document_a_verifier__c);
        System.assertEquals('Autre', res.Convsta_Type_de_document__c);
    }
}