force-app/main/default/objects/Account/fields/Adresse_Rue__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Rue__c</fullName>
    <label>Adresse courante: Rue</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse courante: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Adresse courante: Code Postal</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adresse courante: Pays</label>
    <referenceTo>Pays__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_FEG__c.field-meta.xml
<CustomField>
    <fullName>ID_FEG__c</fullName>
    <externalId>true</externalId>
    <label>ID FEG</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Adresse_du_lieu_du_stage__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Adresse_du_lieu_du_stage__c</fullName>
    <label>Adresse du lieu du stage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateEnd__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Entreprise__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Langue__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Langue__c</fullName>
    <label>Langue de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Français</fullName>
            </value>
            <value>
                <fullName>Anglais</fullName>
            </value>
            <value>
                <fullName>Espagnol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Nouvelle_adresse_lieu_de_stage__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Nouvelle_adresse_lieu_de_stage__c</fullName>
    <label>Nouvelle adresse du lieu de stage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Responsable_Pedagogique__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Responsable_Pedagogique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Pédagogique</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Convsta_Responsables_Pedagogiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Tuteur__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Tuteur__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tuteur entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Reception_Convention__c.field-meta.xml
<CustomField>
    <fullName>Date_Reception_Convention__c</fullName>
    <inlineHelpText>La date à laquelle la convention de l&apos;étudiant envoyée par l&apos;entreprise a été reçue par l&apos;emlyon</inlineHelpText>
    <label>Réception de la Convention</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsable_administratif_entreprise__c.field-meta.xml
<CustomField>
    <fullName>Responsable_administratif_entreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable administratif entreprise</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Responsable administratif entreprise)</relationshipLabel>
    <relationshipName>convsta_stages_responsable_entreprise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Adresse_Ville__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Ville__c</fullName>
    <label>Adresse: Ville</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/convsta_code_etudiant_EM__c.field-meta.xml
<CustomField>
    <fullName>convsta_code_etudiant_EM__c</fullName>
    <externalId>true</externalId>
    <label>code étudiant</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Professionnel__c.field-meta.xml
<CustomField>
    <fullName>Email_Professionnel__c</fullName>
    <label>Email Professionnel(ne pas utiliser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Fonctions__c.field-meta.xml
<CustomField>
    <fullName>Fonctions__c</fullName>
    <label>Fonction codée</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille_Fonction__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Président(e)</fullName>
            </value>
            <value>
                <fullName>Administrateur</fullName>
            </value>
            <value>
                <fullName>Vice-Président</fullName>
            </value>
            <value>
                <fullName>Président du Directoire</fullName>
            </value>
            <value>
                <fullName>Conseiller du Président</fullName>
            </value>
            <value>
                <fullName>Président Directeur Général</fullName>
            </value>
            <value>
                <fullName>Directeur Général</fullName>
            </value>
            <value>
                <fullName>Directeur Général Adjoint</fullName>
            </value>
            <value>
                <fullName>Secrétaire Général</fullName>
            </value>
            <value>
                <fullName>Directeur du Développement</fullName>
            </value>
            <value>
                <fullName>Directeur Affaires Internationales</fullName>
            </value>
            <value>
                <fullName>Fondé de Pouvoir</fullName>
            </value>
            <value>
                <fullName>Dir. des Compensations Internationales</fullName>
            </value>
            <value>
                <fullName>Directeur</fullName>
            </value>
            <value>
                <fullName>Directeur Adjoint</fullName>
            </value>
            <value>
                <fullName>Attaché de Direction</fullName>
            </value>
            <value>
                <fullName>Directeur de Filiale</fullName>
            </value>
            <value>
                <fullName>Directeur et Responsable d&apos;Etablissement</fullName>
            </value>
            <value>
                <fullName>Associé</fullName>
            </value>
            <value>
                <fullName>Gérant(e)</fullName>
            </value>
            <value>
                <fullName>Directeur d&apos;Agence</fullName>
            </value>
            <value>
                <fullName>Conseil Auprès de la DG</fullName>
            </value>
            <value>
                <fullName>Directeur ou Conseil en Stratégie</fullName>
            </value>
            <value>
                <fullName>Chargé de Mission</fullName>
            </value>
            <value>
                <fullName>Directeur Technique</fullName>
            </value>
            <value>
                <fullName>Responsable Technique</fullName>
            </value>
            <value>
                <fullName>Cadre Technique</fullName>
            </value>
            <value>
                <fullName>Personnel Technique</fullName>
            </value>
            <value>
                <fullName>Cadre Logistique</fullName>
            </value>
            <value>
                <fullName>Directeur de Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_FEG__c.field-meta.xml
<CustomField>
    <fullName>ID_FEG__c</fullName>
    <externalId>true</externalId>
    <label>ID FEG</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendConvstaDemandeToCursus.cls
public with sharing class SendConvstaDemandeToCursus implements Queueable, Database.AllowsCallouts {
  private List<Case> convstaDemandes;

  public SendConvstaDemandeToCursus(List<Case> demandes) {
    this.convstaDemandes = demandes;
  }
  public SendConvstaDemandeToCursus(Set<Id> caseIds) {
    this.convstaDemandes = [
      SELECT
        Id,
        Convsta_DateStart__c,
        Convsta_DateEnd__c,
        Convsta_Type_de_demande__c,
        Convsta_TypeContrat__c,
        Origin,
        Convsta_Adresse_du_lieu_du_stage__c,
        Convsta_Nouvelle_adresse_lieu_de_stage__c,
        Convsta_Langue__c,
        Date_Reception_Convention__c,
        Convsta_Entreprise__r.Name,
        Convsta_Entreprise__r.ID_FEG__c,
        Convsta_Entreprise__r.Code_Postal__c,
        Convsta_Entreprise__r.Adresse_Ville__c,
        Convsta_Entreprise__r.CodePays__c,
        Convsta_Entreprise__r.Adresse_Rue__c,
        Responsable_administratif_entreprise__r.Name,
        Responsable_administratif_entreprise__r.FirstName,
        Responsable_administratif_entreprise__r.LastName,
        Responsable_administratif_entreprise__r.Fonctions__c,
        Convsta_Responsable_Pedagogique__r.FirstName,
        Convsta_Responsable_Pedagogique__r.LastName,
        Convsta_Responsable_Pedagogique__r.Email,
        Convsta_Tuteur__r.FirstName,
        Convsta_Tuteur__r.LastName,
        Convsta_Tuteur__r.Fonctions__c,
        Convsta_Tuteur__r.Salutation,
        Convsta_Tuteur__r.Email_Professionnel__c,
        Contact.convsta_code_etudiant_EM__c
      FROM Case
      WHERE Id IN :caseIds
    ];
  }

  public void execute(QueueableContext context) {
    System.debug('>>> SendConvstaDemandeToCursus Queueable Execute START');

    Case convstaDemande = convstaDemandes.remove(0);
    System.debug('convstaDemande : ' + convstaDemande);
    // check phase exists
    OASElevesApi.getPhaseReturn wsReturn = Convsta_WS_Helper_Cursus.wsGetCodePhase(
      convstaDemande.Contact.convsta_code_etudiant_EM__c,
      convstaDemande.Convsta_DateStart__c,
      convstaDemande.Convsta_DateEnd__c
    );
    if (wsReturn.success) {
      // check si data ok
      String resCheckDataStr = Convsta_WS_Helper_Cursus.checkStrictTotalData(
        convstaDemande
      );
      Convsta_WS_Helper_Cursus.checkStrictTotalDataStructure resCheckData = (Convsta_WS_Helper_Cursus.checkStrictTotalDataStructure) JSON.deserialize(
        resCheckDataStr,
        Convsta_WS_Helper_Cursus.checkStrictTotalDataStructure.class
      );

      System.debug('resCheckData : ' + resCheckData);
      if (resCheckData.allDataOK != null) {
        Convsta_WS_Helper_Cursus.wsPostPhase(convstaDemande, wsReturn.codePhase);
      }
    }

    if (convstaDemandes.size() != 0) {
      System.enqueueJob(new SendConvstaDemandeToCursus(convstaDemandes));
    }
  }
}