force-app/main/default/objects/Account/fields/Convsta_roll_max_date_de_stage__c.field-meta.xml
<CustomField>
    <fullName>Convsta_roll_max_date_de_stage__c</fullName>
    <label>Date du dernier stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_DateStart__c.field-meta.xml
<CustomField>
    <fullName>Convsta_DateStart__c</fullName>
    <label>Date de démarrage du stage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_Type_de_demande__c.field-meta.xml
<CustomField>
    <fullName>Convsta_Type_de_demande__c</fullName>
    <label>Type de demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validation_experience_anterieure</fullName>
                <label>Validation d&apos;expérience antérieure</label>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Contrat à venir</fullName>
                <label>Contrat à venir (CDI/CDD/Intérim)</label>
            </value>
            <value>
                <fullName>Besoin d&apos;aide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Convsta_TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>Convsta_TypeContrat__c</fullName>
    <label>Type Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Convsta_Type_de_demande__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Convention de stage de l ecole</fullName>
                <label>Convention de stage émise par emlyon business school</label>
            </value>
            <value>
                <fullName>Contrat de travail de l&apos;entreprise</fullName>
                <label>Contrat de travail de l&apos;entreprise (CDD/Intérim)</label>
            </value>
            <value>
                <fullName>VIE</fullName>
                <label>VIE/VIA</label>
            </value>
            <value>
                <fullName>Convention_de_stage</fullName>
                <label>Convention de stage</label>
            </value>
            <value>
                <fullName>Service_civique</fullName>
                <label>Service civique</label>
            </value>
            <value>
                <fullName>Auto_entrepreneur</fullName>
                <label>Auto-entrepreneur/ Création d&apos;entreprise</label>
            </value>
            <value>
                <fullName>Convention de stage de l&apos;entreprise</fullName>
                <label>Convention de stage émise par l&apos;entreprise</label>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
                <isActive>false</isActive>
                <label>Alternance</label>
            </value>
            <value>
                <fullName>Contrat local a l etranger</fullName>
                <isActive>false</isActive>
                <label>Contrat local a l etranger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Convsta_Validation_d_experience.recordType-meta.xml
<RecordType>
    <fullName>Convsta_Validation_d_experience</fullName>
    <active>true</active>
    <businessProcess>Convsta_Validation_Expérience</businessProcess>
    <label>Validation d&apos;expérience</label>
</RecordType>

force-app/main/default/classes/BatchAndScheduleRollMaxDateDeStageTest.cls
@isTest private class BatchAndScheduleRollMaxDateDeStageTest {
    @testSetup
    static void setup(){
        Account acc1 = TestDataFactory.getAccount();
        acc1.Name = 'Account 1';
        insert acc1;

        Contact ctc = TestObjectFactory.createContact(acc1);
        insert ctc;
        Case case1_older = new Case(Subject = 'Older case 1', 
                                    AccountId = acc1.Id, 
                                    recordTypeId    = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience'),
                                    Convsta_DateStart__c = Date.newInstance(2000, 01, 13),
                                    Type = 'Expérience professionnelle',
                                    Status = 'Expérience validée',
                                    Convsta_Type_de_demande__c = 'Stage',
                                    Convsta_TypeContrat__c  = 'Convention de stage de l ecole',
                                    contactid= ctc.id);
        insert case1_older;

        Case case1_last = new Case(Subject = 'Last case 1', 
                                   recordTypeId    = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience'),
                                   AccountId = acc1.Id, 
                                   Convsta_DateStart__c = Date.newInstance(2000, 01, 14),
                                    Type = 'Expérience professionnelle',
                                    Status = 'Expérience validée',
                                   Convsta_Type_de_demande__c = 'Stage',
                                   Convsta_TypeContrat__c  = 'Convention de stage de l ecole',
                                   contactid= ctc.id);
        insert case1_last;
        case1_last.Subject = 'Last case 1';
        update case1_last;


        Account acc2 = TestDataFactory.getAccount();
        acc2.Name = 'Account 2';
        insert acc2;

        Case case2_older = new Case(Subject = 'Older case 2', 
                                    AccountId = acc2.Id, 
                                    Convsta_DateStart__c = Date.newInstance(2000, 01, 13),
                                    Type = 'Expérience professionnelle',
                                    Status = 'Expérience validée',
                                   Convsta_Type_de_demande__c = 'Stage',
                                   Convsta_TypeContrat__c  = 'Convention de stage de l ecole',
                                    recordTypeId = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience'),
                                    contactid= ctc.id);
        insert case2_older;

        Case case2_last = new Case(Subject = 'Last case 2', 
                                    AccountId = acc2.Id, 
                                    Convsta_DateStart__c = Date.newInstance(2000, 01, 14),
                                    Type = 'Expérience professionnelle',
                                    Status = 'Expérience validée',
                                   Convsta_Type_de_demande__c = 'Stage',
                                   Convsta_TypeContrat__c  = 'Convention de stage de l ecole',
                                    recordTypeId = APU_ApexUtils.getCaseRecordTypeIdByDeveloperName('Convsta_Validation_d_experience'),
                                    contactid= ctc.id);
        insert case2_last;
        case2_last.Subject = 'Last case 2';
        update case2_last;

    }

    @isTest static void testBatch(){
        Test.startTest();
        BatchAndScheduleRollMaxDateDeStage batch = new BatchAndScheduleRollMaxDateDeStage();
        Database.executeBatch(batch);
        Test.stopTest();

        Account acc1 = [SELECT Id, Convsta_roll_max_date_de_stage__c
                        FROM Account
                        WHERE Name = 'Account 1'];
        Case lastCase1 = [SELECT Id, Convsta_DateStart__c
                          FROM Case
                          WHERE Subject = 'Last case 1'];
        System.assertEquals(lastCase1.Convsta_DateStart__c, acc1.Convsta_roll_max_date_de_stage__c);

        Account acc2 = [SELECT Id, Convsta_roll_max_date_de_stage__c
                        FROM Account
                        WHERE Name = 'Account 2'];
        Case lastCase2 = [SELECT Id, Convsta_DateStart__c
                          FROM Case
                          WHERE Subject = 'Last case 2'];
        System.assertEquals(lastCase2.Convsta_DateStart__c, acc2.Convsta_roll_max_date_de_stage__c);
    }

    @isTest public static void testSchedule() {
    	Test.startTest();        

		BatchAndScheduleRollMaxDateDeStage schedule = new BatchAndScheduleRollMaxDateDeStage();
        String sch = '0 0 4 * * ? *'; //Every day at 04:00
        System.schedule('Test Launch Check', sch, schedule);    
             
        Test.stopTest();
    }
 
}