force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/CONVSTA_Table_Regles_Experience_Pro__c.object-meta.xml
<CustomObject>
    <description>Les règles de gestion associées aux stages/contrats</description>
    <label>Table des Règles Expérience Pro</label>
    <nameField>
        <label>Table des Règles Expérience Professionne</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables des Règles Expérience Pro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CONVSTA_Table_Regles_Experience_Pro__c/fields/Accessible_aux_etudiants__c.field-meta.xml
<CustomField>
    <fullName>Accessible_aux_etudiants__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accessible aux étudiants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TableReglesExperienceProTriggerTest.cls
@isTest
public class TableReglesExperienceProTriggerTest {
	/*
    @isTest
    static void desactivateOldAccessibleTable(){
        CONVSTA_Table_Regles_Experience_Pro__c oldAccessibleTable = TestDataFactory.getTableReglesExperiencePro();
        oldAccessibleTable.Name = 'Old';
        oldAccessibleTable.Accessible_aux_etudiants__c = true;
        insert oldAccessibleTable;

        CONVSTA_Table_Regles_Experience_Pro__c newAccessibleTable = TestDataFactory.getTableReglesExperiencePro();
        newAccessibleTable.Name = 'New';
        newAccessibleTable.Accessible_aux_etudiants__c = false;
        insert newAccessibleTable;

        Test.startTest();
        newAccessibleTable.Accessible_aux_etudiants__c = true;
        update newAccessibleTable;
        Test.stopTest();

        oldAccessibleTable = [SELECT Accessible_aux_etudiants__c FROM CONVSTA_Table_Regles_Experience_Pro__c WHERE Id = :oldAccessibleTable.Id];
        System.assertEquals(false, oldAccessibleTable.Accessible_aux_etudiants__c);
    }*/
}