force-app/main/default/objects/Contact/fields/Adresse_Email_Personnelle__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Email_Personnelle__c</fullName>
    <label>Email Personnel</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nature_du_premier_contact__c.field-meta.xml
<CustomField>
    <fullName>Nature_du_premier_contact__c</fullName>
    <inlineHelpText>décrit le canal technique d’arrivée de la fiche piste dans le système</inlineHelpText>
    <label>Canal d&apos;acquisition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adwords</fullName>
            </value>
            <value>
                <fullName>Agent commercial</fullName>
            </value>
            <value>
                <fullName>Appel d’offre</fullName>
            </value>
            <value>
                <fullName>Appel ou Email entrant</fullName>
            </value>
            <value>
                <fullName>Application mobile</fullName>
            </value>
            <value>
                <fullName>Apport Professeur/Intervenant</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Campus Day virtuel</fullName>
            </value>
            <value>
                <fullName>Directories/ Guides</fullName>
            </value>
            <value>
                <fullName>Display/ Banners</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Emailing Externe</fullName>
            </value>
            <value>
                <fullName>Evénement/ Conférence</fullName>
            </value>
            <value>
                <fullName>Fichiers externes</fullName>
            </value>
            <value>
                <fullName>Foisonnement</fullName>
            </value>
            <value>
                <fullName>Formulaire Candidater</fullName>
            </value>
            <value>
                <fullName>Forum/ Salon</fullName>
            </value>
            <value>
                <fullName>Import contacts</fullName>
            </value>
            <value>
                <fullName>Master class</fullName>
            </value>
            <value>
                <fullName>Module Chat</fullName>
            </value>
            <value>
                <fullName>Open class</fullName>
            </value>
            <value>
                <fullName>Prescripteurs</fullName>
            </value>
            <value>
                <fullName>Présentation aux écoles/ universités</fullName>
            </value>
            <value>
                <fullName>Présentation étudiants</fullName>
            </value>
            <value>
                <fullName>Prospection</fullName>
            </value>
            <value>
                <fullName>Récurrence</fullName>
            </value>
            <value>
                <fullName>Réseaux sociaux</fullName>
            </value>
            <value>
                <fullName>Réunion d&apos;information France</fullName>
            </value>
            <value>
                <fullName>Réunion d&apos;information Internationale</fullName>
            </value>
            <value>
                <fullName>Site internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Adresse_e_mail__c.field-meta.xml
<CustomField>
    <fullName>Adresse_e_mail__c</fullName>
    <externalId>true</externalId>
    <label>Adresse Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TestAutoConvertLeads.cls
@isTest 
      private class TestAutoConvertLeads{
      static testMethod void createnewlead() {
          
      Contact ct = TestDataFactory.getContact();
      ct.Adresse_Email_Personnelle__c = 'mailtest@test.com';
	  ct.Nature_du_premier_contact__c ='Site internet';  
      insert ct;
          
      Account acct = TestDataFactory.getAccount();
      acct.Name = 'Sans organisation connue';
      insert acct;
      
      Id leadtype = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Formation initiale').getRecordTypeId();
          
      Lead leadToCreate =new Lead();
      List<id> Ids= New List<Id>();
      leadToCreate.RecordtypeId= leadtype;
      leadToCreate.LastName ='Test';
      leadToCreate.Company='Salesforce';
      leadToCreate.LeadSource='Formation continue courte';
      leadToCreate.Rating='';
      leadToCreate.Status='';
      leadToCreate.Adresse_e_mail__c='mailtest@test.com';
      insert leadToCreate; 
      
      Ids.add(leadToCreate.id);
          
           Test.startTest(); 
      AutoConvertLeads.leadAssign(Ids);
          Test.stopTest();
      
          Lead converted = [SELECT Id, OwnerId, Status FROM Lead WHERE Id = :Ids];
    	System.assertEquals('Qualifié', converted.Status);
   }
}