force-app/main/default/objects/Contact/fields/Adresse_Email_Personnelle__c.field-meta.xml
<CustomField>
    <fullName>Adresse_Email_Personnelle__c</fullName>
    <label>Email Personnel</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Appliquer_l_e_mail_EM_Lyon__c.field-meta.xml
<CustomField>
    <fullName>Appliquer_l_e_mail_EM_Lyon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appliquer l&apos;e-mail EM Lyon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Appliquer_l_e_mail_personnel__c.field-meta.xml
<CustomField>
    <fullName>Appliquer_l_e_mail_personnel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appliquer l&apos;e-mail personnel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Appliquer_l_e_mail_professionnel__c.field-meta.xml
<CustomField>
    <fullName>Appliquer_l_e_mail_professionnel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appliquer l&apos;e-mail professionnel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_de_repli__c.field-meta.xml
<CustomField>
    <fullName>Email_de_repli__c</fullName>
    <label>Email Professionnel</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_EM_Lyon__c.field-meta.xml
<CustomField>
    <fullName>Email_EM_Lyon__c</fullName>
    <label>Email EM Lyon</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/MaJContactBatchTests.cls
/*
 * Test the batch to update the contact email
 */
@IsTest
public class MaJContactBatchTests {

    @IsTest
    public static void batch_Test(){
        // Data
        List<Contact> lCtc = TestDataFactory.getContacts();
        
        // DO
        Test.startTest();
        MaJContactBatch batch = new MaJContactBatch();
        DataBase.executeBatch(batch, 200);
        Test.stopTest();
        
        List<Contact> contacts = [SELECT Id, Email, Appliquer_l_e_mail_EM_Lyon__c, Email_EM_Lyon__c,
                                  Appliquer_l_e_mail_personnel__c, Adresse_Email_Personnelle__c,
                                  Appliquer_l_e_mail_professionnel__c, Email_de_repli__c
                                  FROM Contact];
        
        // VERIFY
        for(Contact contact : contacts){
            if(contact.Appliquer_l_e_mail_EM_Lyon__c){
                System.assertEquals(contact.Email_EM_Lyon__c, contact.Email);
            }
            
            if(contact.Appliquer_l_e_mail_personnel__c){
                System.assertEquals(contact.Adresse_Email_Personnelle__c, contact.Email);
            }
            
            if(contact.Appliquer_l_e_mail_professionnel__c){
                System.assertEquals(contact.Email_de_repli__c, contact.Email);
            }
        }
    }
}