force-app/main/default/objects/Contact/fields/Email_de_repli__c.field-meta.xml
<CustomField>
    <fullName>Email_de_repli__c</fullName>
    <label>Email Professionnel</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membre_vie__c.field-meta.xml
<CustomField>
    <fullName>Membre_vie__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Membre à vie</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/classes/BatchDeleteEmailEtudiantMAVTest.cls
@isTest 
public class BatchDeleteEmailEtudiantMAVTest
{
    static testMethod void clearEmailRepli() 
    {
        Contact ctc = TestDataFactory.getContact();
        ctc.RecordTypeId = APU_ApexUtils.getContactRecordTypeIdByName('Etudiant');
        ctc.Membre_vie__c = true;
        ctc.Email_de_repli__c = 'test@test.com';
        insert ctc;
        
        Test.startTest();

        BatchDeleteEmailProfessionnelEtudiantMAV batch = new BatchDeleteEmailProfessionnelEtudiantMAV();
        Database.executeBatch(batch); 
            
        Test.stopTest();
        
        ctc = [SELECT Id, Email_de_repli__c FROM Contact];
        
        System.assertEquals(null, ctc.Email_de_repli__c);
    }
}