force-app/main/default/objects/Contact/fields/Famille_Fonction__c.field-meta.xml
<CustomField>
    <fullName>Famille_Fonction__c</fullName>
    <label>Famille Fonction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Autres</fullName>
                <default>true</default>
                <label>Autres</label>
            </value>
            <value>
                <fullName>Commercial/Ventes</fullName>
            </value>
            <value>
                <fullName>Direction Générale</fullName>
            </value>
            <value>
                <fullName>Enseignement/Education</fullName>
            </value>
            <value>
                <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
            </value>
            <value>
                <fullName>Finance/Gest./Adminis./Juridi.</fullName>
            </value>
            <value>
                <fullName>Marketing/Communication</fullName>
            </value>
            <value>
                <fullName>Organisation/Systèmes d&apos;Informations</fullName>
            </value>
            <value>
                <fullName>Production/Achats</fullName>
            </value>
            <value>
                <fullName>Ressources Humaines/Formation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect Etudiant</fullName>
            </value>
            <value>
                <fullName>Etudiant</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Contact_central__c.field-meta.xml
<CustomField>
    <fullName>Contact_central__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact central</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_de_mise__c.field-meta.xml
<CustomField>
    <fullName>Date_de_mise__c</fullName>
    <label>Date de création fiche</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exercice__c.field-meta.xml
<CustomField>
    <fullName>Exercice__c</fullName>
    <label>Exercice EMLYON</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
                <default>true</default>
                <label>2015</label>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InterfaceExternalId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceExternalId__c</fullName>
    <externalId>true</externalId>
    <label>InterfaceExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AsyncUpdateContactTest.cls
@isTest
public class AsyncUpdateContactTest {
	static TestMethod void testQueueable() {
        try{
        	Account acc = TestDataFactory.getAccount();
      		insert acc;

            final Contact contact= new Contact(AccountId=acc.Id,
                                               statut__c='Etudiant',
                                               FirstName='Mohamed',
                                               LastName='Abdelfadel',
                                               Salutation='Mr',
                                               Famille_Fonction__c='Autres');

            try{
                insert contact;
            } catch(DmlException dmle)
            {
                System.debug('The following exception has occurred: ' + dmle.getMessage());
            }


            Id RecordTypeFundraisingB2CId= APU_ApexUtils.getOpportunityRecordTypeIdByName('Fundraising B2C');
            final Opportunity opp1= new Opportunity(RecordTypeId= RecordTypeFundraisingB2CId,StageName='Prospect probable',
                                                    Name='test opp 1',
                                                    Contact_central__c=contact.Id,
                                                    AccountId=acc.Id,
                                                    amount = 1000,
                                                    Exercice__c='2015',
                                                    CloseDate=Date.valueOf('2015-08-15'),
                                                    InterfaceExternalId__c = 'blabla1',
                                                    Date_de_mise__c = DateTime.valueOf('2014-12-01 10:00:00'));

            final Opportunity opp2= new Opportunity(RecordTypeId= RecordTypeFundraisingB2CId,StageName='Conclu',
                                                    Name='test opp 2',
                                                    Contact_central__c=contact.Id,
                                                    AccountId=acc.Id,
                                                    amount = 500,
                                                    Exercice__c='2015',
                                                    CloseDate=Date.valueOf('2015-08-15'),
                                                    InterfaceExternalId__c = 'blabla2',
                                                    Date_de_mise__c = DateTime.valueOf('2014-12-01 10:00:00'));


            final List<Opportunity> myOpportunities = new List <Opportunity>();
            myOpportunities.add(opp1);
            myOpportunities.add(opp2);

            Boolean exceptionCatched = false;
            String err ='';
            try{
                insert myOpportunities;
            }catch (System.DMLException e){
                exceptionCatched = true;
                err = e.getMessage();
            }
            System.assertEquals(exceptionCatched, false, err);

            opp1.StageName='Conclu';
            opp2.StageName='Prospect probable';

            //Assert Test
            Test.startTest();

            exceptionCatched = false;
            try {
                update myOpportunities;
            } catch (System.DMLException e) {
                exceptionCatched = true;
                err = e.getMessage();
            }
            System.assertEquals(exceptionCatched, false, err);

            final Opportunity opp3= new Opportunity();
            myOpportunities.add(opp3);
            try {
                update myOpportunities;
            } catch (System.DMLException e) {
                exceptionCatched = true;
            }

            System.assertEquals(exceptionCatched, true);
            Test.stopTest();
        }catch(DmlException dmle)
        {
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }
    }
}