force-app/main/default/objects/Contact/fields/Famille_Fonction__c.field-meta.xml
<CustomField>
    <fullName>Famille_Fonction__c</fullName>
    <label>Famille Fonction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Autres</fullName>
                <default>true</default>
                <label>Autres</label>
            </value>
            <value>
                <fullName>Commercial/Ventes</fullName>
            </value>
            <value>
                <fullName>Direction Générale</fullName>
            </value>
            <value>
                <fullName>Enseignement/Education</fullName>
            </value>
            <value>
                <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
            </value>
            <value>
                <fullName>Finance/Gest./Adminis./Juridi.</fullName>
            </value>
            <value>
                <fullName>Marketing/Communication</fullName>
            </value>
            <value>
                <fullName>Organisation/Systèmes d&apos;Informations</fullName>
            </value>
            <value>
                <fullName>Production/Achats</fullName>
            </value>
            <value>
                <fullName>Ressources Humaines/Formation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/nb_SIP_en_cours__c.field-meta.xml
<CustomField>
    <fullName>nb_SIP_en_cours__c</fullName>
    <description>Indique le nombre total d&apos;opportunités qualifiées (pour l&apos;exercice en cours) pour le contact central de cette opportunité.
Il comptabilise les opportunités de type : Prospect qualifié;Prospect probable;Prospect chaud;Intérêt Supplémentaire</description>
    <label>Nombre d&apos;opportunités Conseiller</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre_opportunit_s__c.field-meta.xml
<CustomField>
    <fullName>Nombre_opportunit_s__c</fullName>
    <label>Nombre d&apos;opportunités total</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre_opportunites_sur_criteres__c.field-meta.xml
<CustomField>
    <fullName>Nombre_opportunites_sur_criteres__c</fullName>
    <label>Nombre d&apos;opportunités en cours</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect Etudiant</fullName>
            </value>
            <value>
                <fullName>Etudiant</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Etudiant.recordType-meta.xml
<RecordType>
    <fullName>Etudiant</fullName>
    <active>true</active>
    <label>Etudiant</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Professionnel.recordType-meta.xml
<RecordType>
    <fullName>Professionnel</fullName>
    <active>true</active>
    <label>Professionnel</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Code_Agresso_Opportunit__c.field-meta.xml
<CustomField>
    <fullName>Code_Agresso_Opportunit__c</fullName>
    <description>Ce champ est remplit automatiquement en se basant sur &quot; RecordType + Exercice + Compteur Opp&quot;</description>
    <label>Code Agresso Opportunité</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compteur_OPPT__c.field-meta.xml
<CustomField>
    <fullName>Compteur_OPPT__c</fullName>
    <externalId>true</externalId>
    <label>Compteur OPPT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_central__c.field-meta.xml
<CustomField>
    <fullName>Contact_central__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact central</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_de_mise__c.field-meta.xml
<CustomField>
    <fullName>Date_de_mise__c</fullName>
    <label>Date de création fiche</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exercice__c.field-meta.xml
<CustomField>
    <fullName>Exercice__c</fullName>
    <label>Exercice EMLYON</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
                <default>true</default>
                <label>2015</label>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exercice_de_report__c.field-meta.xml
<CustomField>
    <fullName>Exercice_de_report__c</fullName>
    <label>Exercice de report</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ExerciceNum_ro__c.field-meta.xml
<CustomField>
    <fullName>ExerciceNum_ro__c</fullName>
    <label>Exercice</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InterfaceExternalId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceExternalId__c</fullName>
    <externalId>true</externalId>
    <label>InterfaceExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InterfaceExternalId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceExternalId__c</fullName>
    <externalId>true</externalId>
    <label>InterfaceExternalId Poste</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>TEXT(Opportunity.StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Suiveur__c.field-meta.xml
<CustomField>
    <fullName>Suiveur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suiveur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Produits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Programme.recordType-meta.xml
<RecordType>
    <fullName>Programme</fullName>
    <active>true</active>
    <label>Programme</label>
</RecordType>

force-app/main/default/classes/TestTR003ManageOpportunities.cls
/*-------------------------------------------------------------------
-- - Purpose       : Test class for TR003ManageOpportunities
--
-- Maintenance History:
--
-- Date        Name  Version  Remarks
-- ----------  ----  -------  ---------------------------------------
-- ??????????  ????  1.0
-- 04/01/2018  T.CH  1.1
-- 17/01/2018  A.DO  1.2      Fixe duplicate & corection
-- 19/01/2018  A.DO  1.3      Add tests for AssignOwnerId and setup()
-- 17/01/2020  E.BE  1.4      correct createUser
--------------------------------------------------------------------  */
@isTest()
private class TestTR003ManageOpportunities {

    @isTest static void IncrementCompteurOPPT(){
        // Simuler Top Agresso ou Interface
        PAD.addTriggerBypass('TR006OppLineItem2FieldsNull');
      	PAD.addTriggerBypass('TR007Opp2FieldsNull');
        
        Account acc = TestDataFactory.getAccount();
        insert acc;

        // Met criteria
        Opportunity opp1 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Pré inscrit');

        Opportunity opp2 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Inscrit');

        Opportunity opp3 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Admis');
        
        Opportunity opp4 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Intégré');
        
        Opportunity opp5 = TestObjectFactory.createOpportunity(acc,  'Programme Long Diplômant', 'Candidat');
    

        // Don't met criteria
        Opportunity opp6 = TestObjectFactory.createOpportunity(acc, 'Formation courte', 'Prospect report');
        // validation rule
        opp6.Exercice_de_report__c = '2022'; 
        Opportunity opp7 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Prospect report');
        // validation rule
        opp7.Exercice_de_report__c = '2022';
        // Met criteria
        Opportunity opp8 = TestObjectFactory.createOpportunity(acc, 'Programme Long Diplômant', 'Candidat');

        // Met criteria (opp line will contains Agresso)
        Opportunity opp9 = TestObjectFactory.createOpportunity(acc, 'Formation intra-entreprise');
        opp9.Code_Agresso_Opportunit__c = 'IEXX-XXXXXX';

        Test.startTest();
        insert new List<Opportunity>{opp1, opp2, opp3, opp4, opp5, opp6, opp7, opp8, opp9};
        update opp9; // Simulate update on existing Agresso : no change
        Test.stopTest();
    
        opp1 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp1.Id];
        opp2 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp2.Id];
        opp3 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp3.Id];
        opp4 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp4.Id];
        opp5 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp5.Id];
        opp6 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp6.Id];
        opp7 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp7.Id];
        opp8 = [SELECT Id, Compteur_OPPT__c FROM Opportunity WHERE Id = :opp8.Id];
        opp9 = [SELECT Id, Code_Agresso_Opportunit__c FROM Opportunity WHERE Id = :opp9.Id];

        // Incrementation
        System.assertEquals(opp1.Compteur_OPPT__c + 1, opp2.Compteur_OPPT__c);
        System.assertEquals(opp2.Compteur_OPPT__c + 1, opp3.Compteur_OPPT__c);
        System.assertEquals(opp3.Compteur_OPPT__c + 1, opp4.Compteur_OPPT__c);
        System.assertEquals(opp4.Compteur_OPPT__c + 1, opp5.Compteur_OPPT__c);

        // No incrementation
        System.assertEquals(null, opp6.Compteur_OPPT__c);
        System.assertEquals(null, opp7.Compteur_OPPT__c);

        // Incrementation
        System.assertEquals(opp5.Compteur_OPPT__c + 1, opp8.Compteur_OPPT__c);

        // No change on Agresso
        System.assertEquals('IEXX-XXXXXX', opp9.Code_Agresso_Opportunit__c);

        // Simuler Top Agresso ou Interface
        PAD.removeTriggerBypass('TR006OppLineItem2FieldsNull');
      	PAD.removeTriggerBypass('TR007Opp2FieldsNull');
    }

    @isTest static void UpdateOppsNumber() {
    	Account acc = TestDataFactory.getAccount();
        insert acc;

        // Détermination de l'exercice actuel
        Date endExerciceDate = Date.newinstance(System.Today().year(), 8, 31);
        Date actualDate = Date.today();
        Integer actualExercice = 0;
        if(actualDate>endExerciceDate){
            actualExercice = actualDate.year() + 1;
        }else{
            actualExercice = actualDate.year();
        }

        Contact contact1= new Contact(AccountId=acc.Id,
                                      statut__c='Etudiant',
                                      FirstName='Contact1',
                                      LastName='Contact1',
                                      Salutation='Mme',
                                      Famille_Fonction__c='Autres',
                                      Nombre_opportunit_s__c = '0',
                                      Nombre_opportunites_sur_criteres__c = '0',
                                      nb_SIP_en_cours__c = 0
                                     );
        insert contact1;

        // Opp pour nb total
        Opportunity opp1= new Opportunity(StageName='Sollicité',
                                       Name='test1',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c='2016',
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID1',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));

        // Opp pour nb En cours
        Opportunity opp2= new Opportunity(StageName='Intéressé par',
                                       Name='test2',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c='2016',
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID2',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));
        
        // Opp pour nb En cours sur l'exercice en cours
        Opportunity opp3= new Opportunity(StageName='Sollicité',
                                       Name='test3',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c=String.valueOf(actualExercice),
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID3',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));

        // Opp pour nb Conseillers
        Opportunity opp4= new Opportunity(StageName='Prospect chaud',
                                       Name='test4',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c='2016',
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID4',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));

        // Opp pour nb Conseillers sur l'exercice en cours
        Opportunity opp5= new Opportunity(StageName='Prospect chaud',
                                       Name='test5',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c=String.valueOf(actualExercice),
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID5',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));

        // opp pour nb En cours et Conseillers sur l'exercice en cours
        Opportunity opp6= new Opportunity(StageName='Intérêt Supplémentaire',
                                       Name='test6',
                                       Contact_central__c=contact1.Id,
                                       AccountId=acc.Id,
                                       Exercice__c=String.valueOf(actualExercice),
                                       CloseDate=Date.valueOf('2017-08-31'),
                                       InterfaceExternalId__c = 'InterfaceExternalID6',
                                       Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00'));
        
        insert new List<Opportunity>{opp1, opp2, opp3, opp4, opp5, opp6};

        Test.startTest();
        TR003ManageOpportunities.UpdateOppsNumber(new Set<Id>{contact1.Id});
        Test.stopTest();

        contact1 = [SELECT Id, Nombre_opportunit_s__c, Nombre_opportunites_sur_criteres__c, nb_SIP_en_cours__c
                    FROM Contact
                    WHERE FirstName =:'Contact1'];

        // Test du nombre total d'opportunité 
        System.assertEquals(6, Integer.valueOf(contact1.Nombre_opportunit_s__c));

        // Test du nombre total d'opportunité 
        System.assertEquals(2, Integer.valueOf(contact1.Nombre_opportunites_sur_criteres__c));

        // Test du nombre total d'opportunité 
        System.assertEquals(2, contact1.nb_SIP_en_cours__c);
    }
    
    /*
    @isTest static void UpdateOppsNumberProfesionnel() {
        Account acc = TestDataFactory.getAccount();
        insert acc;
        
        Contact con = TestObjectFactory.createContact(acc, 'Professionnel');
        con.Nombre_opportunites_sur_criteres__c='0';
        insert con;        
        
        Id recordTypeFormationCourteId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Formation courte');
        Id recordTypeFormationLongDiplomantId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Programme Long Diplômant');
        
        List<Opportunity> oppList = TestObjectFactory.createOpportunities(acc, 'Formation courte', 20);
        
        for (Opportunity opp: oppList) {
            if (Math.random() > 0.5) {
                opp.RecordTypeId = recordTypeFormationCourteId;
            } else {
                opp.RecordTypeId = recordTypeFormationLongDiplomantId;          
            }
            opp.Contact_central__c = con.Id;
            opp.ExerciceNum_ro__c=''+Date.today().year();
            opp.CloseDate=Date.valueOf('2017-08-31');
            opp.Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00');
            opp.StageName = 'Intéressé par';
        }
        
        List<Opportunity> oppList2 = TestObjectFactory.createOpportunities(acc, 'Formation courte', 20);
        
        for (Opportunity opp: oppList2) {
            if (Math.random() > 0.5) {
                opp.RecordTypeId = recordTypeFormationCourteId;
            } else {
                opp.RecordTypeId = recordTypeFormationLongDiplomantId;          
            }
            opp.Contact_central__c = con.Id;
            opp.Exercice__c='2013';
            opp.ExerciceNum_ro__c='2000';
            opp.CloseDate=Date.valueOf('2017-08-31');
            opp.Date_de_mise__c = DateTime.valueOf('2017-08-31 10:00:00');
            opp.StageName = 'Intéressé par 2';
        }
        
        oppList.addall(oppList2);        
        insert oppList;
        
        Test.startTest();
        try {
            TR003ManageOpportunities.UpdateOppsNumber(new Set<Id>{con.Id});
        } catch (Exception e) {
            System.debug('find Exception');
            System.debug(e);
        }
        Test.stopTest();
        
        Contact conCheck = [SELECT Id, Nombre_opportunites_sur_criteres__c FROM Contact WHERE Id = :con.Id];
        System.assertEquals('20', conCheck.Nombre_opportunites_sur_criteres__c);
    }*/

    @isTest static void CheckOwnerIdChangeAdmin(){
        User usrOld = TestObjectFactory.createUser('OldUser');
        insert usrOld;
        
        User usrNew = TestObjectFactory.createUser('NewUser');
        insert usrNew;
        
        Opportunity opp = TestDataFactory.getOpportunity('Formation initiale');
        opp.OwnerId = usrOld.Id;
        insert opp;
        PAD.removeTriggerHasRun('TR003ManageOpportunities'); // Pour permettre appel dans l'update

        Profile p = [SELECT Id FROM Profile WHERE Name='Administrateur système'];
        User usrRunAs = TestObjectFactory.createUser('UserRun');
        usrRunAs.ProfileId = p.Id;
        insert usrRunAs;

        System.runAs(usrRunAs){
            Test.startTest();
            opp.OwnerId = usrNew.Id;
            update opp;
            Test.stopTest();
        }

        // Nothing to test
    }

    @isTest static void CheckOwnerIdChange(){
        UserRole usrOldRole = [SELECT Id
                                FROM UserRole
                                WHERE DeveloperName = 'EML'];
        UserRole usrNewRole = [SELECT Id
                                FROM UserRole
                                WHERE DeveloperName = 'Direction_Entreprise'];

        User usrOld = TestObjectFactory.createUser('OldUser','EML');
        usrOld.UserRoleId = usrOldRole.Id;
        insert usrOld;        
        User usrNew = TestObjectFactory.createUser('NewUser','EML');
        usrNew.UserRoleId = usrNewRole.Id;
        insert usrNew;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'BDD'];      

        User usrRunAs = TestObjectFactory.createUser('UserRun');
        usrRunAs.ProfileId = p.Id;
        insert usrRunAs;

        System.runAs(usrRunAs){            
            Opportunity opp = TestDataFactory.getOpportunity('Formation courte');
            opp.OwnerId = usrOld.Id;
            insert opp;
            PAD.removeTriggerHasRun('TR003ManageOpportunities'); // Pour permettre appel dans l'update
        
            Test.startTest();
            try{
                opp.OwnerId = usrNew.Id;
                update opp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Le propriétaire actuel de l\'opportunité  et le nouveau propriétaire doivent avoir le même rôle !');
                System.AssertEquals(expectedExceptionThrown, true);
            } 
            Test.stopTest();
        }
    }

    @isTest static void CheckUserRoleIdChange(){
        UserRole usrOldRole = [SELECT Id
                               FROM UserRole
                               WHERE DeveloperName = 'EML'];
        UserRole usrNewRole = [SELECT Id
                               FROM UserRole
                               WHERE DeveloperName = 'Direction_Entreprise'];

        User usrOld = TestObjectFactory.createUser('OldUser','EML');
        usrOld.UserRoleId = usrOldRole.Id;
        insert usrOld;        
        User usrNew = TestObjectFactory.createUser('NewUser','EML');
        usrNew.UserRoleId = usrOldRole.Id;
        insert usrNew;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'BDD'];      

        User usrRunAs = TestObjectFactory.createUser('UserRun');
        usrRunAs.ProfileId = p.Id;
        usrRunAs.UserRoleId = usrNewRole.Id;
        insert usrRunAs;

        System.runAs(usrRunAs){            
            Opportunity opp = TestDataFactory.getOpportunity('Formation courte');
            opp.OwnerId = usrOld.Id;
            insert opp;
            PAD.removeTriggerHasRun('TR003ManageOpportunities'); // Pour permettre appel dans l'update
        
            Test.startTest();
            try{
                opp.OwnerId = usrNew.Id;
                update opp;
            }catch(Exception e){
                System.debug('eGetMessage: ' + e.getMessage());
                Boolean expectedExceptionThrown =  e.getMessage().contains('Vous ne pouvez pas réaffecter une opportunité qui n\'est pas dans votre pôle !');
                System.AssertEquals(expectedExceptionThrown, true);
            } 
            Test.stopTest();
        }
    }    

    @isTest static void CreateContactRole(){
        //Data creation
        Test.startTest();

        Product2 prod = new Product2(Name='prodTest', Suiveur__c = UserInfo.getUserId());
        Product2 prod2 = new Product2(Name='prodTest', Suiveur__c = null);
        insert new List<Product2>{prod,prod2};

        Pricebookentry pricebook1= new PriceBookEntry(Product2Id=prod.Id, UnitPrice=10, Pricebook2Id=Test.getStandardPricebookId(), IsActive = true, UseStandardPrice = false);
        Pricebookentry pricebook2= new PriceBookEntry(Product2Id=prod2.Id, UnitPrice=10, Pricebook2Id=Test.getStandardPricebookId(), IsActive = true, UseStandardPrice = false);
        insert new List<Pricebookentry>{pricebook1,pricebook2};

        Account acc = TestDataFactory.getAccount();
        insert acc;

        final Contact contact= new Contact(AccountId=acc.Id,
                                           statut__c='Professionnel',
                                           FirstName='Mahmoud',
                                           LastName='BECHAA',
                                           Salutation='M',
                                           Famille_Fonction__c='Autres');
        try{
          insert contact;
        }catch(DmlException dmle){
          System.debug('The following exception has occurred: ' + dmle.getMessage());
        }
        final Opportunity opp= new Opportunity(StageName='Prospect probable',
                                               Name='test',
                                               Contact_central__c=contact.Id,
                                               AccountId=acc.Id,
                                               Exercice__c='2015',
                                               CloseDate=Date.valueOf('2015-08-15'),
                                               InterfaceExternalId__c = 'blabla',
                                               Date_de_mise__c = DateTime.valueOf('2014-12-01 10:00:00'));


        try{
            insert opp;
        }catch(DmlException dmle){
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }

        final OpportunityLineItem opLine = new OpportunityLineItem(OpportunityId = opp.Id,
                                                                   InterfaceExternalId__c='blabla',
                                                                   PricebookentryId=pricebook1.Id,
                                                                   Totalprice=10,
                                                                   Quantity = 1);

        try{
            insert opLine;
        }catch(DmlException dmle){
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }
        final Opportunity opp2 = new Opportunity(StageName='Prospect probable',
                                                 Name='test',
                                                 Contact_central__c=contact.Id,
                                                 AccountId=acc.Id,
                                                 Exercice__c='2015',
                                                 CloseDate=Date.valueOf('2015-08-15'),
                                                 InterfaceExternalId__c = 'blabla2',
                                                 Date_de_mise__c = DateTime.now());


        try{
            insert opp2;
        }catch(DmlException dmle)
        {
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }


        final OpportunityLineItem opLine2 = new OpportunityLineItem(OpportunityId = opp2.Id,
                                                                    InterfaceExternalId__c='blabla2',
                                                                    PricebookentryId=pricebook1.Id,
                                                                    Totalprice=10,
                                                                    Quantity = 1);

        try{
            insert opLine2;
        }catch(DmlException dmle)
        {
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }

        Opportunity opp3 = new Opportunity(StageName='Prospect probable',
                                           Name='test',
                                           Contact_central__c=null,// No contact central
                                           AccountId=acc.Id,
                                           Exercice__c='2015',
                                           CloseDate=Date.valueOf('2015-08-15'),
                                           InterfaceExternalId__c = 'blabla3',
                                           Date_de_mise__c = DateTime.now());

        try{
            insert opp3;
        } catch(DmlException dmle)
        {
            System.debug('The following exception has occurred: ' + dmle.getMessage());
        }
        final OpportunityLineItem opLine3 = new OpportunityLineItem(OpportunityId = opp3.Id,
                                                                    InterfaceExternalId__c='blabla3',
                                                                    PricebookentryId=pricebook2.Id,
                                                                    Totalprice=10,
                                                                    Quantity = 1);

        Set<Id> idContacts = new Set<Id>();
        idContacts.add(contact.Id);
        List<Contact> contacts = new List<Contact>();
        contacts.add(contact);
        List<Opportunity> opportunities = New List<Opportunity>();
        OpportunityContactRole role = new OpportunityContactRole();

        opportunities.add(opp);
        opportunities.add(opp2);
        opportunities.add(opp3);
        if(contacts.size() > 0 && opportunities.size() > 0)
        {
            for (Opportunity oppo: opportunities)
            {
                for (Contact cont : contacts)
                {
                    role.ContactId = cont.id;
                    role.IsPrimary = true;
                    role.OpportunityId = oppo.id;
                    role.Role = 'Contact central';
                }
            }
        }
        insert role;

        Test.stopTest();
    }
}