force-app/main/default/objects/Contact/fields/Souhait_programme__c.field-meta.xml
<CustomField>
    <fullName>Souhait_programme__c</fullName>
    <description>Champ alimenté depuis l&apos;opportunité</description>
    <inlineHelpText>Champ alimenté depuis l&apos;opportunité</inlineHelpText>
    <label>Souhait programme</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_central__c.field-meta.xml
<CustomField>
    <fullName>Contact_central__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact central</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FORM_Exercice_en_cours__c.field-meta.xml
<CustomField>
    <fullName>FORM_Exercice_en_cours__c</fullName>
    <formula>AND 
( 
TODAY()&gt;FORM_debut_annee_scolaire__c 
, 
TODAY()&lt;FORM_fin_annee_scolaire__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FORM Exercice en cours/Suivant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunite_active__c.field-meta.xml
<CustomField>
    <fullName>Opportunite_active__c</fullName>
    <formula>IF(
NOT(
OR(
ISPICKVAL (StageName, &quot;Clos (Perdu)&quot;),
ISPICKVAL (StageName, &quot;Compte doublon&quot;)
)
)
,
true,
false
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunité active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MaJContactByOpportunityBatchTests.cls
/*
 * Test class
 * Test the batch to update the owner and the Souhait_programme__c of a contact
 */
@IsTest
public class MaJContactByOpportunityBatchTests {

    @IsTest
    public static void batch_Test(){
        // Data
        DataTests data = TestDataFactory.get_4_OpportunitiesWithSameContact(MaJOpportunityServiceTests.RT_FORMATION_INITIALE, MaJOpportunityServiceTests.RT_FORMATION_INITIALE, 'Relations Employeur');
        List<Opportunity> opps = [SELECT Id, Name, OwnerId, IsClosed, 
                           FORM_Exercice_en_cours__c, RecordTypeId, 
                           Opportunite_active__c,  Contact_central__c,
                           Contact_central__r.OwnerId, 
                           Contact_central__r.Souhait_programme__c 
                           FROM Opportunity];
        
        // DO
        Test.startTest();
        MaJContactByOpportunityBatch batch = new MaJContactByOpportunityBatch();
        DataBase.executeBatch(batch, 200);
        Test.stopTest();
        
        Contact contact = [SELECT Id, Souhait_programme__c FROM Contact WHERE Id = :opps.get(0).Contact_central__c];      
        
		// VERIFY
        System.assertEquals(opps.get(0).Name, contact.Souhait_programme__c);
    }
}