force-app/main/default/objects/Detail_pack__c/Detail_pack__c.object-meta.xml
<CustomObject>
    <label>Détail pack</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Id de Détail pack</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail_pack__c/fields/Composant__c.field-meta.xml
<CustomField>
    <fullName>Composant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composant</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pack parent</relationshipLabel>
    <relationshipName>Composant_pack</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detail_pack__c/fields/Pack__c.field-meta.xml
<CustomField>
    <fullName>Pack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pack</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Détails pack</relationshipLabel>
    <relationshipName>Details_pack</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detail_pack_session__c/Detail_pack_session__c.object-meta.xml
<CustomObject>
    <label>Détail pack session</label>
    <nameField>
        <displayFormat>DPS-{0}</displayFormat>
        <label>Nom de Détail pack session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail_pack_session__c/fields/Composant_session__c.field-meta.xml
<CustomField>
    <fullName>Composant_session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composant session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Liste des sessions packs utilisant la session</relationshipLabel>
    <relationshipName>Details_pack_session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detail_pack_session__c/fields/Pack_Session__c.field-meta.xml
<CustomField>
    <fullName>Pack_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pack Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Détails des Sessions composant le pack</relationshipLabel>
    <relationshipName>Details_pack_session2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gamme__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accompagnement entreprises = RDV</fullName>
            </value>
            <value>
                <fullName>Accompagnement pédagogique</fullName>
            </value>
            <value>
                <fullName>Accord Cadre Formation Continue =</fullName>
            </value>
            <value>
                <fullName>Annuaires</fullName>
            </value>
            <value>
                <fullName>Atelier</fullName>
            </value>
            <value>
                <fullName>Business Weeks</fullName>
            </value>
            <value>
                <fullName>Careers Days</fullName>
            </value>
            <value>
                <fullName>Célébration</fullName>
            </value>
            <value>
                <fullName>Chaires Conjointes</fullName>
            </value>
            <value>
                <fullName>Chaires d’enseignement et de recherche (&gt;1Me sur 4/5 ans)</fullName>
            </value>
            <value>
                <fullName>Colloques</fullName>
            </value>
            <value>
                <fullName>Conférence</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (notoriété)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (pédagogiques)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (type gd public)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (type scientifique)</fullName>
            </value>
            <value>
                <fullName>Conférences payantes (par l&apos;auditeur, participant)</fullName>
            </value>
            <value>
                <fullName>Conférences payantes (par l&apos;intervenant-casHEC)</fullName>
            </value>
            <value>
                <fullName>Conseil institutionnel =</fullName>
            </value>
            <value>
                <fullName>Corporate Discovery Session</fullName>
            </value>
            <value>
                <fullName>Dons Fondation =&gt; individu ou entreprise (idem EMLYON)</fullName>
            </value>
            <value>
                <fullName>Enquêtes et Stats</fullName>
            </value>
            <value>
                <fullName>Entretien individuel</fullName>
            </value>
            <value>
                <fullName>Evènements corporate payants organisés par la comm</fullName>
            </value>
            <value>
                <fullName>Evenements EMLYON.</fullName>
            </value>
            <value>
                <fullName>Evenements EMLYON. (A voir avec BB)</fullName>
            </value>
            <value>
                <fullName>Evenements EMLYON (à positionner confer supra - voir Bernard)</fullName>
            </value>
            <value>
                <fullName>Evenements FOREVER co-organisés</fullName>
            </value>
            <value>
                <fullName>Evènements FOREVER organisés par EMLYON FOREVER</fullName>
            </value>
            <value>
                <fullName>Expert Panels OU Table rondes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Champ_syst_me_pour_clonage__c.field-meta.xml
<CustomField>
    <fullName>Champ_syst_me_pour_clonage__c</fullName>
    <label>Champ système pour clonage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Code_OLI__c.field-meta.xml
<CustomField>
    <fullName>Code_OLI__c</fullName>
    <externalId>true</externalId>
    <label>Code_OLI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CodeAgresso_Poste_Opportunite__c.field-meta.xml
<CustomField>
    <fullName>CodeAgresso_Poste_Opportunite__c</fullName>
    <description>Ce champ est remplit automatiquement en se basant sur &quot; RecordType + Exercice + Compteur Opp&quot;</description>
    <label>Code Agresso Poste Opportunité</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Famille__c)</formula>
    <label>Famille</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProduitFiltreSession__c.field-meta.xml
<CustomField>
    <fullName>ProduitFiltreSession__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProduitFiltreSession</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Poste d&apos;opportunité</relationshipLabel>
    <relationshipName>Poste_d_opportunit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Session_de_formation__c.field-meta.xml
<CustomField>
    <fullName>Session_de_formation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session de formation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.ProduitFiltreSession__c</field>
            <operation>equals</operation>
            <valueField>Session__c.Produits__c</valueField>
        </filterItems>
        <filterItems>
            <field>Session__c.Statut__c</field>
            <operation>notEqual</operation>
            <value>Complète</value>
        </filterItems>
        <filterItems>
            <field>Session__c.Statut__c</field>
            <operation>notEqual</operation>
            <value>Abandonnée</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Liste prévisionnelle inscrit</relationshipLabel>
    <relationshipName>Poste_d_opportunit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type_produit__c.field-meta.xml
<CustomField>
    <fullName>Type_produit__c</fullName>
    <description>Champ permettant de stocker le type d&apos;enregistrement du produit. Il est nécessaire de la stocker pour des raisons techniques : pour les parcours un roll-up sur l&apos;opportunité permet de savoir si on est dans le cas d&apos;un parcours.</description>
    <label>Type produit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille / Domaine</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accélérateur</fullName>
            </value>
            <value>
                <fullName>Accompagnement Carrières</fullName>
            </value>
            <value>
                <fullName>Accompagnement entreprises = RDV</fullName>
            </value>
            <value>
                <fullName>Accompagnement pédagogique</fullName>
            </value>
            <value>
                <fullName>Accord Cadre Formation Continue =</fullName>
            </value>
            <value>
                <fullName>Achats</fullName>
            </value>
            <value>
                <fullName>Alternance</fullName>
            </value>
            <value>
                <fullName>Annuaires</fullName>
            </value>
            <value>
                <fullName>Atelier</fullName>
            </value>
            <value>
                <fullName>Au choix</fullName>
            </value>
            <value>
                <fullName>Business Weeks</fullName>
            </value>
            <value>
                <fullName>Careers Days</fullName>
            </value>
            <value>
                <fullName>Célébration</fullName>
            </value>
            <value>
                <fullName>Chaires Conjointes</fullName>
            </value>
            <value>
                <fullName>Chaires d’enseignement et de recherche (&gt;1Me sur 4/5 ans)</fullName>
            </value>
            <value>
                <fullName>Colloques</fullName>
            </value>
            <value>
                <fullName>Conférence</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (notoriété)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (pédagogiques)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (type gd public)</fullName>
            </value>
            <value>
                <fullName>Conférences non payantes (type scientifique)</fullName>
            </value>
            <value>
                <fullName>Conférences payantes (par l&apos;auditeur, participant)</fullName>
            </value>
            <value>
                <fullName>Conférences payantes (par l&apos;intervenant-casHEC)</fullName>
            </value>
            <value>
                <fullName>Confier 1 projet à 1 étudiant</fullName>
            </value>
            <value>
                <fullName>Conseil institutionnel =</fullName>
            </value>
            <value>
                <fullName>Corporate Discovery Session</fullName>
            </value>
            <value>
                <fullName>CVThèque</fullName>
            </value>
            <value>
                <fullName>Développement Commercial et Relation client</fullName>
            </value>
            <value>
                <fullName>Développement personnel</fullName>
            </value>
            <value>
                <fullName>Dons Fondation =&gt; individu ou entreprise  (idem EMLYON)</fullName>
            </value>
            <value>
                <fullName>Programme apprentissage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Produit_Pack__c.field-meta.xml
<CustomField>
    <fullName>Produit_Pack__c</fullName>
    <formula>RecordType.DeveloperName = &quot;Pack&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produit Pack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <label>Module</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Pack.recordType-meta.xml
<RecordType>
    <fullName>Pack</fullName>
    <active>true</active>
    <label>Pack</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Programme.recordType-meta.xml
<RecordType>
    <fullName>Programme</fullName>
    <active>true</active>
    <label>Programme</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session de formation</label>
    <nameField>
        <label>Nom de Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions de formation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Produits__c.field-meta.xml
<CustomField>
    <fullName>Produits__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TR002ManageOpportunityLineItem.cls
/*--------------------------------------------------------------------
-- - Purpose             : Implementation of methods called by trigger on opportunity line items.
--
-- - Maintenance History :
--
-- Date        Name  Company  Version  Remarks
-- ----------  ----  -------  -------  -------------------------------
-- 00/00/20XX  XXXX  XXXXXXX  1.0      Initial version
-- 14/02/2018  T.CH  MODIS    2.0      1018's implementation
-- 27/03/2018  T.CH  MODIS    2.1      Integration's check of Opportunity on BeforeInsert
--------------------------------------------------------------------*/
public class TR002ManageOpportunityLineItem {
   
    public static void checkIncrementCompteurOPPLine(List<OpportunityLineItem> lOppLine, Boolean forceChange) {
        List<OpportunityLineItem> lOppLineToUpdate = new List<OpportunityLineItem>();
        List<OpportunityLineItem> lOppLineCandidates = new List<OpportunityLineItem>();

        // Récupération des opp lines sans Code Agresso
        for(OpportunityLineItem oppLine : lOppLine){
            if(oppLine.CodeAgresso_Poste_Opportunite__c == null){
                lOppLineCandidates.add(oppLine);
            }
        }
        
        // Récupération du dernier Compteur du Code Agresso connu
        Integer lastCompteurOppLine = TR002ManageOpportunityLineItem.getLastCompteurOppLine();
        
        // Si la MàJ est forcée par une MàJ d'opp
        if (forceChange) {
            // Incrémentation des opp line
            lOppLineToUpdate = TR002ManageOpportunityLineItem.IncrementCompteurOPPLine(lOppLineCandidates, lastCompteurOppLine);

            // Mise à jour des opp lines
            if(lOppLineToUpdate.size() > 0){
                update lOppLineToUpdate;
            }            
        } else {
            // Récupération des opportunités pour vérification des critères
            Set<Id> oppIds = new Set<Id>();
            for (OpportunityLineItem oppLine: lOppLineCandidates) {            
                oppIds.add(oppLine.OpportunityId);
            }
            
            Map<Id, Opportunity> opps = new Map<Id, Opportunity>([
                    SELECT Id, RecordTypeId, StageName
                    FROM Opportunity
                    WHERE Id in :oppIds]);

            Id recordTypeFormationCourteId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Formation courte');
            Id recordTypeProgrammeLongDiplomantId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Programme Long Diplômant');
            Id recordTypeFormationIntraId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Formation intra-entreprise');
            Id recordTypeFormationInitialeId = APU_ApexUtils.getOpportunityRecordTypeIdByName('Formation initiale');
            
            // Vérification des critères 
            for(OpportunityLineItem oppLine :lOppLineCandidates) {
                Opportunity opp = opps.get(oppLine.OpportunityId);
                if(opp!=null){ // Si l'opportunité a bien été insérée en SF
                    if (    (opp.RecordTypeId == recordTypeFormationCourteId
                             && ((opp.StageName == 'Pré inscrit') || (opp.StageName == 'Inscrit')))
                        ||  (opp.RecordTypeId == recordTypeProgrammeLongDiplomantId
                             && ((opp.StageName == 'Admis') || (opp.StageName == 'Intégré') || (opp.StageName == 'Candidat')))
                        ||  (opp.RecordTypeId == recordTypeFormationIntraId)
                        ||  (opp.RecordTypeId == recordTypeFormationInitialeId
                             && opp.StageName == 'Inscrit' && oppLine.Famille__c == 'Programme apprentissage')
                       ){
                            lOppLineToUpdate.add(oppLine);
                    }
                }
            }

            // Incrémentation des opp line
            if (lOppLineToUpdate.size()>0){
                TR002ManageOpportunityLineItem.IncrementCompteurOPPLine(lOppLineToUpdate, lastCompteurOppLine);
            }
        }
    }

    public static Integer getLastCompteurOppLine() {
        Integer lastCompteurOppLine = 0;
        Date lastYear = Date.today().addMonths(-12);
        // Récupérer le dernier enregistrement avec un Code_OLI
        List<OpportunityLineItem> lastOppLineCodeOLI = [SELECT Id, Code_OLI__c
                                                        FROM OpportunityLineItem 
                                                        WHERE Code_OLI__c > 0 
                                                        ORDER BY Code_OLI__c DESC 
                                                        LIMIT 1];

        // Récupérer la dernière valeur du Code_OLI
        if (lastOppLineCodeOLI.size() > 0) {            
            lastCompteurOppLine = (Integer)lastOppLineCodeOLI[0].Code_OLI__c;
        }

        return lastCompteurOppLine;
    }
    
    public static List<OpportunityLineItem> IncrementCompteurOPPLine(List<OpportunityLineItem> lOppLine, Integer lastCompteurOppLine){
        for(OpportunityLineItem oppLine :lOppLine){
            lastCompteurOppLine++;
            oppLine.Code_OLI__c = lastCompteurOppLine;
        }

        return lOppLine;
    }

    public static void addProductFilter(List<OpportunityLineItem> oli){
        //Récupération des priceBookEntry ids
        Set<Id> idPriceBook = new Set<Id>();
        for(OpportunityLineItem op :oli){
            idPriceBook.add(op.PricebookEntryId);
        }

        List<PricebookEntry> priceBookEntry = [Select p.Product2Id, p.Id From PricebookEntry p where p.Id in :idPriceBook];

        //Récupération des produits à partir du priceBookEntry
        Map<Id,Id> maps = new Map<Id,ID>();
        for(PricebookEntry pE :priceBookEntry){
            maps.put(pe.Id,pE.Product2Id);
        }

        //Modification du champ ProduitFiltreSession__c de l'OpportunityLineItem
        for(OpportunityLineItem o :oli){
            o.ProduitFiltreSession__c=maps.get(o.PricebookEntryId);
        }
    }

    public static void attachSession(list<OpportunityLineItem > oppLines){
        Set<Id> id_opp = new set<Id>();
        Set<Id> id_session = new set<Id>();
        Map<Id,Session__c> map_module = new Map<Id,Session__c>();
        list<OpportunityLineItem> po_module = new list<OpportunityLineItem>();
        for(OpportunityLineItem po : oppLines)  
        {
            if(po.Session_de_formation__c != null && po.Type_produit__c == 'Pack')
            { 
                id_opp.add(po.OpportunityId);
                id_session.add(po.Session_de_formation__c);
            }
        }
        
        po_module = [select Id, OpportunityId,PricebookEntry.Product2Id from OpportunityLineItem where Type_produit__c = 'Module' and OpportunityId IN :id_opp];
        
        for( Detail_pack_session__c  s : [select Id, Name ,Composant_session__r.Produits__c, Composant_session__c  from Detail_pack_session__c where Pack_Session__c IN :id_session ])
        {
            map_module.put(s.Composant_session__r.Produits__c,s.Composant_session__r);
        }  

        list<OpportunityLineItem> poToUpdate;
        
        for(OpportunityLineItem po: po_module)
        {
            if(map_module.ContainsKey(po.PricebookEntry.Product2Id) )
            {
                po.Session_de_formation__c = map_module.get(po.PricebookEntry.Product2Id).Id;
            }
        }
                
    }

    public static void createOppLineItem(list <OpportunityLineItem> oppLines)
    {
        // GGA 30/11 - Le trigger ne doit pas se déclencher si le champ système est rempli (il est rempli par WF à la création). 
        // En cas de clonage, le champ serait rempli donc ne se déclenche pas.
        list<OpportunityLineItem> po_clonage = new list<OpportunityLineItem>();
        for(OpportunityLineItem clonepo :oppLines)  
        {                
            if(clonepo.Champ_syst_me_pour_clonage__c == null)
            {
                po_clonage.add(clonepo);
            }
        }

        if (po_clonage.size() > 0)
        {
            list <OpportunityLineItem> oppLineItemsToInsert= new list <OpportunityLineItem>();
            set<id> ProductsIds = new set<id>();
            set<id> packProductsIds = new set<id>();
            map<id,List<Detail_pack__c>> mapPackModuleProducts = new map<id,List<Detail_pack__c>>();
            List<Detail_pack__c>  moduleProducts = new List<Detail_pack__c>();   
            List<OpportunityLineItem> oppLineFormationCourte = new List<OpportunityLineItem>();
            Id OppFormationCourteId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Formation courte').getRecordTypeId();
            
            Set<Id> OppIds = new Set<Id>();
            for (OpportunityLineItem oppLineItem: po_clonage){
                OppIds.add(oppLineItem.OpportunityId);
            }
            
            Map<Id,Opportunity> mpOppById = new Map<Id,Opportunity>([SELECT Id, RecordTypeId FROM Opportunity where ID in :OppIds]);
            for (OpportunityLineItem oppLineItem: po_clonage){
                Opportunity opp = mpOppById.get(oppLineItem.OpportunityId);
                if(opp != null && opp.RecordTypeId == OppFormationCourteId){
                    oppLineFormationCourte.add(oppLineItem);
                }
            }
            
            for (OpportunityLineItem oppLineItem: oppLineFormationCourte){
                ProductsIds.add(oppLineItem.Product2Id);
            }
            
            map<id,Product2> mapProducts = new map <id,Product2>([select id,Produit_Pack__c from product2 where id IN: ProductsIds ]);
            for (OpportunityLineItem oppLineItem: oppLineFormationCourte){
                if (mapProducts.get(oppLineItem.Product2Id).Produit_Pack__c){
                    packProductsIds.add(oppLineItem.Product2Id) ;   
                }
            }
            
            moduleProducts = [select Pack__c,Composant__c from Detail_pack__c where Pack__c IN: packProductsIds];
            for (Detail_pack__c prod: moduleProducts){
                
                if (mapPackModuleProducts.containsKey(prod.Pack__c))
                {
                    mapPackModuleProducts.get(prod.Pack__c). add(prod);
                }
                else {
                    mapPackModuleProducts.put(prod.Pack__c, new  List <Detail_pack__c> { prod });
                }
            }
            
            
            for (OpportunityLineItem oppLineItem: oppLineFormationCourte){                
                if (mapProducts.get(oppLineItem.Product2Id).Produit_Pack__c){                    
                    if (mapPackModuleProducts.get(oppLineItem.Product2Id)!=null){                        
                        for (Detail_pack__c pro : mapPackModuleProducts.get(oppLineItem.Product2Id)){                            
                            OpportunityLineItem newOppLineItem = new OpportunityLineItem();
                            
                            PricebookEntry[] listPricebookEntry = [Select p.UseStandardPrice, p.UnitPrice, p.SystemModstamp, p.ProductCode, p.Product2Id, 
                                                                p.Pricebook2Id, p.Name, p.LastModifiedDate, p.LastModifiedById, p.IsDeleted, p.IsActive, p.Id, 
                                                                p.CreatedDate, p.CreatedById 
                                                                from PricebookEntry p where p.Product2Id =: pro.Composant__c And Pricebook2Id IN (Select Pricebook2Id From Opportunity Where ID =:oppLineItem.OpportunityId) limit 1];
                            
                            if (listPricebookEntry.size() > 0){
                                newOppLineItem.PricebookEntryId = listPricebookEntry[0].Id;
                                newOppLineItem.OpportunityId= oppLineItem.OpportunityId;    
                                newOppLineItem.UnitPrice =0;
                                newOppLineItem.Quantity = oppLineItem.Quantity; 
                                
                                oppLineItemsToInsert.add(newOppLineItem);
                            }                        
                        }
                    }
                    
                }
            }
            
            insert oppLineItemsToInsert;
        }

        
    }  
}