force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/Convsta_Conditions_Contractuelles__c.object-meta.xml
<CustomObject>
    <description>Informations relatives aux conditions contractuelles de l&apos;étudiant en entreprise - A saisir pour sa demande d&apos;expérience professionnelle.</description>
    <label>Conditions Contractuelles</label>
    <nameField>
        <displayFormat>contrat-{000000}</displayFormat>
        <label>Convsta Conditions Contractuelles</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions Contractuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/Code_Devise__c.field-meta.xml
<CustomField>
    <fullName>Code_Devise__c</fullName>
    <defaultValue>&apos;EUR&apos;</defaultValue>
    <description>Le code de la devise dans laquelle l&apos;étudiant sera rémunéré dans le cadre de son expérience professionnelle (ex: EUR, USD, CHF, etc.)</description>
    <inlineHelpText>Le code de la devise dans laquelle l&apos;étudiant sera rémunéré dans le cadre de son expérience professionnelle (ex: EUR, USD, CHF, etc.)</inlineHelpText>
    <label>Code Devise</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convsta_Conditions_Contractuelles__c/fields/MD_Demande__c.field-meta.xml
<CustomField>
    <fullName>MD_Demande__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Conditions Contractuelles</relationshipLabel>
    <relationshipName>Conditions_Contractuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/ByPass_RV__c.field-meta.xml
<CustomField>
    <fullName>ByPass_RV__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass RV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Convsta_Conditions_ContractTriggerTest.cls
@isTest
public class Convsta_Conditions_ContractTriggerTest {
       @testSetup
    static void setup(){
        Id pResp = [select id from profile where name='Responsable Pédagogique'].id;
        list<user> userList = new list<User>();
        userList.add( new User(alias = 'test123', email='test123@noemail.com',ByPass_RV__c =true,
                               emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='FR',
                               localesidkey='en_US', profileid = presp, country='France',IsActive =true,
                               timezonesidkey='America/Los_Angeles', username='respPeda@noemail.com'));
        
        insert userList;
    }
    
    @isTest
    public static void test(){
        Case demande = TestDataFactory.getCaseWithSigners();
        user usr = [select id, username from user where username='respPeda@noemail.com' limit 1];
        demande.ownerId=usr.id;
        insert demande;
        system.runAs(usr) {
            Convsta_Conditions_Contractuelles__c condition = new Convsta_Conditions_Contractuelles__c(MD_Demande__c = demande.Id);
            insert condition;
            
            condition.Code_Devise__c = 'EUR';        
            update condition;
        }
        //Only code coverage
    }
}